### ISSUE TITLE
Peer dependencies not working with react 18+

### ISSUE THREAD

**Issue by raphaelguimaraeszup** [reactjs/react-modal#1005]
### Summary:

I upgraded my react & react dom dependencies to 18.2.0 and when I try to run `npm i` my build process is breaking.

### Steps to reproduce:

 1. Update React & React to v18+
 2. Try run `npm i`

### Expected behavior:

Install and build the project.

### Link to example of issue:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16 || ^17" from react-modal@3.14.4
```

### Additional notes:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16 || ^17" from react-modal@3.14.4
```

**Comment by diasbruno** [comment]
@raphaelguimaraeszup  Essa versao do react-modal eh antiga. Atualize.

**Comment by diasbruno** [comment]
Prefira v3.16+.

**Comment by diasbruno** [comment]
A @ZupIT em peso nos like... :joy:

**Comment by diasbruno** [comment]
@raphaelguimaraeszup deu bom?

**Comment by raphaelguimaraeszup** [comment]
@diasbruno minha versão já está na indicada "react-modal": "^3.16.1",

**Comment by raphaelguimaraeszup** [comment]
@diasbruno refiz o teste aqui, excluindo a node modules e só rodando `npm i` aparentemente resolveu para essa dependência sim, agora estou com problema em outra. Devo ter feito o último teste antes de ter atualizado para essa versão 3.16.x, obrigado.
