### ISSUE TITLE
When I try to apply css variables from css modules in React, nothing is passed

### ISSUE THREAD

**Issue by uuzelac** [reactjs/react-modal#1021]
### Summary:

This is my `styles.module.css` that I imported into my `Modal.tsx`:

```
.modalOverlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(13, 13, 13, 0.52);
}

.modalContent {
  position: absolute;
  top: 50%;
  left: 50%;
  right: auto;
  bottom: auto;
  margin-right: -50%;
  transform: translate(-50%, -50%);
  padding: 40px;
  background-color: var(--gray);
  border-radius: 20px;
  outline: none;
  box-shadow: 2px 3px 24px rgba(203, 190, 163, 0.27);
}
```

```
import Modal from 'react-modal';
import styles from './styles.module.css';

<Modal
      isOpen={modalIsOpened}
      className={styles.modalContent}
      overlayClassName={styles.modalOverlay}>

   ...
   <CustomForm ... />
   <CustomButton ... />
</Modal>
```

The problem is that this `var(--gray)` doesn't work. Also if I import any custom button or form that is also using `styles.module.css` that contains `var(--some-color)` that var returns nothing. I am using theme provider around my `<App />`  component that holds all the values for the colors values. I need this for the theme switching.

**Comment by RajivRnjan** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by hklohani** [comment]
style={{
    '--gray': 'your color',
  }}
  
  Hey, do like this and let me know if it works

**Comment by diasbruno** [comment]
@uuzelac @RajivRnjan @Zaid1681 Thanks for the interest on working on this, but first things first...

- Is `--gray` defined anywhere? 
- Does @hklohani 's suggestion works?

**Comment by diasbruno** [comment]
Second and the funny one....what is quine? Can you guys point me to this project?

**Comment by uuzelac** [comment]
So imagine that you have just two colors that you pass as an object to your `<Root />` component like this:

```
theme = {
    '--black': '#000000',
    '--white': '#FFFFFFF',
}
```

```
const App = () => {
  return (
    <div style={{ ...theme }}>
      <Root />
    </div>
  );
};
```

This way all css modules for example `styles.module.css` in your `Root` can access these values like this:

```
.button {
  background-color: var(--black);
}
```

**except** `ReactModal` because it is created outside of the `App` component. As I saw in the documentation `ReactModal` is a React Portal and it is rendered on the top of everything which is ok but that makes a bit difficult to use themes, providers or something that is a wrapper around `Root` component. I didn't find any other elegant solution for this case scenario. Maybe there is something in the documentation which I overlooked, so please point me in the right direction if I made some mistake.

Thanks

**Comment by diasbruno** [comment]
Thanks. Is there anything else in the middle that handles the `theme`'s object to be properly scoped? A library, a compiler transformer (loader or whatever)?
