### ISSUE TITLE
How can i make the modal overlay non blocking? 

### ISSUE THREAD

**Issue by Ahmed-Ateeq** [reactjs/react-modal#1031]
Hello, we do have a prop to disable closing the modal on overlay click and we can hide the overlay using css / styling. But is there a way to make the background / overlay non blocking, meaning that the user should be able to interact with the background (currently the overlay blocks the background)

**Comment by diasbruno** [comment]
What you want is not a modal...modal is a blocking activity.

**Comment by Ahmed-Ateeq** [comment]
hmm true. The concept for the modal is a bit different than what I want to achieve. 

Thanks btw 👍, giving it the same height as the content and unsetting top makes it non blocking (i'm doing this only for mobile screens because I want the modal to behave like a bottom sheet).
