### ISSUE TITLE
Simple question - integrating in Rails

### ISSUE THREAD

**Issue by TimCannady** [reactjs/react-modal#104]
Apologies for the beginner question. How do I integrate this in Rails?

I've tried bundling both react-modal and react-dom, but it can't find the gem. I tried including it in the require tree of application.js, and it breaks.

Thanks for any beginner guidance.

**Comment by dziulius** [comment]
You need to build it using webpack (or browserify if you know how to write build recipe).

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in over a year. I'm assuming that this is no longer an issue. If it is, please feel free to re-open.
