### ISSUE TITLE
Avoid Scroll position being kept

### ISSUE THREAD

**Issue by kmthorsnes** [reactjs/react-modal#1044]
### Summary:
- The modal position is kept if exit on bottom and re-entered

### Steps to reproduce:

 1. Open Modal
 2. Scroll to bottom of content 
 3. Exit modal 
 4. Re-enter modal
 5. Observe the modal being in the scroll position it was left in step 3.

### Expected behavior:
- I want the modal to always have topp position when i enter it, regardless of earlier visitt or not. 

### Additional notes:
- I have looked at the `preventScroll` atribute, but that does not look to be what im looking for?

**Comment by diasbruno** [comment]
@kmthorsnes Do you see this behavior in all browsers? Which version of react and react-modal are you using?

**Comment by kmthorsnes** [comment]
@diasbruno Thank you for replying! 
> Do you see this behavior in all browsers? 
Yes, I have tested with brave, safari and firefox. 

> Which version of react and react-modal are you using?
- React: `17.0.2`
- react-modal: `3.11.2`

**Comment by diasbruno** [comment]
`preventScroll` was released on version `3.12.1`. But we also don't have any "reported bugs" since its release.

**Comment by diasbruno** [comment]
Ah sorry. 

If you have this configuration:

```jsx
<modal>
   <your_component /> <----
</modal>
```

`your_component` will always be rendered, it's just not attached to the dom tree. The dom elements it produces may live longer and this explains why it persists the scroll position.

You'll probably need to, on exit, use `container.scrollTo(0,0)` (or something like this).

**Comment by diasbruno** [comment]
`preventScroll` actually focus the element that triggers the modal to open.

**Comment by kmthorsnes** [comment]
@diasbruno Thank you! I'll have a closer look at this!

**Comment by diasbruno** [comment]
I'll close this for now. Please feel free to reopen if that doesn't help. Thanks!
