### ISSUE TITLE
Add support for React 19

### ISSUE THREAD

**Issue by ryami333** [reactjs/react-modal#1052]
The stable React 19 [release](https://github.com/facebook/react/releases) has just dropped. If nothing else, the `peerDependencies` will need to be updated to include `19`.

**Comment by zacharytyhacz** [comment]
Last commit 10 months ago. v4 last commit 2 years ago

It's likely this package is no longer maintained unfortunately. 

We gotta fork it and update it

**Comment by ryami333** [comment]
You might be right, but it is under the reactjs namespace, surely a core maintainer could make this update.

**Comment by zacharytyhacz** [comment]
I hope so

**Comment by diasbruno** [comment]
@zacharytyhacz PRs are always welcome.

**Comment by diasbruno** [comment]
Peer dependencies to allow react 19 is now update.

Please, bring feedback if it didn't work, and, how it behaves on the newest react version.

**Comment by lhtdesignde** [comment]
Amazing! Thank you.
