### ISSUE TITLE
node version restriction in patch version

### ISSUE THREAD

**Issue by herrwitzi** [reactjs/react-modal#1053]
### Summary:
With the last update to version 3.16.2 the node engine is restricted to versions between 8 and 18
This is a breaking change for projects that use a newer node version.

### Steps to reproduce:
 1. try to  `npm install react-modal@3.16.2` in a node environment with a version greater than 18

### Expected behavior:
node version shouldn't be restricted as it was in the previous verison 3.16.1 otherwise it should be a major release and not a patch-version

**Comment by herrwitzi** [comment]
For now i fixed it with an override of the version in my package.json

```json
{
  "overrides": {
    "react-modal": "3.16.1"
  }
}
```

and for yarn users:
```json
{
  "resolutions": {
    "react-modal": "3.16.1"
  }
}
```

**Comment by diasbruno** [comment]
The restriction is about the changes nodejs made from node 18+, where they changed the cryptography stuff...It's not necessary though.
