### ISSUE TITLE
Non-actionable warning in console: You tried to return focus to null but it is not in the DOM anymore

### ISSUE THREAD

**Issue by coderberry** [reactjs/react-modal#11]
I am seeing a lot of messages in the console: `You tried to return focus to null but it is not in the DOM anymore`. I am unsure how to make this warning go away.

**Comment by misuba** [comment]
I notice the stuff in that commit doesn't seem to be in the code anymore... and I'm having this issue.

**Comment by glifchits** [comment]
@misuba I'm with you there. I get the warning almost every time state most places in my app change, even when the modal is not open.

**Comment by jeffutter** [comment]
I am seeing this too. @mzabriskie can we reopen this issue?

**Comment by jccode** [comment]
Still seeing this warning too.  :(

Reproduce steps:

1. Construct 2 modals, named it modal_A and modal_B. 
2. Open modal_A (with one button). 
3. In modal_A 's click handler, try to close modal_A and open modal_B.
4. When you try to close modal_B, you can see the warning messages in console window.

**Comment by mrkvngrkn** [comment]
I'm getting this warning since I've upgraded to React v16

**Comment by diasbruno** [comment]
@jccode @mrkvngrkn Please follow issue #577. We are discussing how we are going to handle this properly.
