### ISSUE TITLE
Way to keep modal around even if the parent component is removed?

### ISSUE THREAD

**Issue by reywright** [reactjs/react-modal#111]
I'm thinking that sometimes you might want to have a modal between routes. I'm currently trying to do this... the problem is that it forces me to put the modal on a component outside of the router. It would be nice if there were some tools that allowed me to unmount manually, either in a flux / redux sort of architecture, or on another component.

**Comment by diasbruno** [comment]
@reywright Interesting use case. yeah, you'll need to put the Modal in some place where you can reference it (state), because it is not owned by the any of the other components - they just use it. 
(Hope I got it right.)

Hope you have found a solution.

**Comment by reywright** [comment]
I did. Basically I have react-modal above where I put my routes at, and use a data store (in my case redux) to notify the modal when to trigger... then I have a timeout (again redux) when it hits the next route to hide it.. so now it works.

**Comment by claydiffrient** [comment]
It's been a while since there was any discussion on this issue.  From the comments, it seems a way of doing this was found. I'm assuming that it isn't a problem anymore.  If it is, feel free to re-open the issue.
