### ISSUE TITLE
Double scroll-bar after open the modal with a long detail in body.

### ISSUE THREAD

**Issue by tairy-potter** [reactjs/react-modal#114]
![image](https://cloud.githubusercontent.com/assets/15603495/12164744/96eaef48-b54a-11e5-9469-d6c2e4132553.png)

**Comment by megapctr** [comment]
Isn't this a problem with how bootstrap styles modals?

**Comment by ryanflorence** [comment]
A pull request with css that works better would be great, but please note the CSS has never been the primary feature here, that's why you have to inject, the idea is you add your own CSS to make it look like your app (and do whatever CSS you need).

**Comment by halt-hammerzeit** [comment]
+1, having the same issue.

The solution is to set:
```
.ReactModal__Overlay
{
  overflow: scroll;
}
```

And also add and remove this class to the body
```

body.body--fixed {
  height: 100%;
  overflow: hidden;
}
```
