### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by haotangio** [reactjs/react-modal#119]
I'm using Node.js + Browserify + React.js and they're working well. 

But when I use `Modal = require('react-modal')`, the error is show on browser console: `Uncaught Error: Mismatched anonymous define() module` (although the modal is still working).

Do I need to add any configuration to resolve it?

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in almost a year. I'm assuming that this is no longer an issue. If it is, please feel free to re-open.
