### ISSUE TITLE
Background window responds however popup is still open

### ISSUE THREAD

**Issue by coolReactDev** [reactjs/react-modal#124]
I have a problem, eventhough the modal is open if I click on a background html control like button or text its responding keyboard event. Another way is to Click on URL and navigate to the control using keyboard.

I downloaded the basic demo modified the code to not close on outside clicks, added another text box beside the "Open Modal" button. I could type on the text box with modal active in the foreground by doing above steps

 handleModalCloseRequest: function() {
        this.setState({modalIsOpen: true});
      },

Can you help on this?

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in almost a year. I'm assuming that this is no longer an issue. If it is, please feel free to re-open.
