### ISSUE TITLE
Transfer to reactjs

### ISSUE THREAD

**Issue by mjackson** [reactjs/react-modal#127]
We're merging @rackt with the @reactjs GitHub org. Just wanted to let everyone know we'll be transferring this repo over there.

**Comment by Gouthamve** [comment]
:+1: Nice. But this broke the demo links. It would be great if you could fix them as reactjs.github.io is redirecting to the official react website.

**Comment by mjackson** [comment]
We're working on it.

**Comment by ConAntonakos** [comment]
Awesome! Thank you for all the hard work!
