### ISSUE TITLE
Project maintenance and development

### ISSUE THREAD

**Issue by Aweary** [reactjs/react-modal#130]
@ryanflorence @mzabriskie it seems like this repo is all but abandoned. The last release was October 23rd 2015. There are 17 open pull requests, most with no acknowledgement.

Is there any intention to maintain this project? It's a very well built component, but there are a few things I'd like to see (and the community would like to see, I'd bet) fixed/implemented.

 I'd like to contribute, but I don't want to waste my time with a PR if its never going to be merged/reviewed, you know?

I know you guys are super busy with other bigger projects, but if there's a way to let some other folks maintain/develop this project I think the community would appreciate it.

**Comment by evoyy** [comment]
The maintainers are avoiding like the plague. I don't blame them. There are issues that can't be resolved without a major re-design.

**Comment by Aweary** [comment]
@evoyy it seems that way. @ryanflorence @mzabriskie just a small acknowledgement on the project status or your intentions to maintain it would be great. At the very least just explicitly say that you don't have any intentions to maintain it.

**Comment by cogell** [comment]
:+1: some info would be great

**Comment by Aweary** [comment]
@ryanflorence ping! :rocket:

**Comment by claydiffrient** [comment]
@Aweary, I was made a collaborator on the project today.  The company I work for (Instructure) and myself personally have a vested interest in this project.  I'm working on sorting out the issues and the PRs now, but look forward to seeing some PRs be merged and some issues closed soon.  I'm going to go ahead and close this issue as the project will continue to be developed and maintained.

**Comment by Aweary** [comment]
@claydiffrient great to hear, looking forward to seeing this project start growing again!
