### ISSUE TITLE
Error: You must set an element with `Modal.setAppElement(el)` to make this accessible

### ISSUE THREAD

**Issue by vonwao** [reactjs/react-modal#133]
I get error, but CHANGELOG says:

v0.5.0 - Tue, 22 Sep 2015 19:19:44 GMT
[changed] setAppElement method is now optional.

So I'm confused.

Error: react-modal: You must set an element with `Modal.setAppElement(el)` to make this accessible
    at validateElement (index.js:224)
    at show (index.js:211)
    at Object.toggle (index.js:219)

**Comment by zires** [comment]
Same problem here

**Comment by yachaka** [comment]
Hello,

Same problem here.  
The whole problem is the scripts being loaded at the top of the page. `react-modal` was trying to set the app element to `document.body`, while it doesn't exist yet. If you did the same, within your code, it resulted as the same as your script was probably loaded before the DOM too.

I solved it by calling it in the lifecycle method `componentWillMount`:
```js
componentWillMount() {
    Modal.setAppElement('body');
 },
```

I can create a pull request solving this issue if you wish to?

**Comment by ryanflorence** [comment]
woah, what? that should not be optional, that's the whole point of this library.

**Comment by stkrzysiak** [comment]
Thank you @yachaka for that snippet, solved my issue.  I ran into this when running tests, fwiw.

**Comment by yachaka** [comment]
@ryanflorence The doc is precising that it's optional, and that by default react-modal is anchored to `document.body` (which isn't, as the DOM isn't existing yet):
```
/*
By default the modal is anchored to document.body. All of the following overrides are available.

* element
Modal.setAppElement(appElement);

* query selector - uses the first element found if you pass in a class.
Modal.setAppElement('#your-app-element');

*/
```
I guess the doc/or the code has to change?

**Comment by ungoldman** [comment]
I only got this error when we switched to using webpack-dev-server. Very weird.

**Comment by ungoldman** [comment]
Update: injecting the bundled application JS into `<body>` instead of `<head>` seems to have solved it for me for now, but I think ideally react-modal should wait until the DOM is loaded to try attaching to `document.body` (if that's what's going on).

**Comment by RobinClowers** [comment]
The `appElement` is only used in one place: https://github.com/reactjs/react-modal/blob/master/lib/components/Modal.js#L75, and isn't documented at all. I think that line should be using the closed over `appElement` variable instead.

**Comment by radixhound** [comment]
This happened for me when moving to webpack. It was working fine before. I don't understand it but adding the `componentWillMount` snippet fixed it for me as well.

**Comment by halt-hammerzeit** [comment]
**yachaka**'s advice worked for me too on fixing this bug

**Comment by figandbones** [comment]
I got this problem too, like ungoldman, when we started building/running with webpack. No one's advice was helping. We have a 'common' project, which had the code that was using react-modal, and was deployed to the main app project. I had to move the modal code to the main app project to git it to work.

**Comment by diasbruno** [comment]
Depending on when it evaluates [react-modal@1.6.5:/lib/helpers/ariaAppHider.js#L1](https://github.com/reactjs/react-modal/blob/v1.6.5/lib/helpers/ariaAppHider.js#L1), `document.body` can not exist yet and it will resolve to `undefined || null` and when call `validateElement(appElement)` the error is thrown. This can happen if `Modal.setAppElement()` is called with null or not called at all (probably it can also happen if called with a selector that does not match any results).

If you don't want to depend on `setAppElement`, your `<script />` must be placed inside `<body />`.

@yachaka snippet prevents this behavior by defining the element before placing the `<Modal />`.

Too late to help, but I hope new users can understand what is going on if they face this issue.

**Comment by royrwood** [comment]
I started getting this error/warning yesterday after upgrading my react-modal and react libs to the latest versions.  To make the error/warning go away, I modified my main `.jsx` file to include an explicit call to `Modal.setAppElement( )` like this:

<pre>
// Weird-- we get warnings in the console if we don't explicitly set the Modal appElement...
Modal.setAppElement('body');

ReactDOM.render(myAppBody, document.getElementById('index-main-div'));
</pre>

And yes, my Javascript is a child of the HTML body, as suggested by @ungoldman...

```
<html>
...
...
    <body>
        <div id="index-main-div"></div>

        <script src="./js/myapp.js"></script>
    </body>
</html>
```

**Comment by damorton** [comment]
```
<ReactModal
        appElement={document.getElementById('app')}
...
```
FYI This also works.

**Comment by catamphetamine** [comment]
@damorton Not, it doesn't.
There's no `document` on the server.

**Comment by yantakus** [comment]
```
document && document.getElementById('#app') && ReactModal.setAppElement('#app');
```

**Comment by joe-oli** [comment]
Is the following possible with react-modal, if the modal is used within a component only, can it be mounted such that the overlay covers only that component - and not parent / grandparents of that component ? I tried it, it didn't seem to work, it went back to covering the whole screen.

**Comment by maevadevs** [comment]
`componentWillMount()` is flagged UNSAFE in v16.3+ and will be deprecated in v17. `componentDidMount()` does the trick for me.

**Comment by tahv0** [comment]
What have you done when testing single child component? Then root App is not included.

**Comment by ldvndev** [comment]
Thank you @yachaka for that snippet, solved
