### ISSUE TITLE
Using a stylesheet rather than inline styles

### ISSUE THREAD

**Issue by wavded** [reactjs/react-modal#137]
There doesn't appear to be away to turn off the defaultStyles, which makes it difficult if you are managing a project which styles are maintained in css files and not inside react components.  Can there be an option to turn inline styling off?

**Comment by claydiffrient** [comment]
@wavded https://github.com/reactjs/react-modal/pull/100 should fix that... unfortunately, it's been waiting to be merged **forever**

**Comment by claydiffrient** [comment]
#100 was merged now, so I'm going to go ahead and close this out.  The next release will include that feature.
