### ISSUE TITLE
Invariant Violation: findComponentRoot

### ISSUE THREAD

**Issue by guo0693** [reactjs/react-modal#146]
`<Modal
                isOpen={isUserModalOpen}
                onRequestClose={closeUserModal}
                style={customStyles} className="user-modal">
                <UserForm formData = {userModalData} />
            </Modal>`

When I try to add a composite component inside the modal, i got below error. I think it's because the modal's render function returns null and insert elements into the ModalPortal. Any suggestions on how to avoid this error?

invariant.js:39 Uncaught Error: Invariant Violation: findComponentRoot(..., .2.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

UserForm is just a dynamic form from redux-form lib:

const { Component } = React;
const { reduxForm } = require("redux-form");
const Fields = require("./schema/fieldsGenerator");

class UserForm extends Component {

```
addField(field) {
    if (!_.isEmpty(field)) {
        switch (field.type) {
        case "group":
            return (<div className={field.className} key={field.name}>
                <h4>{field.header}</h4>
                {field.children.map(( childField ) => {
                    return this.addField(childField);
                })}
            </div>);
        case "text":
            return (<div className={field.wrapperClassName} key={field.name}>
                <label className={field.labelClassName}>{field.label}</label>
                <input key={field.name} { ...field }/>
            </div>);
        case "button":
        case "dropdown":
        case "radio":
        case "checkboxList":
        case "react":
        default:
            return "";
        }
    }
}

render() {
    const { onSubmit, formData } = this.props;
    let fields = Fields.fromUserData(formData);
    return (
        <form onSubmit={ _.noop } className="user-modal-form">
            {fields.map((field) => {
                if (field.hasOwnProperty("name")) {
                    return this.addField(field);
                }
            })}
        </form>
    );
}
```

}

module.exports = reduxForm({ "form": "user-form" })(UserForm);

**Comment by diasbruno** [comment]
@guo0693 Can you provide more info on this (react, react-dom and react-modal versions)? If possible, can you make a simple example? 

You can use @rmertens' [react-modal-bug-example](https://github.com/rmertens/react-modal-bug-example) as a bootstrap.

**Comment by guo0693** [comment]
"react": "0.14.2",
 "react-dom": "0.14.2",
 "react-modal": "^0.6.1"

Will draft an example once I get time.

Thx :)

**Comment by danbovey** [comment]
I got this error on `react-modal@1.2.0` but not on `react-modal@0.6.1`, so I knew it would be something with dependencies.

I fixed it by upgrading React and ReactDOM to `15.0.1` with `react-modal@1.2.0`

**Comment by asyncanup** [comment]
react and react-dom should really have been peerDependencies
Fails for us otherwise because we have a dependency repo that uses react-modal, linked into main application via `npm link`. So webpack gets a duplicate React in the bundle.

**Comment by claydiffrient** [comment]
It's been a while since there was any discussion on this issue.  I'm assuming that it isn't a problem anymore.  If it is, feel free to re-open the issue.

**Comment by byondrealdev** [comment]
@claydiffrient we moved on to use something else. not sure if the problem got solved or not.
