### ISSUE TITLE
Export defaultStyles

### ISSUE THREAD

**Issue by tyrsius** [reactjs/react-modal#147]
This is a feature request. I would like to be able to globally alter the default styles for the modal without needing to wrap the component. Exporting the default styles, or exporting a function that modified the default styles, would facilitate this pretty easily.

**Comment by claydiffrient** [comment]
@tyrsius In the next release #100 will be available allowing you to override the default styles by use of CSS classes.  Is this adequate for your use case?

**Comment by tyrsius** [comment]
Its a nice step, but it doesn't fully solve this. I would still have to either provide those classes to every Modal instance, or wrap it with my own component to put the classes on.

Allowing the `defaultStyles` object to be modified would allow globally styling the modal without wrapping it.

These cases are definitely similar, but I think there is still value in exporting the default object.

**Comment by claydiffrient** [comment]
Cool cool, I'll dig in and see what I can do.  It likely won't be in the next release, but I can probably get it in shortly after that.

**Comment by tyrsius** [comment]
I can make a PR for this if you'd like. Since you are exporting `ModalPortal` as the default, moving the styles into their own module would probably make sense. Not sure where you want it, it doesn't really make sense in `components`

`lib/styles.js`
OR
`lib/styles/default.js`

Either of those look good?

**Comment by claydiffrient** [comment]
A PR would be awesome.  I think `lib/styles.js` would be okay.  I don't think we want to support multiple themes so I don't think specifiying `lib/styles/default` is necessary.

**Comment by tyrsius** [comment]
Will do

**Comment by tyrsius** [comment]
Here you go #148

**Comment by tyrsius** [comment]
I split it up, but I didn't consider that the built module doesn't surface everything, just the `Modal` component. I'm not sure what the best way to do that is. It feels weird to tack it on to the `Modal`...

**Comment by tyrsius** [comment]
#148 should take care of this

**Comment by claydiffrient** [comment]
Closed because of #148 being merged.
