### ISSUE TITLE
Buttons inside Modal ignore .selector:hover styles.

### ISSUE THREAD

**Issue by Diarsid** [reactjs/react-modal#150]
```
<Modal ...>
           <button type="button" className="in-dialog-button">Cancel</button>
</Modal>
```

If apply styles to selector .in-dialog-button with an external stylesheet, the button itself becomes styled quite well, but becomes completely inactive instead. It is impossible to press on it and it does not respond on mouse hover over it.

Is it possible to appy custom style to buttons inside Modal?

**Comment by Diarsid** [comment]
Sorry. I've investigated this issue and found out that buttons inside the Modal actually work properly.
They just completely ignore .selector:hover styles that's why it seems they become inactive. 

But they ignore :hover styles.

**Comment by emolr** [comment]
I have the same issue, i vote this up, it's a quite strange behaviour i haven't seen before

**Comment by emolr** [comment]
I figured out what tricked my issue which was 100% similar to @Diarsid. 
So you might have the same issue? 

I was doing feature detection and adding classes to the app in react. 
So for example: `no-touch` on non touch devises, and i don't style hover interactions when this class is not available.

The react app seemed like the root of the application, but this modal plugin renders the modal in the `<body>` root, so i changed my features list to add the classes to `<html>` instead. 

I hope it can be of some kind of help :)

**Comment by Diarsid** [comment]
If I remember correctly, react does not recommend to add its components nor in `<html>` neither in `<body>` directly, it recomends to introduce something like
```
<body>
    <div id="container"></div>
</body>
```
and have the 'container' as an app root. I'm not an expert in JavaScript and React also, that's why I'm not sure if @emolr solution satisfy all "best practices" requirements. 

As for my issue, I've solved it by using inline styles and explicit event listeners on the required component:
```
<button
         type="button"
         style={submitButtonStyle}
         onClick={this.submitAction}
         onMouseEnter={this.submitButtonToggle}
         onMouseLeave={this.submitButtonToggle}>
                 Submit
</button>
```
where submitButtonToggle is a function that simpy switches a boolean value in the component state:
```
submitButtonToggle: function () {
        this.setState({submitButtonHover: ! this.state.submitButtonHover});
},
```
and required inline style is obtained from an appropriate function:
```
getHoverButtonStyle: function () {
            if ( this.state.submitButtonHover ) {
                return styles.dialogButtonStyleHover;
            } else {
                return styles.dialogButtonStyle;
            }
},
```
Not sure if this solution is elegant one, but it works well.

**Comment by claydiffrient** [comment]
It's been a while since there was any traction on this issue.  I'm going to close it assuming it's no longer an issue.  If it is feel free to re-open.
