### ISSUE TITLE
React 15 compatibility?

### ISSUE THREAD

**Issue by leesiongchan** [reactjs/react-modal#151]
Is this safe to bump `react` to 15.0?

**Comment by EvNaverniouk** [comment]
I've opened a PR. My preliminary testing didn't find anything broken after upgrading, so it should be an easy process to get the PR merged: https://github.com/reactjs/react-modal/pull/152

**Comment by wikiwong** [comment]
I am currently seeing an error on Modal.js:79.

In:

`function sanitizeProps(props) {
  delete props.ref;
}`

Modal.js:79 Uncaught TypeError: Cannot delete property 'ref' of #<Object>

**Comment by claydiffrient** [comment]
v1.0.0 was just published and adds support for React 15
