### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-modal#155]
### Summary:

Using this with react-rails component and Rails 5. Nothing fancy. Got the error.

Error is here:

```
  componentDidMount: function() {
    this.node = document.createElement('div');
    this.node.className = 'ReactModalPortal';
    AppElement.appendChild(this.node);
    this.renderPortal(this.props);
  },
```

**Comment by claydiffrient** [comment]
@SylarRuby What is the actual error?

**Comment by SylarRuby** [comment]
Hi @claydiffrient. This is the actual error:

>Cannot read property 'appendChild' of null

Then when I click the modal button:

>Error: react-modal: You must set an element with `Modal.setAppElement(el)` to make this accessible

I have not used this package in a long time and I never used `var appElement = document.getElementById('your-app-element');` before. My old rails 4 project still works. Im on Rails 5.

**Comment by claydiffrient** [comment]
Hey @SylarRuby, if you are using version 1.0.0 which was released Friday, you likely shouldn't see that issue.  If you do then we've got a problem happening somewhere.

The `AppElement` is a container for your app.  Generally it should be set prior to your modal being used. In theory it should default to `document.body`, but many times you may want to specify a particular container element by specifying `Modal.setAppElement(el)` where `el` is either a DOM node or a selector for a DOM node such as `#main`, `#app`, or whatever it may be in your case.

This will make sure that the modal is fully accessible.

**Comment by SylarRuby** [comment]
@claydiffrient Yes, I'm using version 1.0.0. I'll have a dabble later tonight and report back. ,

**Comment by anshumanf** [comment]
`document.body` [may be `null`](http://stackoverflow.com/questions/9916747/why-is-document-body-null-in-my-javascript) before the `DOMContentLoaded `event. 

I can submit a pull request to set `AppElement` to `document.body` inside an event listener for `DOMContentLoaded` to fix:

> Cannot read property 'appendChild' of null

In addition, currently there is no default value for the `appElement` prop - it will not default to `document.body` even if the above change is made. So in my use case I had to use either `Modal.setAppElement()` or set the `appElement` prop in order to avoid triggering: 

> Error: react-modal: You must set an element with Modal.setAppElement(el) to make this accessible

**Comment by SylarRuby** [comment]
Yea this is not working for me.

**Comment by anshumanf** [comment]
@SylarRuby Could you try using [this fork](https://github.com/anshumanf/react-modal) I made to verify if your first problem is fixed by it?
You can put `git://github.com/anshumanf/react-modal.git#3db60232a77f4cf65b871095d56558f5c8d59014` as the version in your `package.json`.

**Comment by SylarRuby** [comment]
@anshumanf Im puzzled about this `appElement`. My component is like this:

```
var Foo = React.createClass({
  render(){
    return(
      <div>bar</div>
    )
  }
});
```

**In a rails html.erb:**

    <%= react_component("Foo") %>

How do I go about doing: `ReactDOM.render(<App/>, appElement);` in a rails situation?

**Comment by SylarRuby** [comment]
Guess I can close this. For I had to make few adjustments:

For my react comonent: 

    <%= react_component("Foo"), html_options={id: 'foo'} %> # the id must set here

In the add:

```
componentWillMount(){
    var el = document.getElementById('foo');
    Modal.setAppElement(el);
  },
```

The you call the modal in your component's render:

```
... 
return(
      <div>
        <Modal> ... </Modal>
     </div>
    )
...
```

**Comment by felixmc** [comment]
I found that moving my `<script>` tags from `<head>` to right before `</body>` fixed the issue for me without having to touch an js.

**Comment by biznickman** [comment]
I'm running into this exact issue as well with the following code:

```
import React, { PropTypes } from 'react';
import Modal from 'react-modal';

const ContactModal = (props) => (
  <div>
    <Modal
      isOpen={props.contactsStore.modalVisible}
      onRequestClose={props.contactsActions.closeModal} >
      <p>This is the modal</p>
    </Modal>
  </div>
);

export default ContactModal;
```

And the error is: `Cannot read property 'appendChild' of null`

**Comment by SylarRuby** [comment]
Why I have closed this? Still not working.

**Comment by diasbruno** [comment]
`Modal.setAppElement(el);` is necessary and should be called as a set up `react-modal` when using 1.6.5, but it will be deprecated on next releases.

It still open for discussion on issue #287.

I'm closing this issue for clean up. But if it is still relevant, please reopen this issue.
