### ISSUE TITLE
Consider merging with/deprecating in favor of react-overlays

### ISSUE THREAD

**Issue by ryanflorence** [reactjs/react-modal#156]
We don't need two libs for this: https://github.com/react-bootstrap/react-overlays

**Comment by claydiffrient** [comment]
That looks like a cool project.  Just looking at the examples page, the modal doesn't seem to maintain focus within the modal itself.  There is a prop that defaults to true to do it, but in my quick test it doesn't seem to behave properly.

It works fine for shift+tab, but doesn't seem to work the other way.  I'm all for merging/deprecating, but I want to make sure the accessibility story is complete on that side.

**Comment by ryanflorence** [comment]
I tested it out and it did.

**Comment by claydiffrient** [comment]
@diasbruno You've been really active on this project recently?  What are your thoughts.  I'm thinking it might be the way to go.

**Comment by diasbruno** [comment]
I don't really know what to say about this, but It seems a good lib.

**Comment by taion** [comment]
I can't personally claim that a11y has been an explicit requirement for us. @monastic.panic has done most of the work on react-overlays in general, though.

That said, if there's anything missing/broken/wrong, we would want to fix it. The library just should do the right thing.

**Comment by nathanmarks** [comment]
@taion We have a number of issues with our dialog/overlay system in https://github.com/callemall/material-ui. I'm going to give `react-overlays` a whirl to see what it can do for us. If it's a fit i'm sure you'll see some contributions coming back upstream to help with any fixes or issues!

**Comment by taion** [comment]
@nathanmarks Did anything ever come of that?

**Comment by alex-shamshurin** [comment]
react-modal is extremely slow

**Comment by doeg** [comment]
Hey @diasbruno, I think this issue can be closed out. 🙇 https://github.com/react-bootstrap/react-overlays is now deprecated in favour of https://github.com/react-restart/ui.
