### ISSUE TITLE
Can't get height of content

### ISSUE THREAD

**Issue by DaveStein** [reactjs/react-modal#157]
I'd love to get the height of dynamic content. I am passing in the text as a prop:

```
<ReactModal style={this.props.style} isOpen={this.props.open}>
  // Setting inner HTML for some arbitrary bold word
  <div dangerouslySetInnerHTML={{__html: this.props.content}} />
  <div className="right">
    <input ref="yes" type="button" value="Yes" />
    <input ref="no" type="button" value="No" />
  </div>
</ReactModal>
```

Setting styles like:

```
{
  width: '250px',
  marginLeft: '50%',
  left: '-125px'
}
```

I want to be able to measure the height so I can apply similar rules for vertical centering.

**Comment by diasbruno** [comment]
Hi @DaveStein. Now we have a `onAfterOpen()` callback. Maybe it can helps with this.

**Comment by DaveStein** [comment]
@diasbruno is there a strong reason to, or not to, have an option to allow auto centering? Seems like a common thing people would want and is usually default in other implementations. I can look into using the callback in the meantime

**Comment by diasbruno** [comment]
@DaveStein I think css is the best option, but maybe we can have some 'presets' for animations and positions.

`import { Style1, ... } from react-modal-presets;`

**Comment by claydiffrient** [comment]
It's been a while since there was any discussion on this issue.  I'm assuming that it isn't a problem anymore.  If it is, feel free to re-open the issue.
