### ISSUE TITLE
How can I close Modal by clicking overlay?

### ISSUE THREAD

**Issue by DaveStein** [reactjs/react-modal#158]
Just a question :)

**Comment by Diarsid** [comment]
Hi!
You should set **shouldCloseOnOverlayClick** attribute of your Modal to **true**.
```
<Modal
         closeTimeoutMS={0}
         isOpen={....}
         onRequestClose={....}
         shouldCloseOnOverlayClick={true}  // that's it!
         style={....} >
                  ...your content
</Modal>
```

**Comment by DaveStein** [comment]
Heh it mentions this in the testing section for some reason (I wasn't looking there cause I'm not running tests) but it says `By default the modal is closed when clicking outside of it (the overlay area). If you want to prevent this behavior you can pass the 'shouldCloseOnOverlayClick' prop with 'false' value.` so isn't this a bug then? I'm certainly not setting it to false.

**Comment by DaveStein** [comment]
nm `onRequestClose` needs to be defined as well!

**Comment by DaveStein** [comment]
PS: Obviously my brain was fried yesterday and I didn't RTFM well - sorry!
