### ISSUE TITLE
sanitizeProps causes error 

### ISSUE THREAD

**Issue by suprsidr** [reactjs/react-modal#160]
### Summary:
Uncaught TypeError: Cannot delete property 'ref' of #&lt;Object>
### Steps to reproduce:

 1. open modal
 2. Uncaught TypeError: Cannot delete property 'ref' of #&lt;Object>
Modal.js line 78 sanitizeProps(props) -> line 115 delete props.ref;

### Additional notes:
if I comment out the call to sanitizeProps all is good.

just upgraded to react 15.0.1 and react-dom 15.0.1
Worked fine prior

**Comment by diasbruno** [comment]
@suprsidr awesome! i'll check it.

**Comment by rmertens** [comment]
Getting the same error (also react 15.0.1)!

**Comment by diasbruno** [comment]
@rmertens can you make a simple example were you can reproduce it?

**Comment by rmertens** [comment]
@diasbruno uploaded here: https://github.com/rmertens/react-modal-bug-example

**Comment by wikiwong** [comment]
No mean to clutter, but I am getting the same error as well.  Feel free to tag me for any additional info I can provide.

Thanks for looking into this guys!

**Comment by diasbruno** [comment]
If `sanitizeProps(props)` is moved to `Modal::componentWillReceiveProps()`, it works fine.

`react: 15.0.1, react-dom: 15.0.1, react-modal: 1.1.1`

Is there a reason to `sanitizeProps()` is called in `Modal::renderPortal()`. @claydiffrient 

Some info from react docs:

> Never access refs inside of any component's render method – or while any component's render method is even running anywhere in the call stack.

[react/docs - Ref to Components](http://facebook.github.io/react/docs/more-about-refs.html)

**Comment by diasbruno** [comment]
Also tested with `react: 15.0.0, react-dom: 15.0.0, react-modal: 1.1.1` and works fine.

**Comment by claydiffrient** [comment]
Fixed released as v1.1.2
