### ISSUE TITLE
Moving location of parenthesis causes Invariant Violation error

### ISSUE THREAD

**Issue by UngaWunga** [reactjs/react-modal#167]
This code below works fine:

```
const TestCrap = React.createClass(
{
	render: function()
	{
		return (
			<div className="commentBox">
				Hello, world! I am a CommentBox.
			</div>
		);
	}
});
```

This causes an error:
"Uncaught Invariant Violation: ExportConfigGrid.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.invariant @ app.js:1126ReactCompositeComponentMixin._renderValidatedComponent @ app.js:7719ReactCompositeComponent__renderValidatedComponent @ app.js:1444ReactCompositeComponentMixin.mountComponent @ app.js:7326ReactCompositeComponent_mountComponent @ app.js:1444ReactReconciler.mountComponent @ app.js:5636ReactCompositeComponentMixin.mountComponent @ app.js:7331ReactCompositeComponent_mountComponent @ app.js:1444ReactReconciler.mountComponent @ app.js:5636mountComponentIntoNode @ app.js:2640Mixin.perform @ app.js:6743batchedMountComponentIntoNode @ app.js:2656Mixin.perform @ app.js:6743ReactDefaultBatchingStrategy.batchedUpdates @ app.js:10780batchedUpdates @ app.js:6248ReactMount._renderNewRootComponent @ app.js:2850ReactMount__renderNewRootComponent @ app.js:1444ReactMount._renderSubtreeIntoContainer @ app.js:2924ReactMount.render @ app.js:2944React_render @ app.js:1444(anonymous function) @ app.js:85__webpack_require__ @ app.js:20(anonymous function) @ app.js:40(anonymous function) @ app.js:43
app.js:43601 [Object, Object]"

```
const TestCrap = React.createClass(
{
	render: function()
	{
		return
		(
			<div className="commentBox">
				Hello, world! I am a CommentBox.
			</div>
		);
	}
});
```

Expected behavior is to not care about a dev formats their code. Whitespace in this scenario should make no difference. 
Using the following versions:
React v0.14.8
ReactDOM v0.14.8

Thanks

**Comment by claydiffrient** [comment]
It doesn't appear that this issue is with react-modal at all.  So I'm closing it.  That being said, the reason this fails is because of automatic semicolon insertion in JavaScript.  Essentially in the second case  your return statement is being automatically converted to `return ;` and is therefore returning `undefined` rather than your React component.  You shouldn't have a return statement on a line by itself.
