### ISSUE TITLE
react-modal dependent on existence of document.body

### ISSUE THREAD

**Issue by muffs** [reactjs/react-modal#170]
Hey,

I just want to preface this issue by saying that `react-modal` is awesome and I appreciate the work y'all have done for the JS community. 😍 

### Summary:

I'm working with a legacy code base who's bundle in included in the `<head>` tag. At runtime, `react-modal` runs the following line:
```javascript
var AppElement = ExecutionEnvironment.canUseDOM ? document.body : {appendChild: function() {}};
```

`document.body` is null since the document hasn't completed rendered yet.

### Steps to reproduce:

 1. Include your bundle in the `<head>` tag.
 2. Use `react-modal`.

Can be reproduced by making the following [changes](https://github.com/muffs/react-modal/commit/6c29b206d19130b9c4c709acad1bad07d98a9407) to the examples.

### Expected behavior:

I would either expect this to be documented or for `react-modal` to lazily access `document.body`.

### Additional notes:

A solution involves wrapping `document.body` in an anonymous function and invoking `AppElement` on every access.

**Comment by rdsteg** [comment]
Wait, what good does this do besides fix an unsupported feature?

**Comment by claydiffrient** [comment]
@muffs Thanks for opening this issue.  I'm afraid however that this is something we aren't going to try and fix at the library level.  Loading scripts at the bottom of the body is a current best practice.  If we were to try and hack around this and implement a fix for this at the library level we'd be going against that best practice.  The time, effort, and maintenance cost of having this in the library is just too much.

Again, thanks for the issue I hope you find an acceptable way to make it work in your project!

**Comment by muffs** [comment]
@claydiffrient thanks for the response :) I totally understand. I was unaware that this was an explicitly unsupported feature rather than an oversight.

For anyone else who stumbles on this issue, I ended up finding a solution by wrapping `react-modal`, key here is the `Modal.setAppElement(document.body)` :
```javascript
import React, { Component } from 'react';
import Modal from 'react-modal';

export default class MyModal extends Component {

  static propTypes = {
    isOpen: React.PropTypes.bool.isRequired,
    onAfterOpen: React.PropTypes.func,
    onRequestClose: React.PropTypes.func
  };

  constructor(props) {
    super(props);
    Modal.setAppElement(document.body);
  }

  render() {
    const {
      isOpen,
      onAfterOpen,
      onCloseClick,
      children
    } = this.props;

    return (
      <Modal className="modal"
             overlayClassName="modal-overlay"
             isOpen={isOpen}
             onAfterOpen={onAfterOpen}
             onRequestClose={onCloseClick}>
        {children}
      </Modal>
    );
  }

}
```

**Comment by javidjamae** [comment]
FYI - There is an `appElement` prop you can use:

```
<Modal
  appElement={ document.body }
  ...
>
```
