### ISSUE TITLE
set an element with `Modal.setAppElement(el) to element in virtual dom

### ISSUE THREAD

**Issue by richardadrian** [reactjs/react-modal#174]
I don't want to attach this to an element that exists on in the html.  I want to attach it to a div that is being created in a render (we are using react grid layout).  The message is saying that the element does not exist and when I look at the console it is true, it does not.  

How do I make this wait until the component is actually rendered?

**Comment by claydiffrient** [comment]
It's been a while since there was any traction on this issue.  I'm going to close it assuming it's no longer an issue.  If it is feel free to re-open.  I'm hoping the changes we are discussin gin #287 might be of use here.
