### ISSUE TITLE
React Select Incompatible with React Modal

### ISSUE THREAD

**Issue by maxmatthews** [reactjs/react-modal#177]
### Summary:
When using react-select (https://github.com/JedWatson/react-select) the modal crops the menu that appears. 
### Steps to reproduce:
```			
<Modal
	isOpen={this.state.showSwitchClient}
	onRequestClose={this.hideSwitchClient}
	className="modal modalSwitchClient"
	overlayClassName="modalOverlay"
>
	<div className="row">
		<Select
			onChange={this.onChange}
			options={clientOptions}
			placeholder="Select Client"
			clearable={false}
			onClose={this.closeSelect}
			value={this.state.selectedClient} />
	</div>
</Modal>
```

### Expected behavior:
Modal should allow overflow 

### Additional notes:
Not sure if this is something that needs to be fixed in this package or the react-select one. Both are extremely popular so I'm surprised they aren't' compatible. The issue has been opened on that package as well: https://github.com/JedWatson/react-select/issues/810 and https://github.com/JedWatson/react-select/issues/404

![screen shot 2016-05-23 at 11 20 34 am](https://cloud.githubusercontent.com/assets/4709710/15475496/611dbac2-20d8-11e6-87b5-b969267ccccc.png)

![screen shot 2016-05-23 at 11 03 24 am](https://cloud.githubusercontent.com/assets/4709710/15475247/1c10d096-20d7-11e6-983a-c3aef2acf3f7.png)

**Comment by everdimension** [comment]
Looks like a simple `overflow: hidden` rule at work. React-modal allows you to easily override default styles.

But if you wish to keep `overflow: hidden` rule and still have `react-select`'s dropdown to show properly, then it's not a problem with `react-modal`.

**Comment by maxmatthews** [comment]
@everdimension Thank you so much! You were right. Just had to add `overflow: visible` to the modal's CSS and that solved my issue.

**Comment by davidsonsns** [comment]
I had a similar problem with [ant.design](http://ant.design), `overflow: visible` working tks @maxmatthews
