### ISSUE TITLE
disable esc key close the modal

### ISSUE THREAD

**Issue by craigcosmo** [reactjs/react-modal#181]
esc key press will close modal. Anyway to prevent this? can there be an option?

**Comment by claydiffrient** [comment]
@craigcosmo What's your use case for this?  From an accessibility standpoint, pressing the escape key is a fundamental expected behavior for keyboard only users (http://webaim.org/resources/evalquickref/#keyboard)

**Comment by craigcosmo** [comment]
We dont want users mistakenly press esc close the form when filling it out. That would a terrible experinece. 

Craig




On Mon, Jun 13, 2016 at 2:17 AM +0700, "Clay Diffrient" <notifications@github.com> wrote:












@craigcosmo What's your use case for this?  From an accessibility standpoint, pressing the escape key is a fundamental expected behavior for keyboard only users (http://webaim.org/resources/evalquickref/#keyboard)

**Comment by deviantony** [comment]
You can prevent the modal from closing with the Esc key using something like that:

```javascript
class CantCloseMyModal extends React.Component {

  constructor() {
    this.state = {
      open: true,
      canClose: false,
    };
  }

//don't forget to bind it
close() {
    if (this.state.canClose) {
      this.setState({ open: false });
    }
  }

render() {
    return (
      <Modal
        isOpen={this.state.open}
        onRequestClose={this.close}
        shouldCloseOnOverlayClick={false}
      >
      ...
     </Modal>
);
}
```

You just need to set the variable `canClose` to true when you want to give the user the ability to close the modal.

**Comment by neekibo** [comment]
I also vote for an option. My use case is a color-picker (react-color) inside a modal (react-modal). On first escape I want to close the color-picker, not the modal. I am using react-keydown already, so all shortcuts would be handled consistently by react-keydown.

**Comment by claydiffrient** [comment]
@neekibo @craigcosmo After reviewing this carefully, I don't want to build this behavior into the modal itself.  It's another thing to maintain that in many (if not most) modal uses lowers the accessibility of the component.

I understand your concern for the use cases you have outlined, and I have not taken them lightly.  I would suggest you do something similar to what @deviantony suggested to prevent this in your use cases.

**Comment by craigcosmo** [comment]
I found out you can actaually have this featureby omit the `onRequestClose` property

by that, you call the component like this 
```jsx
<Modal
					overlayClassName="login-error-modal-overlay"
					className="login-error-modal"
					isOpen={this.state.modal}
                                        >
					<span class="login-error">you have duplicated option. option should be unique</span>
				</Modal>
```

**Comment by gevgeny** [comment]
@craigcosmo If you omit `onRequestClose ` so click-out won't work neither. Here is my solutions: 

```jsx
<ReactModal
  onRequestClose={(event) => {
    // Ignore react-modal esc-close handling 
    if (event.type === 'keydown' && event.keyCode === 27) return

    onRequestCloseHandler()
  }}
>
```

**Comment by craigcosmo** [comment]
@gevgeny yeah I noticed that 👍

**Comment by kuantayevs** [comment]
You can use `disableEscapeKeyDown = {true}`

**Comment by brunofin** [comment]
```javascript
<ReactModal shouldCloseOnEsc={false} {...props}></ReactModal>
```
