### ISSUE TITLE
Request to update gh_pages

### ISSUE THREAD

**Issue by Mr-Antivirus** [reactjs/react-modal#182]
Hello,

While trying to follow the example and also reference the gh_pages sites, I've realized that they are running two entirely different code bases. The gh_pages are severely out of date, so it was a little hard to figure out why copying the example code gave me a white background, while the gh_pages example gave me the typical black background.

Can someone update this for other newcomers?

**Comment by claydiffrient** [comment]
@Mr-Antivirus Thanks for your request.  I'm working on a new gh-pages site.  I'll see about getting my WIP pushed up so people can at least see some of the updated material soon.

**Comment by claydiffrient** [comment]
@Mr-Antivirus I spent a good portion of the day today working on this... hopefully this meets your needs.  It's incomplete, but should be much more up-to-date and have better examples.

https://reactcommunity.org/react-modal/
