### ISSUE TITLE
onRequestClose doesnt work 

### ISSUE THREAD

**Issue by Xurma2** [reactjs/react-modal#185]
### Summary:

When I am trying to close the changing state in Modal
It works if you click on the overlay
### Steps to reproduce:
1. Send props from component to `inOpen`
2. onRequestClose does not respond
### Expected behavior:

Called onRequestClose

**Comment by ClaudeTheCazur** [comment]
I'm also having this issue. Has anyone figured anything out?

**Comment by fenos** [comment]
Hello, any idea on this?

**Comment by claydiffrient** [comment]
I haven't been able to reproduce this behavior.  Is there anything more specific that you can provide that would help me reproduce it?

**Comment by diasbruno** [comment]
I'm closing this issue for clean up. Please, reopen if it still a problem in 1.6.5+.
