### ISSUE TITLE
Modal has overlay but doesnt appear in project, although it previously did

### ISSUE THREAD

**Issue by ChristopherVH** [reactjs/react-modal#190]
### Summary:
I hadn't worked on a project for about two months then when returning and altering the text of one modal and clearing and re-installing the most recent versions of my npm packages the modals would not show up at all.

### Steps to reproduce:

 1. Resintall npm pakages because getting following error 
```
[ERROR in ./frontend/nimbusplaylist.jsx
Module not found: Error: Cannot resolve module 'react-modal' in /Users/chrisvh/Documents/Capstone/frontend
 @ ./frontend/nimbusplaylist.jsx 3:12-34

ERROR in ./frontend/components/NewPlaylistModal.jsx
Module not found: Error: Cannot resolve module 'react-modal' in /Users/chrisvh/Documents/Capstone/frontend/components
 @ ./frontend/components/NewPlaylistModal.jsx 3:12-34

ERROR in ./frontend/components/PlaylistModal.jsx
Module not found: Error: Cannot resolve module 'react-modal' in /Users/chrisvh/Documents/Capstone/frontend/components
 @ ./frontend/components/PlaylistModal.jsx 5:12-34

ERROR in ./frontend/components/Like.jsx
Module not found: Error: Cannot resolve module 'react-modal' in /Users/chrisvh/Documents/Capstone/frontend/components
 @ ./frontend/components/Like.jsx 5:12-34
```
etc... 
2. Change text of modal

### Expected behavior:
Updated modal with behavior similar to what it was.
### Additional notes:
I'm a total noob and am not too sure how the npm installing may have affected the project or why I would have had to npm install on the project I cloned. Any advice would be great but and in depth explanation of why what I'm doing isn't working would be phenomenal.

**Comment by stephenkingsley** [comment]
@ChristopherVH I think u do not install react-modal, u can `npm i --save react-modal`

**Comment by diasbruno** [comment]
@stephenkingsley seems to be the case.

@ChristopherVH after the npm command it worked?

**Comment by ChristopherVH** [comment]
Totally right, all fixed now!
