### ISSUE TITLE
how to use modal with redux?

### ISSUE THREAD

**Issue by istok20** [reactjs/react-modal#204]
may someone give any example on how to use react-modal with redux in a proper way?

**Comment by suciuvlad** [comment]
@istok20 https://github.com/suciuvlad/redux-dialog

**Comment by dbertella** [comment]
I found this topic on SO that explain how to use modals in general with redux architecture, it may help

**Comment by diasbruno** [comment]
I'm closing this issue for clean up. Thanks for sharing those links. 
Hope we can publish this on docs.
