### ISSUE TITLE
Modal Pop Up

### ISSUE THREAD

**Issue by Kanchan-Sharma** [reactjs/react-modal#206]
I am creating a website using ASP.NET and it consists a master page, I have a login link on this master page so that it is available for all the content pages. Now I want the login page to be opened as a modal popup, so I wrote the code for modal popup in login page's aspx file. But I don't know how to access that modal popup placed on login content page from that login link that is present on master page so that the modal can be open at any page whenever i click on the login link??
Can anyone help me?
I have attached the screen shots of master page and login page and highlighted the concerned parts.
Thank you

![login](https://cloud.githubusercontent.com/assets/19486051/17401156/ad1e3346-5a69-11e6-9d56-335f49eef8e9.png)
![master](https://cloud.githubusercontent.com/assets/19486051/17401157/ad58eb58-5a69-11e6-9a4c-e8a995b49f39.png)

**Comment by vincenzo-antolini-os** [comment]
I think you should change lib. This specific modal lib is not the "correct" one.

**Comment by claydiffrient** [comment]
Closing as this appears to be unrelated to react-modal at all.
