### ISSUE TITLE
I can't navigate trough form elements using tab button

### ISSUE THREAD

**Issue by jurgob** [reactjs/react-modal#211]
### Steps to reproduce:
1. add some form elements inside a popup
2. try to navigate with tab button
### Expected behavior:

focus should move trought the form elements

**Comment by evanhobbs** [comment]
I'm having the same issue as well. Does anyone know of a workaround in the meantime?

**Comment by claydiffrient** [comment]
I can't reproduce what you are describing.  I used the example implementation at https://reactcommunity.org/react-modal/ and the following was my experience with no issues.

https://cl.ly/1P0f1I1Y2Y1t

Can you provide a sample implementation of this not working properly?

**Comment by evanhobbs** [comment]
It's part of an unreleased feature for an app I'm working on so it might be tricky. We have a form that we show in the page and also in a modal. When it's in a modal for some reason the tabs stop working. I'll see if I can come up with a reproducible example...

**Comment by nickb1080** [comment]
I'm seeing the same issue as well. Tracing it through, it comes at https://github.com/reactjs/react-modal/blob/master/lib/components/ModalPortal.js#L128 and then into the `scopeTab` and `tabbable` helpers. I'm unclear on the need for this special tab handling -- can anyone elaborate as to what this is trying to solve?

**Comment by nickb1080** [comment]
I've identified the issue I'm having, it is not solved by https://github.com/reactjs/react-modal/pull/216

In short, there is a check to see if an element is "tabbable", which includes various other checks, including "visible". This visible check traverses up the DOM looking for elements with `display: none` OR -- crucially -- offsetHeight of 0 or offsetWidth of 0. These values do not mean the children are not visible! My project has various wrapper nodes that seem to be `<span>` with offset width and height of zero. This code should instead use `getBoundingClientRect()`

**Comment by conlanpatrek** [comment]
Opened a separate PR for this, as the `getBoundingClientRect` method was still failing for us. There is a potential workaround in the PR #271

**Comment by mandazi** [comment]
I am also having the same issue with this.

**Comment by diasbruno** [comment]
@mandazi which version are you using? I've update the `tabbable` function recently.

See [0f2bf9e9](https://github.com/reactjs/react-modal/commit/0f2bf9e92e09fe79e0b28c9f02c1ef4b4c4a19b9).

**Comment by mandazi** [comment]
@diasbruno 2.4.1

**Comment by conlanpatrek** [comment]
@diasbruno it looks like that update is for `scopeTab`, not `tabbable`. It's been a minute since I've looked at this, but if I recall correctly we're incorrectly identifying which elements are `hidden` with this check here: https://github.com/reactjs/react-modal/blob/master/src/helpers/tabbable.js#L17

The problem is that offsetWidth and offsetHeight aren't enough to determine if the contents of a node are visible. You also have to consider the `overflow` mode.

#271 was meant to resolve this, though that was a year ago and might need updated... Would it be helpful if I rebased that commit or provided a demonstration of the issue?

**Comment by mandazi** [comment]
@diasbruno I just tried the latest version of react-modal (3.1.2) and it doesn't work.

@conlanpatrek thanks! It sounds like that might be the fix.

**Comment by diasbruno** [comment]
@mandazi @conlanpatrek Sounds like a plan. Once it is rebased, we can merge it. (#271)

**Comment by mandazi** [comment]
@conlanpatrek the PR #271 fixes the tab issue. Just verified!

**Comment by conlanpatrek** [comment]
#271 has been rebased and updated to meet style standards.

**Comment by diasbruno** [comment]
Released `v3.1.3`.

**Comment by paulewetzel** [comment]
I had the same issue today (2021), so I created a quick work around. All you need to do is create a ref an assign it to the container element that surrounds the focusable elements that you wish to tab through. For example:


```
import React, { useRef} from 'react';
import ModalTabManager from '../../yourpath';

const YourComponent = (props) =>{
const containerRef = useRef();
return (
<ModalTabManager containerRef={containerRef}>
    <form ref={containerRef}>
        <input type="text" />
        <input type="text" />
        <input type="text" />
        <input type="text" />
    </form>
 </ModalTabManager> 
);
}
```

Cut and paste the ModalTabManager component below into your project, do what I did in the example above, and that should fix your tabbing issues.
```
import React, { useState, useEffect } from 'react';

const ModalTabManager = ({ containerRef, children }) => {
    const [configuredTabIndexes, setConfiguredTabIndexes] = useState(false);

    const focusableElements = () => {
        return [...containerRef?.current?.querySelectorAll(
            'a, button, input, textarea, select, details, [tabindex]:not([tabindex="-1"]):not([type="hidden"]):not([disabled])'
        )];
    }

    const isTabbable = (element) =>{
        if(element.getAttribute('tabindex')){
            return true;
        }
        return false;
    }

    const findElementByTabIndex = (tabIndex) => {
        return containerRef?.current?.querySelector(`[tabindex="${tabIndex}"]`);
    }
    
    const moveFocusToTabIndex = (tabIndex) => {
        findElementByTabIndex(tabIndex)?.focus();
    }

    const handleFocusEvent = (event) => {
        if(!isTabbable(event.target)){
            return;
        }

        const tabIndex = parseInt(event.target.getAttribute('tabindex'));

        if(event.shiftKey && event.key === 'Tab'){
            moveFocusToTabIndex(tabIndex - 1);
        }else if(event.key === 'Tab'){ //should probably make sure there is no other modifier key pressed.
            moveFocusToTabIndex(tabIndex + 1);
        }
    }

    useEffect(() => {
        if(!configuredTabIndexes && containerRef.current){
            setConfiguredTabIndexes(true);
            focusableElements().forEach((el, index) => el.setAttribute('tabindex', index + 1));
            containerRef?.current?.addEventListener('keydown', event => {
                handleFocusEvent(event);
            });
        }
    });

    return children;
}

export default ModalTabManager;
```

**Comment by thenick775** [comment]
Bumping, still having this issue on 3.16.1

**Comment by PeterHagane** [comment]
Stumbled across this same issue in a RadixUI dropdown. Thanks for the easy fix, saved me a bit of time and works in typescript with added lazy any-typing. @paulewetzel
