### ISSUE TITLE
Add `onAfterClose` property

### ISSUE THREAD

**Issue by halt-hammerzeit** [reactjs/react-modal#214]
A proper modal window resets itself upon closing.
It can be reset immediately when `isOpen` is set to `false` but that introduces glitches due to resetting and repainting the modal window before closing animation is played.
An `onAfterClose` handler run in `componentWillUnmount` would resolve this issue.
I can make a PR if you are willing to accept this feature.

**Comment by brentluna** [comment]
This would be awesome.

**Comment by megapctr** [comment]
While this prop would be very helpful, my case was simple enough to implement it manually:
```
    onRequestClose = () => {
        this.props.closeModal()
        setTimeout(
            this.props.resetModal,
            this.props.closeTimeoutMS
        )
    }
```

**Comment by halt-hammerzeit** [comment]
@megapctr oh, yeah, didn't think about this kind of workaround, that will do (though that's just a workaround and doesn't fix the issue)

**Comment by halt-hammerzeit** [comment]
@megapctr And also this workaround won't work for programmatically closing the modal since it will either have to call `this.refs.modal.close()` (which is non-React way) or have to be upgraded to duplicate [`ModalPortal`](https://github.com/reactjs/react-modal/blob/master/lib/components/ModalPortal.js#L54) functionality:

```js
  componentWillReceiveProps: function(newProps) {
    // Focus only needs to be set once when the modal is being opened
    if (this.props.isOpen && !newProps.isOpen) {
        setTimeout(
            this.props.resetModal,
            this.props.closeTimeoutMS
        )
    }
  },
```

**Comment by halt-hammerzeit** [comment]
I found another way: simply componentWillUnmount() in the modal contents component
