### ISSUE TITLE
Open two modals. Hit ESC then hit ECS but nothing happens 

### ISSUE THREAD

**Issue by cristian-sima** [reactjs/react-modal#218]
I am using this great idea http://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680 in order to display modals.

In order to display them, I have this code:

``` jsx
const ModalRoot = ({ list } : ModalRootPropTypes) : any => {

  if (list.size === 0) {
    return null;
  }

  return (
    <div>
      {
        list.map(({ type, props }, index) => {
          const Component = getComponent(type);

          return (
            <Component key={index} {...props} />
          );
        })
      }
    </div>
  );
};

```

The `getComponent` is like this: 

``` jsx
const DeleteArticle = (
 <Modal>
...
</Modal>
);

const MODAL_DELETE_ARTICLE = "MODAL_DELETE_ARTICLE";

const getComponent = (type : ModalActionType) : any => {
  switch (type) {

  case MODAL_DELETE_ARTICLE:
    return DeleteArticle;
....
```

So, essentially, for 2 modals, these pieces of code generates this view:

![image](https://cloud.githubusercontent.com/assets/12199042/18208409/10b745de-7138-11e6-8296-cdba27e791b7.png)

The HTML code is:

![image](https://cloud.githubusercontent.com/assets/12199042/18208562/971e638c-7138-11e6-9da1-9a1b8a8b24c9.png)

Which is very good, correct and right. But:

Now, when I hit `ESC`, the second modal hides (which is good). Then, if I press again ESC, **nothing happens**. That's because the `Modal 1` is not logger focused. 

If I click on it and hit `ECS` it is closed.

My question is:

Can I somehow focus the next modal when one is closed? (Focus `Modal 1` when `Modal 2` is closed)

**Comment by diasbruno** [comment]
This should be fixed since `v1.7.7`.

Please, feel free to reopen this issue if needed.
Thanks.
