### ISSUE TITLE
Demo is not working 

### ISSUE THREAD

**Issue by carloshpds** [reactjs/react-modal#225]
### Summary:
Demo is not working 

### Steps to reproduce:

 1.https://reactcommunity.org/react-modal/

### Expected behavior:
See a real basic example of react-modal

**Comment by claydiffrient** [comment]
@carloshpds Thanks for the issue.  I think I've fixed it but with some caching going on, it might not work until the cache is refreshed.

**Comment by claydiffrient** [comment]
Okay I confirmed that it's working now.  This was closed by 8895edfbbc2a3a0442e45946b934505a1f013ee8 plus a few more parent commits.
