### ISSUE TITLE
draggable feature

### ISSUE THREAD

**Issue by parlop** [reactjs/react-modal#232]
will you support draggable feature in the near future, trying to use react-draggable with this component but dont get any joy, thanks

**Comment by diasbruno** [comment]
@parlop did you found a way to solve this issue with `react-draggable`? this is seems a nice combination.

**Comment by parlop** [comment]
yes, I solved this issue with the library react-draggable(https://github.com/mzabriskie/react-draggable), it works like a charm, thanks!

**Comment by diasbruno** [comment]
Awesome! Thanks!

**Comment by uraniun** [comment]
@parlop can you show your solution? I have the same problem.

**Comment by eldamir** [comment]
@parlop Any detail you can share to help the community? How did you make it work? We are having trouble with the Portal -> #45

**Comment by eldamir** [comment]
@diasbruno Maybe you have some insights? Otherwise, maybe we should reopen the issue?

**Comment by diasbruno** [comment]
@eldamir I was thinking about it and I don't thing this is what a modal should do. I would recommend some kind of 'window', not a modal.

**Comment by parlop** [comment]
actually I made it work with a hack, you have to put draggable before a div content:
<Modal><Draggable><div className="whatever">content</div></Draggable></Modal>
It works for me and give it a high z-index
here's the code i used
```

 return (
      <div>
        <button style={buttonstyle} onClick={this.openModal}><i className="fa fa-search"></i>Search Json</button>
        <Modal
          contentLabel="????"
          className="Modal__Bootstrap modal-dialog"
          closeTimeoutMS={150}
          isOpen={this.state.modalIsOpen}
          onRequestClose={this.handleModalCloseRequest}
          shouldCloseOnOverlayClick={false}
          style={customStyles}
        > <Draggable>
          <div className="modal-content">
            <div className="modal-header">
              <button type="button" className="close" onClick={this.handleModalCloseRequest}>
                <span aria-hidden="true">&times;</span>
                <span className="sr-only">Close</span>
              </button>
              <h4 className="modal-title">Search Json </h4>
            </div>
            <div className="modal-body">
              <SearchModalComp closeMenu={this.closeMenu} {...this.props}/>
            </div>            
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" onClick={this.handleSaveClicked}>Select</button>
              <button type="button" className="btn btn-default" onClick={this.handleModalCloseRequest}>Close</button>
            </div>
          </div></Draggable>
        </Modal>

      </div>
    );
```

**Comment by eldamir** [comment]
Thanks @parlop , I'll give it a try

**Comment by austingayler** [comment]
Having trouble getting this working with react-draggable. It just drags the form inside:
http://i.imgur.com/iCRjZL5.png


            <Col sm={3}>
              <Modal>
                <Draggable>
                  <div>
                    <Modal.Body>
                      <ModalContentStuff {...this.props} closeAction={this.close.bind(this)} />
                    </Modal.Body>
                  </div>
                </Draggable>
              </Modal>
            </Col>

ModalContentStuff contains `<Form><FormGroup>...`


Any ideas?

**Comment by parlop** [comment]
what framework r u using?, (<col sm={3}>)
instead of this 
'  <Col sm={3}>
   <Draggable>
   <div>
   <Modal.Body> ......'
I'd put
'<Draggable>
 <col sm={3}>
  <Modal.Body>.......'

**Comment by eldamir** [comment]
@parlop @austingayler  for me, this just resulted in the modal becoming an empty div, for some reason. The Draggable seems to ignore its children for some reason...

**Comment by eldamir** [comment]
For your reference, I ended up abandoning react-draggable and just using good ol' JQuery

```typescript
export class Dialog extends React.Component<DialogProps, any> {
    render() {
        [...]
        return (
            <Modal isOpen={props.isOpen}
                   contentLabel={props.contentLabel}
                   shouldCloseOnOverlayClick={props.shouldCloseOnOverlayClick}
                   className={modalCSS}
                   overlayClassName={overlayCSS}
                   onAfterOpen={props.onAfterOpen}>
                <div ref={(div) => {
                    const target = $(div).parent();
                    target.draggable({handle: `.${dragHandle}`});
                    this.props.forcedWidth && target.width(this.props.forcedWidth);
                }}>
                    <ModalHeader title={props.contentLabel}
                                 onTickerClick={props.onClose}
                                 className={dragHandle} />
                    <ModalBody>
                        {props.children}
                    </ModalBody>
                </div>
            </Modal>
        );
    }
}
```

The key takeaway here is using `ref` to grab the DOM element and applying draggable. There was an issue with the width becoming 100% for some reason, but I've just managed it with props and a subsequent call to `JQuery.width()`

**Comment by MidnightJava** [comment]
What do you set dragHandle to? I guess I don't understand the parent context here, and I get a runtime error because that variable is undefined.

**Comment by eldamir** [comment]
My `dragHandle` varialbe is just the classname of the `<ModalHeader />`, so that I can drag the dialog by clicking down on the header bar

**Comment by davvidbaker** [comment]
[Here's a working example of how you do this](https://codesandbox.io/s/30j8xpy181), using `react-modal` and `react-draggable`. 

The gist of what's going on is, you create your own "content" div and basically ignore/hide the one provided by `react-modal`.

**Comment by CMCDragonkai** [comment]
@davvidbaker Is there a way to use yours while allowing one to interact with the background UI? I'm using a style override like:

```
        style={{
          overlay: {
            position: 'fixed',
            zIndex: '99',
            height: '400px',
            width: '400px',
            padding: 'initial',
            margin: 'auto',
            top: '0',
            left: '0',
            right: '0',
            bottom: '0',
            border: 'none',
            background: 'transparent',
            borderRadius: '0'
          },
          content: {
            position: 'static',
            height: '100%',
            width: '100%',
            padding: '10px',
            top: 'auto',
            left: 'auto',
            right: 'auto',
            bottom: 'auto',
            background: '#fff',
            outline: 'none',
            overflow: 'auto'
          }
        }}
```

In order to start the modal and its overlay in the middle without covering up the background UI.

**Comment by davvidbaker** [comment]
I think what you want to do will work if you add `pointerEvents: 'none'` to the overlay style object. [Working example](https://codesandbox.io/s/cranky-glitter-d80qv).

**Comment by coderaudi** [comment]
> @parlop @austingayler for me, this just resulted in the modal becoming an empty div, for some reason. The Draggable seems to ignore its children for some reason...

share the detailed example for reactjs model dragging
