### ISSUE TITLE
Issue with Redux and Immutable js

### ISSUE THREAD

**Issue by devnidhinraj** [reactjs/react-modal#234]
### Summary:

I get the following message after i implemented immutable types (immutable.js) for my state.
Warning: setState(...): You passed an undefined or null state object; instead, use forceUpdate().
### Steps to reproduce:

The following is how i trigger the action.

```
`let EditorToolBar = ({
    dispatch
}) => {
    let toolbarBtnStyle = className('btn btn-primary toolbar-button', styles.editorToolBarBnt);
    return (
        <div className="container" >
        <div className= "row">
            <div className="col-md-12">
                <div>
                    <button type="button" className={ toolbarBtnStyle } id="toolbar-text"
                        onClick={
                                ()=> {  
                                dispatch(setVisiblityFilterForTextEditor('SHOW_TEXT_EDITOR'))
                            }
                            }>
                        <span className="glyphicon glyphicon-font"></span>
                    </button>       
                </div>
            </div>
        </div>

    </div>
    );
} //class ends
```

EditorToolBar = connect()(EditorToolBar);
export default EditorToolBar;`

The dialog component. [react-modal - https://github.com/reactjs/react-modal) ]
`const EditorTextDialog = React.createClass({

```
getInitialState: function() {
    return {
        modalIsOpen: false,
    };
},

openModal: function() {
    this.setState({
        modalIsOpen: true,
    });
},

afterOpenModal: function() {
    // references are now sync'd and can be accessed.
    //  this.refs.subtitle.style.color = '#f00';
},

closeModal: function() {
    this.setState({
        modalIsOpen: false
    });
},


visibilityController: function() {
    if (this.store.getState().get('textEditorVisiblityFilter') === 'SHOW_TEXT_EDITOR') {
        this.openModal();
    } else {
        this.closeModal();
    }

},
componentDidMount: function() {

    this.store = this.context.store;
    this.store.subscribe(this.visibilityController);

},

handleModalCloseRequest: function() {
    this.closeModal();
},`
```
### Additional notes:Well the above code is a part of the component on which the React-Modal has been implemented. All was fine until i started using immutable js.

As anybody come across this issue ?

**Comment by tkh44** [comment]
This looks like you are not setting your state correctly in your constructor (es6) or getInitialState (es5).  If you call `setState` somewhere in your component you need to ensure you set one of those first.  Also, out of curiosity why are you not using react-redux's connect HoC?

**Comment by devnidhinraj** [comment]
@tkh44 I tried using connect. But no change.

http://stackoverflow.com/questions/39777405/having-issues-with-dispatch-method-after-implementing-immutable-js-for-state-tre

**Comment by mwq27** [comment]
It looks like this issue was solved in StackOverflow.  This could probably be closed now.

**Comment by diasbruno** [comment]
I'm closing this issue for clean up. Please, reopen this issue if necessary.
