### ISSUE TITLE
deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

### ISSUE THREAD

**Issue by mic159** [reactjs/react-modal#238]
### Summary:

When installing `react-modal` with NPM, i get this warning:

```
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
```
### Steps to reproduce:

Using NodeJS 6.x:  `npm install react-modal`
### Expected behavior:

I would expect no deprecated dependencies on the latest version.

I assume you want it for a pollyfill. I think there are smaller ones out there that are not deprecated, eg: https://www.npmjs.com/package/object-assign
### Additional notes:

Looks like `lodash.assign` inflates the number of dependencies quite a bit too, it would be good to remove!

```
├─┬ react-modal@1.4.0 
│ ├── element-class@0.2.2 
│ ├── exenv@1.2.0 
│ └─┬ lodash.assign@3.2.0 
│   ├─┬ lodash._baseassign@3.2.0 
│   │ └── lodash._basecopy@3.0.1 
│   ├─┬ lodash._createassigner@3.1.1 
│   │ ├── lodash._bindcallback@3.0.1 
│   │ ├── lodash._isiterateecall@3.0.9 
│   │ └── lodash.restparam@3.6.1 
│   └─┬ lodash.keys@3.1.2 
│     ├── lodash._getnative@3.9.1 
│     ├── lodash.isarguments@3.1.0 
│     └── lodash.isarray@3.0.4
```

**Comment by diasbruno** [comment]
@rfreitas can you look at this one?

**Comment by rfreitas** [comment]
yes, PR been added
