### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dwick** [reactjs/react-modal#241]
There are quite a few commits that haven't been published to npm going back to June: 9686635abe418ffd510dafefe4cd59c9e8a87217...c8106f2c9ee6fa251e2da2998ad1d26e2bee827e

Any chance you could cut a new version?

**Comment by dzek69** [comment]
you can attach npm to github instead of npm repo for single package by specifing that package as `githubauthor/packagename`

source: https://docs.npmjs.com/cli/install

**Comment by dwick** [comment]
sure, that's a workaround, but there are probably lots of people using this without recent bug fixes because the package hasn't been published in months

**Comment by claydiffrient** [comment]
@dwick @dzek69 Version 1.5.1 was just released.
