### ISSUE TITLE
Modal appears behind some react-bootstrap elements

### ISSUE THREAD

**Issue by Zensavona** [reactjs/react-modal#249]
### Summary:

![screenshot 2016-10-12 09 03 27](https://cloud.githubusercontent.com/assets/425801/19290324/d884b81c-905a-11e6-9dfd-8c632a83e9a1.png)

The modal appears to sit behind certain kinds of elements, the most obvious being input addons.

I'm not totally sure if this is an issue with `react-modal`, `react-bootstrap` or both, so I've created [a ticket on react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/issues/2277) also. If this is totally not your fault and I should take it up with someone else please let me know. My css-fu is very much lacking so forgive my ignorance in that area.
### Steps to reproduce:

I've made a basic repo as seen in the screenshot above.
1.  `git clone https://github.com/zensavona/bootstrap-modal-repro`
2.  `cd bootstrap-modal-repro`
3. `npm install && npm run start`
4. Take a look in your browser

Let me know if there's something else I can provide to help with this, it's a pretty nasty bug(?).

**Comment by claydiffrient** [comment]
@Zensavona Sorry for the delay on getting to this.  

It appears that you have some styles that are making those inputs show up with a higher z-index.

Specifically I was looking at `.input-group .form-control`.  It sets `z-index: 2` which brings it higher than the modal (that doesn't default to anything).

You can fix this specific case by sending in `style={{overlay: {zIndex: 3}}}` or any other z-index higher than 3.  When I tested it... I used 10.

As this is unrelated to the modal itself, I'm going to go ahead and close the issue.  Thanks!
