### ISSUE TITLE
Prevent background scrolling when modal is displayed

### ISSUE THREAD

**Issue by c0debreaker** [reactjs/react-modal#251]
I couldn't find the proper solution to prevent scrolling of the backdrop when modal is displayed. I found a few but it was confusing and long text too. How is it done?

**Comment by c0debreaker** [comment]
This css code worked very well for me.

```
.ReactModal__Body--open {
  overflow: hidden;
}
```

**Comment by chuanxie** [comment]
`overflow: hidden` doesn't work on Safari

**Comment by kaiomagalhaes** [comment]
I'm having this issue on IOS, even with the `overflow: hidden` it  scrolls. Any ideas?

**Comment by sarink** [comment]
This doesn't seem to be working at all?

**Comment by s-herbert** [comment]
> Safari ignores overflow on body, allowing you to touch-scroll it.

https://medium.com/react-camp/how-to-fight-the-body-scroll-2b00267b37ac

I am implementing my own modal but, came across this while searching for solutions, may help others!
