### ISSUE TITLE
[v1.5.2] Is it possible to use `Modal.setAppElement` with SSR ?

### ISSUE THREAD

**Issue by DimaRGB** [reactjs/react-modal#260]
When i try to use `Modal.setAppElement` just before declare some ContainerComponent:

```
ReactModal.setAppElement('#app');
class ContainerComponent extends React.Component {
  render() {
    return (
      <Modal {...} />
    );
  }
}
```

i have next error:

```
react-modal/lib/helpers/ariaAppHider.js:5
 var el = document.querySelectorAll(element);
              ^

 ReferenceError: document is not defined
```

**Comment by diasbruno** [comment]
Hi @DimaRGB, have you tried with `v1.6.5+`? Not sure if we have a fix for this.

**Comment by DimaRGB** [comment]
Hello @diasbruno, actually i can't, it's very old issue. I think it's more related to version 1.5. So, since released 1.6 and i can't test again, we can close issue, i believe.

**Comment by diasbruno** [comment]
Ok, @DimaRGB. Thank you.

**Comment by NathanielHill** [comment]
For reference, since it was a pain for me, if you are doing SSR, use the following code to prevent errors server-side:

    if (typeof(window) !== 'undefined') {
        ReactModal.setAppElement('body')
    }

You could put this in `componentDidMount()` anywhere you use a modal or I put it in a custom modal component so it's nice and DRY.

  #580
