### ISSUE TITLE
How to set onClick event with modal?

### ISSUE THREAD

**Issue by bsdo64** [reactjs/react-modal#261]
### Summary:
I need to stopPropagation onClick modal on dropdown menu.
But I set Modal component with onClick event handler, event didn't fire. So behind dropdown menu is closed.
How to set onClick handler?

### Steps to reproduce:

 1. Set modal with onClick
```js
stopEvent(e) {
  e.stopPropagation();
}

<Modal
  onClick={this.stopEvent}  // Nothing happend
  ...
/>
```

### Expected behavior:
Behind menu is closed.

**Comment by mwq27** [comment]
Do you have a repo with this still happening?

**Comment by diasbruno** [comment]
`onClick` is not on the list o properties of `Modal`. Maybe we can forward the click event, but I don't know if it would be helpful.

One way, I guess, is to wrap your content into a `div` and place your mouse events on this div.

```js
<modal ...>
  <div onClick={...}>
    {...}
  </div>
</modal>
```

**Comment by diasbruno** [comment]
I'm closing this for clean up. Please, feel free to reopen this issue. Thanks.

**Comment by bsdo64** [comment]
My components have menus, tooltips, popovers and so on.. but when user close modal, I want to restore preserved states by preventing the click event from bubbling up from the modal.

https://github.com/Fauntleroy/react-simple-dropdown/issues/24

Here is my issue about case.

**Comment by diasbruno** [comment]
Relates to [Fauntleroy/react-simple-dropdown#24](https://github.com/Fauntleroy/react-simple-dropdown/issues/24).
