### ISSUE TITLE
portalModalClassName does not update after mount

### ISSUE THREAD

**Issue by aray12** [reactjs/react-modal#262]
### Summary:
ModalPortal does not update props after being mounted

### Steps to reproduce:

 1. Create a wrapper component that passes a `className` to `portalClassName`
 2. Change that `className` on button click
 3. Watch it not update

### Expected behavior:
I have significantly customized the css for my modals to make them appear and behave closer to bootstrap when on tablet or desktop. The problem is pass an `isOpen` class to ModalPortal in order to get the behavior. But on reviewing the code for ModalPortal it doesn't update the className for the div mounted at 

### Additional notes:
For anyone finding this later the work around is to simply apply whatever custom open styling you want to 

```css
body.ReactModal__Body--open .ReactModalPortal {
  // styling here...
}
```

**Comment by artf** [comment]
Same here.

I think moving `this.node.className = this.props.portalClassName;` from `componentDidMount` to `renderPortal` will fix the issue

**Comment by diasbruno** [comment]
@artf @aray12 I'm closing this issue for clean up. This should be fixed on the latest versions. 
Thanks for reporting.
