### ISSUE TITLE
Bootstrap demo does not work

### ISSUE THREAD

**Issue by CodeJjang** [reactjs/react-modal#263]
Hi,

It seems that [the server of the bootstrap demo](https://reactcommunity.org/react-modal/bootstrap/) is not up.

Can the author please lift it up again? Or is it on purpose?

**Comment by robinspark** [comment]
GET https://reactcommunity.org/react-modal/__build__/bootstrap.js 404 (Not Found)

**Comment by claydiffrient** [comment]
I don't see much reason for the bootstrap styles specific example.  It will be removed from the README.md.
