### ISSUE TITLE
Uncaught Error: react-modal: You must set an element with `Modal.setAppElement(el)`

### ISSUE THREAD

**Issue by petrdamborsky** [reactjs/react-modal#267]
### Summary:
Just wanted to try this modal solution. Docs mention the setAppElement as an optional thing to do, but I am getting this error in console when I do not call it. I Have tried to call the Modal.setAppElement from the component itself and then also from the root app component. No place does help to get rid of this error. 

### Steps to reproduce:

 1. Create new component using Modal inside
 2. Use the component in app
 3. Get console error

### Expected behavior:
I would expect not to be forced into setAppElement.

**Comment by diasbruno** [comment]
@petrdamborsky yeah, you can't call `setAppElement` within the modal itself. It should be appended to `document.body` as default, if I'm correct. I'll check it.

**Comment by diasbruno** [comment]
@petrdamborsky since this issue is a bit old (sorry), did you found a way to make it work?

**Comment by petrdamborsky** [comment]
@diasbruno Hey, sorry I missed the notification. I have actually moved on and found different package with modals.

Oh and I was trying the setAppElement from the root component, not the modal itself.. still didn't work. Not sure what was wrong, but I won't be able to get back to that state now :)

**Comment by diasbruno** [comment]
that's ok. 
thanks, @petrdamborsky.
