### ISSUE TITLE
Unexpected token: punc ()) on builds with 1.6.0

### ISSUE THREAD

**Issue by pluddy** [reactjs/react-modal#268]
### Summary:
Getting build failures when pointing at `1.6.0` due to `SyntaxError: Unexpected token: punc ()) [.../react-modal/lib/components/Modal.js:56,0]`

**Comment by ssilve1989** [comment]
Also seeing this

**Comment by claydiffrient** [comment]
@pluddy / @ssilve1989 Please try using #269 and see if that works for you.

**Comment by pluddy** [comment]
LGTM

**Comment by foxhound87** [comment]
Same here
