### ISSUE TITLE
~100mb package with 1.6.2 version

### ISSUE THREAD

**Issue by DimitryDushkin** [reactjs/react-modal#275]
### Summary:
Prior 1.6.2 react-modal size in `node_modules` was 423 Kb, **now it is ~100Mb**. For some reason it installs every devDependency to `old/node_modules` even with `npm i --production`.

It broke CI checking for absence of ssl keys (there are now in `/node_modules/react-modal/old/node_modules/webpack-dev-server/ssl/server.key` in production build).

### Steps to reproduce:

 1. `npm init`
 2. `npm i --save --production react-modal@1.6.2`
 3. `du -sh node_modules` = 100Mb

### Expected behavior:
`du -sh node_modules` = 430Kb

### Additional notes:
`npm 3.10.8`
react-modal 1.6.1 is fine.

**Comment by claydiffrient** [comment]
@DimitryDushkin Thanks for catching that!  I didn't have a clean directory when publishing apparently.  v.1.6.3 has the reduced file size again.
