### ISSUE TITLE
Convert library code to ES2015+

### ISSUE THREAD

**Issue by claydiffrient** [reactjs/react-modal#286]
This would provide a much better developer experience going forward.

**Comment by abouthiroppy** [comment]
@claydiffrient Already progressing?

**Comment by claydiffrient** [comment]
@abouthiroppy I haven't started on the library code at this point.  I'm working on getting the tests completed first as that *should* be easier.

**Comment by abouthiroppy** [comment]
I see. Thanks. I would like to cooperate if you like 🙃

**Comment by claydiffrient** [comment]
@abouthiroppy I ended up accidentally getting things converted over as part of another issue I was working on. If you'd like to review 0b4ab7d5a7ac42f804bb69678a620920cf309607 that'd be awesome though :)  It's PR #293

**Comment by abouthiroppy** [comment]
@claydiffrient Thank you for telling me :) Great work!!!
