### ISSUE TITLE
Remove Modal.setAppElement?

### ISSUE THREAD

**Issue by claydiffrient** [reactjs/react-modal#287]
I'm thinking perhaps we should get rid of `Modal.setAppElement`.  It's slightly odd and trips many people up when trying to use the library.  There's also been the odd `appElement` prop that has been around.

I think we should remove the `appElement` prop replacing it with a `getAppElement` function prop similar to what was done for the `parentElement` stuff in 1.6.x.  I'm almost certain this would help with things like #174 is having issues with.

Thoughts?

**Comment by diasbruno** [comment]
Maybe, an optional attribute if someone needs to set a different element for a particular modal. 
Default it to `document.body` would be better (common case).
