### ISSUE TITLE
How to make it so that the modal appears with padding above, and not without padding?

### ISSUE THREAD

**Issue by jr69** [reactjs/react-modal#288]
### Summary:
I have a modal and its size exceeds the screen. I also have some padding around all edges, so that it doesn't take up the whole screen.

### Steps to reproduce:

 1. Create modal with large height that exceeds screen
 2. Give it some padding at the top, like 64px
 3. Put overflow in the container (where the white background overlay is) to 'scroll'
 4. Click on a button to have it pop up

### Expected behavior:
The modal should appear with padding at the top, i.e. the scrollbar should view it from the start, not in the middle.

The thing is, the very top of the modal appears at the very top of the page, which isn't what I want. The very top of the modal needs to be 64px below the top of the browser's view, i.e. the browser toolbar.

In this case, if you scroll up, thats essentially what I want.

![problem](https://cloud.githubusercontent.com/assets/9291238/21513908/39c72742-cd12-11e6-97f4-1fe82095db92.png)

**Comment by claydiffrient** [comment]
@jr69 Would something like this: http://codepen.io/claydiffrient/pen/jyNBXG work for you?

I think it's a matter of padding not working because the modal contents default to being `position:absolute`  Give `top: 64px` and lets see what happens.

**Comment by indiesquidge** [comment]
@claydiffrient, I've been having the same issue described here and I think the problem may be more related to setting an overflow to achieve something of a [modal scroll](https://github.com/reactjs/react-modal/issues/283) when the window is too small.

I forked your CodePen and added a single line, `overflowY: 'auto'`, to the overlay style object, which seems to resurface the scroll issue: https://codepen.io/indiesquidge/pen/bRLXoB
