### ISSUE TITLE
closeTimeoutMS respected only when onRequestClose is implemented

### ISSUE THREAD

**Issue by pstoica** [reactjs/react-modal#30]
Requiring user interaction in a modal wouldn't allow for animations because of this:

```
  close: function() {
    if (!this.ownerHandlesClose())
      return;
    if (this.props.closeTimeoutMS > 0)
      this.closeWithTimeout();
    else
      this.closeWithoutTimeout();
  },
```

For now I'm working around this by defaulting onRequestClose to a noop.

**Comment by ccqgithub** [comment]
👍

**Comment by diasbruno** [comment]
1.6.5+ should have a fix for this case. I'm closing this issue because it got old. 
If any problem happens, just reopen this issue.
