### ISSUE TITLE
onRequestClose doesn't work on iOS

### ISSUE THREAD

**Issue by littlee** [reactjs/react-modal#301]
### Summary:
I pass `onRequestClose` prop to `<Modal/>`, but when I click the overlay, the modal doesn't close (iPhone 5s latest iOS), but it does on desktop browser.

**Comment by claydiffrient** [comment]
I don't have an iOS device to debug this on.  This would be a great PR opportunity if anyone is interested.

**Comment by yatharthk** [comment]
@claydiffrient I tried to debug this one and it seems like some react issue. The `onMouseDown` and `onMouseUp` events don't work with `<div>` element. However it seems to work fine with more semantic elements like `<button>`. Let me know if you have a workaround for this. Would love to pick this up for a PR.

**Comment by yatharthk** [comment]
@claydiffrient Seems to be somewhat related to [#1169] (https://github.com/facebook/react/issues/1169)

**Comment by monsieurnebo** [comment]
iOS doesn't detect an element as clickable without the `cursor: pointer;` CSS property.

Applying `cursor: pointer;` to the overlay is a workaround, but it would be nice to get a real fix.

See https://github.com/facebook/react/issues/1169

**Comment by diasbruno** [comment]
A fix has been merged. I'm closing this issue for clean up. 
If the fix does not solve this issue, please reopen this issue.
