### ISSUE TITLE
Ability to disable/delay automatic focus

### ISSUE THREAD

**Issue by jordanmack** [reactjs/react-modal#306]
### Summary:
It would be beneficial to have another prop on <Modal> to disable or delay the automatic focus.

Specifically on iOS Safari, the page is automatically scrolled to the focused object. There does not appear to be any way to suppress this functionality, and workarounds are quirky. If movement transitions are applied to the modal, the screen scrolls to undesired locations. Being able to disable or set a specific delay on the focus would provide an easy workaround.

**Comment by davidfateh** [comment]
I second this. I'm also experiencing a problem while calling the modal from a link inside a table using React Virtualized. It seems that when virtualizing the window scroll, the active element (when firing a modal from within the table) becomes the whole grid and that also scrolls the page top to match the top of the grid. I will try to set up a working example of what I mean.

I was poking around in the react-modal source and it looks like we might be able to easily disable this feature like @jordanmack suggested. I think I will take a crack at it.

**Comment by davidfateh** [comment]
I was able to get a working example of what I was talking about with react-virtualized scroll.

https://codesandbox.io/s/El6mDVR8g

Now I understand this is might be an edge case but I think it would still be useful to allow the user to disable the focus manager on an individual basis to allow for more custom control in certain scenarios.

**Comment by imadha** [comment]
Hi there, I'm an FE infra engineer at @SlackHQ, and we've definitely run into this problem! We use `react-modal` to render popovers and tooltips, and unfortunately, it takes focus away from our main text input.

I submitted a PR #490 for this and it seems like an easy solution, just adds a prop `shouldFocusAfterRender` that defaults to `true`. 

Appreciate the hard work, and any feedback.  🙏
