### ISSUE TITLE
Clicking on overlay does not close modal on iOS touch devices

### ISSUE THREAD

**Issue by jordanmack** [reactjs/react-modal#307]
### Summary:
When shouldCloseOnOverlayClick is set to true, clicking the overlay on iOS does not close the modal.

### Steps to reproduce:
 1. Create a modal with shouldCloseOnOverlayClick={true}
 2. Verify that clicking the overlay closes the modal on a desktop browser.
 3. Observe that clicking the overlay does not close the modal on an iOS touch device.

### Expected behavior:
The modal should display the same functionality as the desktop.

### Additional notes:
This may also affect Android and Windows based touch devices, but is untested.

**Comment by diasbruno** [comment]
Hi @jordanmack, this issue is duplicated. You can follow in #301. 
Also, there is PR #304 which offers a solution for this.

**Comment by jordanmack** [comment]
Thanks for the heads up!

**Comment by diasbruno** [comment]
@jordanmack sorry, i mean, you can help testing PR #304, if you have some time to work on this. :)

**Comment by jordanmack** [comment]
@diasbruno I tried to test it out, but I'm having trouble getting it working in my project. It looks like tag v1.6.5 was the last one that worked properly for me.

**Comment by diasbruno** [comment]
@jordanmack awesome. thank you so much for this info.
