### ISSUE TITLE
Failing UglifyJS due to ES6 in Modal.js

### ISSUE THREAD

**Issue by josh-advizr** [reactjs/react-modal#312]
### Summary:
Getting error:
`SyntaxError: Unexpected token: punc ()) [./~/react-modal/lib/components/Modal.js:56,0]`

In the method:
```
getDefaultProps: function () {
    return {
      isOpen: false,
      portalClassName: 'ReactModalPortal',
      ariaHideApp: true,
      closeTimeoutMS: 0,
      shouldCloseOnOverlayClick: true,
      parentSelector: () => document.body
    };
  },
```
### Steps to reproduce:

 1. Include react-modal node module
 2. run UglifyJS

### Expected behavior:
Doesn't die in UglifyJS

### Additional notes:
Second time this has crept in within the past month or two.

**Comment by josh-advizr** [comment]
Obviously, the simple fix here is to change the line
```
parentSelector: () => document.body
```
to
```
parentSelector: function() { return document.body; }
```

**Comment by claydiffrient** [comment]
What version are you running?

**Comment by claydiffrient** [comment]
In 1.6.5 (our latest release) that line doesn't look like what you have reported.

https://github.com/reactjs/react-modal/blob/3ada4fba8133db5750decb72cede1992c5d8a40a/lib/components/Modal.js#L56

**Comment by josh-advizr** [comment]
Deleting my node modules folder and running a fresh install seemed to fix the issue.  My package defn is `"^1.4.0"`
