### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by edmulraney** [reactjs/react-modal#331]
### Steps to reproduce:

 1. Go to http://reactcommunity.org/react-modal/

### Expected behavior:
See demos of react-modal.

**Comment by claydiffrient** [comment]
Looks like the reactcommunity.org domain expired.  I'm not quite sure who was in charge of that.  Presumably this is affecting all the repos under the reactjs organization. @gaearon do you know what's up?

**Comment by ppicazo** [comment]
Looking at: https://github.com/reactjs/reactjs.github.io/commit/a3518a3ca023b6da4952ec447a9e3180247b8344

Maybe @mjackson might be help with this issue?

**Comment by ppicazo** [comment]
Related: https://github.com/reactjs/reactjs.github.io/issues/15

**Comment by diasbruno** [comment]
It's back!
