### ISSUE TITLE
iOS Safari Click at overlay doesn't close a modal

### ISSUE THREAD

**Issue by hibikiledo** [reactjs/react-modal#333]
### Summary:
Safari on iOS 10.2, click at overlay doesn't close a modal

### Steps to reproduce:

 1. Go to example, https://reactcommunity.org/react-modal/examples/on_request_close.html
 2. Click at Trigger Modal button in the result tab
 3. Click at the overlay. (outside of modal but within the result tab area)

### Expected behavior:
The modal should be closed.

### Additional notes:
n/a

**Comment by diasbruno** [comment]
Hi @hibikiledo, please follow issue #256 for more info about the bug. Thanks.
