### ISSUE TITLE
Latest release doesn't work on UglifyJs

### ISSUE THREAD

**Issue by 3LOK** [reactjs/react-modal#336]
### Summary:
You've released a new version of react-modal a couple of hours ago.

As you can see [here](https://github.com/reactjs/react-modal/blob/v1.7.0/lib/components/Modal.js#L103]), you forgot a 'function' keyword for non ES6 class component, and UglifyJs doesn't like this a single bit... 

(see definition of removePortal with missing function compared to reset of the functions there).

### Steps to reproduce:

 1. Try to uglifyjs this project.

### Expected behavior:
For UglifyJs to succeed. It now doesn't.

### Additional notes:

Thanks!!!

**Comment by gengjiawen** [comment]
And [this](https://github.com/reactjs/react-modal/blob/v1.7.0/lib/components/ModalPortal.js#L80)  too.

**Comment by damtur** [comment]
Can you please fix this ASAP? This is breaking tones of our builds unfortunately. Can you provide ETA and let me know please? Thank you!
CC: @diasbruno @claydiffrient

**Comment by diasbruno** [comment]
Backporting problems.
It happens sometimes.  :)

**Comment by glitch100** [comment]
@diasbruno Do we have a high level ETA on this branch going out?

**Comment by bencrinkle** [comment]
having the same issue as we use react-bootstrap-table which has react-modal as a dependancy. Have had to manually add react-modal and hardcode the version to 1.6.5 to get the build to work.

**Comment by diasbruno** [comment]
`v1.7.1` was released.

**Comment by nancruz** [comment]
v1.7.1 fixed the problem

**Comment by claydiffrient** [comment]
Going ahead and closing this since 1.7.1 has been reported to have indeed fixed the problem.
