### ISSUE TITLE
how to show icon beyond the content

### ISSUE THREAD

**Issue by CXJoyce** [reactjs/react-modal#339]
### Summary:
I want to set a close icon beyond my content section, but I find this icon cannot show.  

![2 pic](https://cloud.githubusercontent.com/assets/20786910/23498729/ee1d1642-ff63-11e6-98e2-a9dc2dd806b6.jpg)

**Comment by claydiffrient** [comment]
@CXJoyce You should be able to accomplish this if you set a z-index on the icon higher than what the modal overlay sets.

**Comment by tomasztomys** [comment]
@claydiffrient not working

**Comment by tomasztomys** [comment]
Ok, I have an answer. You have to pass overflow attribute to the nested div (not to the div which has ReactModal__Content class).

**Comment by CXJoyce** [comment]
@tomasztomys ,thanks ! It does work!
