### ISSUE TITLE
react-scripts build failure during UglifyJs due to functions declaration syntax

### ISSUE THREAD

**Issue by elfafa** [reactjs/react-modal#340]
### Summary:

`react-scripts build` failure on projects, due to 2 syntax "errors":
* `SyntaxError: Unexpected token punc «(», expected punc «:» [./~/react-modal/lib/components/Modal.js:103,0]`
* `SyntaxError: Unexpected token punc «(», expected punc «:» [./~/react-modal/lib/components/ModalPortal.js:80,0]`

### Steps to reproduce:

 1. Have a project using `react-modal` dependency
 2. Launch the production package command `npm run build`

### Expected behavior:

Just want the package command to be successful.

### Additional notes:

The reason of this error is simple, it's due to the used syntax for functions declaration:
* not working: `removePortal () {` and `open () {`
* working: `removePortal: function () {` and `open: function () {`

**Comment by AndrewGrachov** [comment]
confirming

**Comment by diasbruno** [comment]
Please, follow #336.

**Comment by elfafa** [comment]
thanks for the other issue link ;)
