### ISSUE TITLE
Syntax error prevents webpack compile

### ISSUE THREAD

**Issue by carrieomalley** [reactjs/react-modal#342]
### Summary:
There's an error in Modal.js in version 1.7.0 that prevents me from building my project

### Steps to reproduce:
React-modal is a dependancy of a dependancy for me so the steps to reproduce are
 1. Add react-modal as a dependancy of an ES6 project 
 2. Build with babel + webpack
 3. Build fails with the following:

```
ERROR in bundle.js from UglifyJs
Unexpected token punc «(», expected punc «:»
```

This error appears here:
node_modules/react-modal/lib/components/Modal.js line 103

 ``` javascript
removePortal () {
    ReactDOM.unmountComponentAtNode(this.node);
    var parent = getParentElement(this.props.parentSelector);
    parent.removeChild(this.node);
    elementClass(document.body).remove('ReactModal__Body--open');
  },
```
Which looks to me like it should be:
```javascript
removePortal: function () {
```

### Expected behavior:
Compiles without error

### Additional notes:
Happy to submit a PR if needed

**Comment by diasbruno** [comment]
Please, follow #336.

**Comment by carrieomalley** [comment]
Apols I didn't see that one :)

**Comment by diasbruno** [comment]
No problem! :)
