### ISSUE TITLE
Cannot run tests in PhantomJS

### ISSUE THREAD

**Issue by nancruz** [reactjs/react-modal#343]
### Summary:
When running tests using PhantomJS, I'm getting a SyntaxError. Please see the attached screenshots.

This started to happen after upgrading to version 1.7.0
### Additional notes:

![image](https://cloud.githubusercontent.com/assets/1250918/23511235/59085aee-ff54-11e6-81fd-f07637d078d6.png)

![image](https://cloud.githubusercontent.com/assets/1250918/23511266/7165892c-ff54-11e6-85f8-a55c64ee4242.png)

**Comment by diasbruno** [comment]
@nancruz hi, this seems related to #336.

**Comment by nancruz** [comment]
@diasbruno you are right. I'm going to close this issue
