### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by shonin** [reactjs/react-modal#350]
### Summary:
The documentation says near the bottom of the README: 
> By default the modal is closed when clicking outside of it (the overlay area). If you want to prevent this behavior you can pass the 'shouldCloseOnOverlayClick' prop with 'false' value.

However that's not exactly true. It appears to not close when clicking on the overlay unless `onRequestClose={this.handleCloseModal}` is passed into `<Modal />`

### Steps to reproduce:

 1. [it works here](https://reactcommunity.org/react-modal/examples/on_request_close.html)
 2. [it doesn't work here](https://reactcommunity.org/react-modal/examples/set_app_element.html)

### Expected behavior:
modal closes when clicking on the overlay by default

**Comment by claydiffrient** [comment]
@shonin It is indeed a problem with the documentation.  Because the open/close state of the modal is handled external to the modal itself, it needs the consumer to provide details on how to actually close the modal.  We'd be happy to accept a PR fixing the documentation.

**Comment by claydiffrient** [comment]
#352 closes this issue.
