### ISSUE TITLE
Can not close Modal when click on overlay (Please update the note in readme)

### ISSUE THREAD

**Issue by SLyHuy** [reactjs/react-modal#351]
### Summary: Can not close Modal when click on overlay
└─┬ react-modal@1.7.2 
  ├── element-class@0.2.2 
  ├── exenv@1.2.0 
  └── lodash.assign@4.2.0 

### Steps to reproduce:

 1. Remove **shouldCloseOnOverlayClick** prop --> Click on overlay --> nothing happen.
 2. Add shouldCloseOnOverlayClick={true} --> Click on overlay --> nothing happen.
 3. Add shouldCloseOnOverlayClick={false} --> Click on overlay --> nothing happen.

### Expected behavior: 

 1. Remove **shouldCloseOnOverlayClick** prop --> Click on overlay --> close modal.
 2. Add shouldCloseOnOverlayClick={true} --> Click on overlay --> close modal.
 3. Add shouldCloseOnOverlayClick={false} --> Click on overlay --> nothing happen.

**Comment by SLyHuy** [comment]
I read source code, and found:

![screen shot 2017-03-09 at 16 07 58](https://cloud.githubusercontent.com/assets/1643397/23743331/d01d17da-04e2-11e7-95c4-b5483de11d92.png)

Then it checks `ownerHandlesClose` and it needs `onRequestClose` prop. Then I have to pass manual function to change state for open or close modal.

Please put the note to Readme please.

**Comment by diasbruno** [comment]
@SLyHuy Can you add this note to the readme?
It's required to pass a function to control the state of the modal.

**Comment by SLyHuy** [comment]
@diasbruno Here is pull request https://github.com/reactjs/react-modal/pull/352

**Comment by claydiffrient** [comment]
#352 closed this issue.
