### ISSUE TITLE
How to reset the styles.

### ISSUE THREAD

**Issue by JonDotsoy** [reactjs/react-modal#357]

**Comment by diasbruno** [comment]
@JonDotsoy Hi, what do you mean by `reset`?

**Comment by JonDotsoy** [comment]
yes, but only the styles.

I,ve the next script to reset the estyle.

```javascript
const resetModalStyle = (() => {
  // Styles
  const initial = null

  const overlay = {
    position: initial,
    top: initial,
    left: initial,
    right: initial,
    bottom: initial,
    backgroundColor: initial,
    WebkitOverflowScrolling: initial,
    zIndex: initial,
  }

  const content = {
    position: initial,
    top: initial,
    left: initial,
    right: initial,
    bottom: initial,
    border: initial,
    background: initial,
    overflow: initial,
    borderRadius: initial,
    outline: initial,
    padding: initial,
  }

  return {overlay, content}
})()
```

Exists any `prop` to this same.

**Comment by diasbruno** [comment]
You can override the styles using:
```js
<Modal {...other_props} style={resetModalStyle()}>
  ...
</Modal>
```

**Comment by diasbruno** [comment]
Look at [react-modal#styles](https://github.com/reactjs/react-modal#styles) for more information.

**Comment by JonDotsoy** [comment]
In effect, solve it with:

```javascript
<Modal style={resetModalStyle}>
   ...
</Modal>
```

> ### Is possible added a `noStyle` prop to use the style from css?

**Comment by JonDotsoy** [comment]
## Is possible added a `noStyle` prop to use the style from CSS? This on next feature?

**Comment by diasbruno** [comment]
This would grow the interface of the component. 
We would end up with 2 places to set styles `(styles : object, noStyle : Bool)` which increases complexity.

For now, it's better for the user to provide the `zero style`.

**Comment by JonDotsoy** [comment]
Something similar to this.

```javascript
<Modal style={Modal.zeroStyle}>
   ...
</Modal>
```
