### ISSUE TITLE
How can I prevent screen movement(rubber effect) when the modal is open?

### ISSUE THREAD

**Issue by kimjuny** [reactjs/react-modal#361]
platform: safari

problem: How can i prevent screen movement(rubber effect) when the modal is open? I need to make the background staying fixed.

<b>OR</b> can I make overlay move all together with background instead of background pulling down but overlay staying fixed?

screenshot: 

![img](https://raw.githubusercontent.com/ronankim/imgbed/master/img2.jpg)

**Comment by andrew-wharton** [comment]
Have you tried using this (it's on the README)?

/* Remove scroll on the body when react-modal is open */
.ReactModal__Body--open {
    overflow: hidden;
}

**Comment by yezongyang** [comment]
'overflow: hidden' is not working for mobile

**Comment by diasbruno** [comment]
@kimjuny did you found a way to fix this? If yes, you can close this issue.

**Comment by diasbruno** [comment]
@kimjuny Thanks!
