### ISSUE TITLE
Error: React DOM tree root should always have a node reference

### ISSUE THREAD

**Issue by frodehansen2** [reactjs/react-modal#362]
### Summary:
"React DOM tree root should always have a node reference"

### Steps to reproduce:
We wrap the dialog component in an DialogLink component which controls the Dialog. We use this DialogLink component in lists which may have up to 1000 items. Because we don't want a lot of ReactModalPortal <divs> in our code for dialogs which may never be openend, the DialogLink does not render the Dialog if it is not open. When we use it this way, we get the "React DOM tree root should always have a node reference" when we close the dialog. Is there a way to use the dialog component like this without getteing the error? I recon the error comes because of the portal is not in the DOM when the dialog performs some cleanup.

### Expected behavior:
No error thrown

**Comment by frodehansen2** [comment]
My bad - local error

**Comment by mmiller42** [comment]
@frodehansen2 Could you elaborate on how to solve this? We're getting this issue when using react-modal on a React universal (server-side rendering) setup, I'm guessing it's because the component needs access to the DOM and it doesn't exist.

**Comment by frodehansen2** [comment]
I don't remember exactly what we had been doing wrong, but after an update and some changes, the error went away.
