### ISSUE TITLE
ReactModal__Body--open class not being set correctly

### ISSUE THREAD

**Issue by andrew-wharton** [reactjs/react-modal#365]
### Summary:

ReactModal__Body--open class not being set when more than one modal is used in a React component.

### Steps to reproduce:

See example http://codepen.io/anon/pen/yMwved

 1. Open first modal. Note background colour not changing. This is because the .ReactModal__Body--open class is not being set.
 2. Open the second modal. Note that the background color changes. This is because the class is being set correctly.

### Expected behavior:

The ReactModal__Body--open class should be set when all modals used by a React class are opened.

### Additional notes:

**Comment by diasbruno** [comment]
Hi @andrew-wharton, you can follow issue #231 and PR #358. :)

**Comment by andrew-wharton** [comment]
Ah, I thought this was a different problem, but I suppose it's the same underlying cause then. Thanks!
