### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by sizeight** [reactjs/react-modal#366]
### Summary:
In react 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there:

**Comment by miketheanimal** [comment]
Ditto, getting this

**Comment by claydiffrient** [comment]
Fixed in v1.7.4

**Comment by rushmata** [comment]
run in your shell "npm update"

**Comment by aseem2625** [comment]
Strangely, I'm getting this error
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead`

 even after having:
```
import PropTypes from 'prop-types';
```
and

```
Home.propTypes = {
  increment: PropTypes.func,
  count: PropTypes.number
};
```
Note: I'm having only 1 component in my project. So, that's not isssue.
