### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by diegohaz** [reactjs/react-modal#375]
https://travis-ci.org/diegohaz/arc/builds/221734613#L251

**Comment by nickswope** [comment]
I just installed this package and am getting the same error whenever I try to import the Modal.

I get this error simply by including the line `import Modal from 'react-modal'`

**Comment by Kyr** [comment]
Same issue :disappointed:

**Comment by KyleKilbride** [comment]
I also get this error when updating to version 1.7.4. This was not an issue in any version previous to this. I will revert for now.

**Comment by claydiffrient** [comment]
Shoot looks like I missed some ES2015 in my review of #358.

I'll get a fix up ASAP.  Sorry for your builds breaking.

**Comment by claydiffrient** [comment]
Okay please give 1.7.5 a shot :)

**Comment by KyleKilbride** [comment]
Works great, thank you!

**Comment by diasbruno** [comment]
Hmm, my bad. I've forget to remove the 'export' syntax when I moved the PR from `master` to `v1`. See #358.
