### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by royroev** [reactjs/react-modal#376]
ERROR in vendor.33d6a985.js from UglifyJs
    SyntaxError: Unexpected token punc «(», expected punc «:» [../~/react-modal/lib/helpers/refCount.js:4,0]

**Comment by royroev** [comment]
and after update 1.7.5 too

**Comment by claydiffrient** [comment]
This is the gift that keeps on giving.  I'll get a fix up.

**Comment by claydiffrient** [comment]
Give 1.7.6 a shot
