### ISSUE TITLE
No change log since 1.6.5

### ISSUE THREAD

**Issue by sapegin** [reactjs/react-modal#377]

**Comment by claydiffrient** [comment]
Sorry about that.  We've been cutting 1.7 releases from the the v1 branch and that branch does have changelog entries.  I'll clean it up and move it over to the master branch.  We've been using the master branch to track development for 2.0 and the v1 branch to backport small important changes to help people get by until 2.0 can be released.

**Comment by claydiffrient** [comment]
Changelog entries have been updated on the master branch. ea3e536004c5ec720c394ea80cb3adff20ed5afb was the commit that did so.  Thanks!
