### ISSUE TITLE
Warning: getDefaultProps

### ISSUE THREAD

**Issue by AndersDJohnson** [reactjs/react-modal#378]
### Summary:

Error in console:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

### Steps to reproduce:

 1. Render any modal with `react-modal@1.7.6` and `react@15.5`.

### Expected behavior:

Should be using `defaultProps` statics - not sure why it compiles down to using `getDefaultProps`.

**Comment by diasbruno** [comment]
@AndersDJohnson It seems to be fixed on `v1.7.7`. Can you validate?

**Comment by diasbruno** [comment]
@AndersDJohnson This should be fixed on our new version `v2.0+`. 
If the problem persist, please, feel free to open this issue again. Thank you.

**Comment by bcuicn** [comment]
It is still happening for me.

**Comment by diasbruno** [comment]
@bcuicn Hi, which version are you using? `react-modal` and `react`
