### ISSUE TITLE
Is there a way to enable scrolling behind the modal?

### ISSUE THREAD

**Issue by petertdinh** [reactjs/react-modal#379]
### Summary:
I know it goes a lot against the nature of what a modal is suppose to do, but is there a way to make it so that when my mouse is hovering on the overlay, I am able the scroll the content behind it using the mousewheel?

As with most setups, I have two different React root components, one for all non-modal content, and one for contents within the modal itself. They are siblings within the body.

**Comment by SergeyShvager** [comment]
Hello, 
By default its enable scrolling, but if you add this css it could block scroll.

.ReactModal__Body--open {
    overflow: hidden;
}

So, just remove this css if you have such one.

**Comment by diasbruno** [comment]
@petertdinh Is @SergeyShvager suggestion solves you problem? If so, you can close this issue.
@SergeyShvager Thank you!

**Comment by vorpus** [comment]
@diasbruno @SergeyShvager Is there a way to allow scrolling only when certain modals are open, but keep `overflow:hidden` for others?

**Comment by diasbruno** [comment]
@vorpus One option is to use a custom class for your specific modal. See [reactjs/react-modal#using-css-classes](https://github.com/reactjs/react-modal#using-css-classes).
