### ISSUE TITLE
Prevent modal from closing when clicking modal, dragging to overlay, and releasing

### ISSUE THREAD

**Issue by bschlenk** [reactjs/react-modal#383]
### Summary:
I have a draggable image within a modal. If I am dragging the image and I release the cursor outside the modal window, e.g. within the overlay, the modal closes.

### Steps to reproduce:

 1. Create a modal window
 2. Click within the modal window and while keeping the mouse button down, drag over to the darker overlay area
 3. Release the mouse button
 4. Observe the modal closing

### Expected behavior:
I expect the modal not to close. I do still expect it to close when I click and release the overlay directly. I don't expect the modal to close if click originates within the modal window.

### Additional notes:
I'm not too familiar with the way browser click events work, but I suspect that because the modal window is nested within the overlay window, the initial click within the modal window is treated as a click on the overlay. It may be possible to check that the event target is the overlay window before closing the modal.

**Comment by bschlenk** [comment]
Turns out this is caused by me calling e.preventDefault() within my own mouseDown handler. The issue is that if I don't, the browser has its own behavior for dragging an image. I can work around this by using css background-image instead of an img element.

**Comment by bschlenk** [comment]
Some more testing reveals that this is not affected by having a preventDefault for my own mouseDown handler. The issue described above still stands.

**Comment by diasbruno** [comment]
@bschlenk can you provide more information about this issue? (like version, browser...)

**Comment by diasbruno** [comment]
@bschlenk I can not reproduce this bug. 
Please, feel free to reopen this issue if needed. Thanks.

**Comment by skudari** [comment]
What was the resolution?

**Comment by diasbruno** [comment]
@skudari If you drag something over the overlay and release it there, it will trigger the onMouseUp handler...so it will close.

**Comment by diasbruno** [comment]
If there is a way to detect this behavior and it doesn't introduce to much logic on this package, we can work something...

PRs are welcome.
