### ISSUE TITLE
onClick calls within modal body not firing

### ISSUE THREAD

**Issue by micodel** [reactjs/react-modal#384]
### Summary:
I have a button within my modal body, identical to the examples in the readme and docs. When I click the button, nothing happens. I cannot even console log.

I am trying to use this button to close the modal. It is calling the same function that is able to successfully close the modal on overlay click.

My modal does close the modal on overlay click if this causes a conflict.

My best guess is some logic that prevents the modal from closing when the modal body is clicked, is preventing my button from being clicked as well.

### Steps to reproduce:

 1. Create a modal similar to those outlined in the docs
 2. Add an element that handles onClick events (button, div, a)
 3. Try and click the button.

### Expected behavior:

I would expect that my button would be able to call functions as indicated by the docs.

**Comment by diasbruno** [comment]
@micodel can you provide more information about this issue? (like version, browser...)

**Comment by diasbruno** [comment]
@netto89 @wschaeferiii @micodel `react-modal` is current on version `v2+`. (preferable version `v2.0.6` - latest). If you can, please update to this version.

If you can provide more information, please reopen this PR.

Thanks.
