### ISSUE TITLE
Problems when using an object for the className

### ISSUE THREAD

**Issue by Tydax** [reactjs/react-modal#385]
### Summary:
Hello there. I have been facing some issues when trying to use an object as a prop the `className` in the modal.
Apparently, the object is not properly translated into a string.
### Steps to reproduce:

 1. Use an object for the `className` prop. For example:
```javascript
<Modal
  className={{
    base: 'react-modal-container',
    afterOpen: '-after-open',
    beforeClose: '-before-close',
  }}
/>
```

2. When inspecting the element in a browser, the `div` is given that `className`: `ReactModal__Content ReactModal__Content--after-open [object Object]`

### Expected behavior:
The object should be transformed appropriately into a string.

**Comment by vasco-santos** [comment]
I am with the same problem as described by @Tydax

**Comment by jimulle** [comment]
Same issue here too

**Comment by teameh** [comment]
Same here, but it works if you just provide a single string instead of an object though!

**Comment by diasbruno** [comment]
Hi @teameh @vasco-santos @jimbolla @Tydax, can you tell which version?

**Comment by teameh** [comment]
Latest version, just freshly installed. `1.7.7`

**Comment by diasbruno** [comment]
```js
<Modal
  className={{
    base: 'react-modal-container',
    afterOpen: '-after-open',
    beforeClose: '-before-close',
  }}
/>
```

feature is available on the `master` branch. All versions `v1.x.y` are released from the branch `v1` which will be discontinued when the documentation and some 'modernization' of the source code are finished. 

The last commit on `master` introduces this feature (which needs a backport to `v1` [commit/6442387b4d7](https://github.com/reactjs/react-modal/commit/6442387b4d72b822686a85fb20b4af9893a89687)).

**Comment by plemarquand** [comment]
Can I suggest the default github branch be set to `v1` until the new code on master is released?

My first instinct when pulling the latest release over npm is that the documentation on github matches my release. I got bit by this bug because I was coding against the documentation (and source code) on the `master` branch without realizing I was running code in the `v1` branch.

**Comment by diasbruno** [comment]
@plemarquand Fair enough. cc @claydiffrient.

**Comment by diasbruno** [comment]
@plemarquand @teameh @jimulle @Tydax @vasco-santos `v2.0.0` has been released, so this is now available. `master` branch is now up-to-date. Thank you.
