### ISSUE TITLE
Body ClassName not available

### ISSUE THREAD

**Issue by vasco-santos** [reactjs/react-modal#388]
### Summary:

The **bodyOpenClassName** prop is not being used in the last tag provided by this module. However, this feature is currently implemented on [master branch of the repository](https://github.com/reactjs/react-modal/commit/6442387b4d72b822686a85fb20b4af9893a89687#diff-476e2e918a31cbbf34324b08ddeee24e). It would be important to create a new TAG with this feature.

### Steps to reproduce:

 1. Render a Modal with the **bodyOpenClassName** prop on it.

### Expected behavior:

New class should be added to the body instead of the default **ReactModal__Body--open**

### Additional notes:

This commit also contains the object classNames which would solve Issue [#385](https://github.com/reactjs/react-modal/issues/385)

**Comment by diasbruno** [comment]
Yeah, this feature needs a backport to`v1`.

**Comment by tiagojsalmeida** [comment]
When is this going to be released?

**Comment by diasbruno** [comment]
@tiagojsalmeida do you mind take care of this backport? I'm trying to do some house cleaning on react-modal.

**Comment by diasbruno** [comment]
@tiagojsalmeida @vasco-santos can you review PR #404?

**Comment by vasco-santos** [comment]
Thanks for the backport.

I reviewed the code, and it seems ready for being launched. 😄

**Comment by diasbruno** [comment]
Released `v1.8.1`.

**Comment by diasbruno** [comment]
Since, `bodyOpenClassName` is now available on `v1.8+`, I'll close this issue.
Thank you, @vasco-santos.
