### ISSUE TITLE
Element behind is overlapping react-modal

### ISSUE THREAD

**Issue by darylong** [reactjs/react-modal#390]
### Summary: Part of the element from the background is overlapping even if react-modal is present.

I'm using react-dates from Airbnb and part of the component of the calendar such as navigation button and help button (green question mark) is overlapping even when the react-modal is presented. Everything else works fine.

Does anyone have an idea why this is happening?

![screen shot 2017-05-28 at 12 25 47 am](https://cloud.githubusercontent.com/assets/29003217/26522869/a1562db8-433c-11e7-9c23-5fe55121ba77.png)

**Comment by matthew-matvei** [comment]
There may be a better solution by the package author, but you could set the `z-index` style on the overlay. You can put something in your CSS like:

    .ReactModal__Overlay {
        z-index: 1000;
    }

That worked for me. Let me know how it goes.

**Comment by darylong** [comment]
Hi @matthew-matvei , thank you so much for the solution. It was really silly of me for not thinking to modify the z-index. Definitely appreciate the quick fix to the problem. 

Would also be curious to find out what was the root cause to the problem as I'm relatively new in React development. Thanks again!

**Comment by matthew-matvei** [comment]
No worries.

Apparently, React decides Z-index based on the component's order in the render tree. Given that it's likely you'll have other components down the line from where the modal is placed, I guess you'll probably have something overlapping by default (unless there's something else we've both neglected ;-) )

**Comment by diasbruno** [comment]
@darylong is this a fix for your issue? If so, you can close this.
@matthew-matvei Thank you!

**Comment by matthew-matvei** [comment]
@diasbruno no worries!

**Comment by darylong** [comment]
Yes the issue is now fixed thanks to @matthew-matvei. Will be closing now, thanks!

**Comment by AlexGalo0** [comment]
> There may be a better solution by the package author, but you could set the `z-index` style on the overlay. You can put something in your CSS like:
> 
> ```
> .ReactModal__Overlay {
>     z-index: 1000;
> }
> ```
> 
> That worked for me. Let me know how it goes.

It also worked for me! Cool!

**Comment by diasbruno** [comment]
Managing the z-index is not something package should handle...It would be completely speculative to know the right option for all projects, so...better handle on a project basis.

**Comment by diasbruno** [comment]
Also, this only happens on projects that already messed with the default DOM layering, or, have particular needs to manually handle layering.
