### ISSUE TITLE
onRequestClose arguments - Feature Request

### ISSUE THREAD

**Issue by Miges** [reactjs/react-modal#391]
A really nice feature would be to pass to the `onRequestClose` how the close was requested, e.g. by mouse click outside the modal or by escape key, etc.

**Comment by diasbruno** [comment]
Hi @Miges, there is a PR (#327) to forward the events to the callback. Can you review this PR?

**Comment by diasbruno** [comment]
Hmm, that is not implemented in this PR. Sorry :). It just forward the `onClick` and `onKeyDown` events to a callback (old PR).
Any specific reason to know how it was requested to close?

**Comment by Miges** [comment]
@diasbruno - sorry, missed your previous comment!  I think the problem was that we had a case where we wanted to distinguish between a dismissal on purpose (e.g. the escape key was hit) vs an accidental dismissal (the user clicked outside the modal)

**Comment by diasbruno** [comment]
No problem. It makes sense. This seems already implemented, so `onRequestClose` will receive the event. Now, it's just a matter of inspect the `event` object. Feel free to open a new issue if something is still missing. 

Thank you, @Miges.
