### ISSUE TITLE
Scrolling the Modal content

### ISSUE THREAD

**Issue by mmarinm** [reactjs/react-modal#392]
### Summary:
I included class rule for preventing background scrolling
```
    .ReactModal__Body--open {
        overflow: hidden;
        position: fixed;
        width: 100%;
        height: 100%;
    }

```
but when the modal opens I want to scroll the content inside of it. Can someone help me I am not able to find an appropriate solution in closed issues?

**Comment by diasbruno** [comment]
Hi @mmarinm, do you mean the content inside de overlay or the real content inside the modal?

**Comment by mmarinm** [comment]
The  content inside that modal

**Comment by diasbruno** [comment]
Hmm, ok. You can make a frame for the scrollable region.

```html
<Modal ...>
  <div className="frame"> <!-- relative and height 100% -->
    <div className="scroll"> <!-- height 100%, maybe overflow-x: auto -->
          [...] <!-- your content -->
    </div>
  </div>
</Modal>
```

Something like this would work, probably you will need to make some tweaks own this example.

**Comment by mmarinm** [comment]
Ok, Thank you, It might be also related to the library I use for smooth scrolling.  I decided to use router instead of the modal

**Comment by Monte9** [comment]
@diasbruno your solution works like a charm. 🌟 Thanks a lot for your help!

**Comment by diasbruno** [comment]
@Monte9 I've updated the example, because it was really bad code. :)
