### ISSUE TITLE
extra border around my border

### ISSUE THREAD

**Issue by des-des** [reactjs/react-modal#393]
### Summary:
Somewhere is react modal it is adding an extra border to the modal. But I cannot find this using the inspector.

This border only appears when the page has focus.

![image](https://cloud.githubusercontent.com/assets/12845233/26824029/af357c64-4aa7-11e7-8224-6e4479bc1814.png)

(see the gray border around my blue border)

I am using className and overlayClassName props.

**Comment by zeakd** [comment]
I have same issue. is it natural? I solved this problem ` :focus {outline:0;} ` on my modal class.

**Comment by des-des** [comment]
Is it natural? Not sure, I think it might be a result of the accessibility stuff going on.. ?

Thanks for the fix!
