### ISSUE TITLE
Farewell

### ISSUE THREAD

**Issue by claydiffrient** [reactjs/react-modal#396]
For all the details check out my [Medium post](https://medium.com/@claydiffrient/farewell-react-modal-e960bfc27bd8).

The tl;dr is basically that I’m overwhelmed and out of time so I’m turning everything over to @diasbruno as I step away from React Modal.

Thanks for everything and goodbye!

**Comment by diasbruno** [comment]
Thank you so much for your time managing `react-modal`.

**Comment by jamesjjk** [comment]
@claydiffrient Awesome work!
