### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by claydiffrient** [reactjs/react-modal#422]
### Summary: 

The CHANGELOG.md file hasn't been updated for a few releases

### Steps to reproduce:

 1. Look at changelog :)

### Expected behavior:  

I would expect it to show release notes for what has occurred in each version

### Additional notes:

If memory serves correctly, you can generate the CHANGELOG.md by using `./scripts/release` when running a release or using `node_modules/rf-changelog/bin/changelog` when not running a full release.

Also, it feels really weird to file an issue and not see all the additional options, but yet it's very relaxing somehow :)

**Comment by diasbruno** [comment]
Yes :), i think I've added in milestone `2.1.0`. It still needs some work to do to get everything in this version.
I tried to find the tool you're using to generate the changelog, so I've decided to update later.

**Comment by diasbruno** [comment]
Finally! I've updated the changelog. I added a small python script to regenerate all the changelog, but it will be gone soon and use your previous script.
