### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by merlinpatt** [reactjs/react-modal#432]
Do you have best practices on how write modal code? Not just how to use the modal, but how to use it well.

We have a couple dozen modals and currently I have them each tied to their own button. But I'm considering using URL query params to manage the modals appearance instead.

There's also the consideration of having each modal be its own separate modal or have one modal that loads the body dynamically.

And in some cases we have a modal that opens another modal so they both need to be open at the same time.

What tips do you have on successfully managing a mess of modals?

**Comment by diasbruno** [comment]
Hi @merlinpatt, some ideas after working with modals:

In case of multiple modals, an example is to define a state like 

```js
{ currentModal: String | null, ... }
``` 

and set `currentModal` with the modal identifier or `null` to close all.

```js
const MODAL1 = 'modal1';
const MODAL2 = 'modal2';

<Modal isOpen={state.currentModal == MODAL1}...>...</Modal>
<Modal isOpen={state.currentModal == MODAL2}...>...</Modal>
```

State that can handle many modals:

```js
// NOTE: this object can be local for a context or global, 
// so you can have many states like this to manage each context.
{ modal1: Boolean, modal2: Boolean, ... }

<Modal isOpen={state.modal1}...>...</Modal>
<Modal isOpen={state.modal2}...>...</Modal>
```

One thing to note is that both states can be used on the same application (imagine a page/route `/todos` with first state and a page/route `/projects` with second state).

Better to keep state small as possible, so dynamically load on the same opened modal when possible.

There are so many ways to manage this state, but I hope this can help.
