### ISSUE TITLE
Didn't update `portalClassName` after receiving of new props

### ISSUE THREAD

**Issue by html-krit** [reactjs/react-modal#435]
### Summary:
Didn't update `portalClassName` after receiving of new props because className added only in `componentDidMount`
### Steps to reproduce:

 1. add custom `portalClassName`
 2. change somehow this props by click on button
 3. className for portal not changed

### Expected behavior:
className for portal must be updated

**Comment by diasbruno** [comment]
Hi @html-krit, which version of `react-modal` and `react` are you using?

**Comment by diasbruno** [comment]
@html-krit this behavior does not seems to happen on `v2.0.2+`.
[codesandbox.io/KvKnrK5G](https://codesandbox.io/s/KvKnrK5G)

If you have more information about this issue, please reopen this PR. 
Thanks.
