### ISSUE TITLE
Thoughts on making the modal draggable?

### ISSUE THREAD

**Issue by AndrewRayCode** [reactjs/react-modal#45]
I'm looking at https://github.com/mzabriskie/react-draggable. However, you cannot do this:

```
<Draggable><Modal /></Draggable>
```

nor can you do this:

```
<Modal><Draggable>Contents</Draggable></Modal>
```

because of the way modalportal works. Any suggestions?

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in over a year.  I'm assuming that this is no longer an issue.  If it is, please feel free to re-open.

**Comment by eldamir** [comment]
Would be really great to have this functionality.

@parlop was nice enough to tell that he made it work with react-draggable (#232), but didn't have the decency to share any details :frowning_face:
