### ISSUE TITLE
How To Load URL in React Modal?

### ISSUE THREAD

**Issue by MZShahbaz** [reactjs/react-modal#453]
- I am interested in displaying a remote URL in my **react modal**

- I may get data of that URL using AJAX call but how may I render that exact URL in my modal?

- Any help would be appreciated...

**Comment by diasbruno** [comment]
There are a few options:

#### 1. Make an request and save the data on some state. Render in the Modal afterwards.

You can execute when opening the modal or use `onAfterOpen`.

#### 2. Add an `iframe` on the modal.

**Comment by MZShahbaz** [comment]
Thanks @diasbruno ...
Your option 2 was easy to pursue.
I used iframe ion the modal and 
window.open(link,'NewWindow','resizable=yes'); without modal
