### ISSUE TITLE
Can't scroll modal if body is setted to fixed

### ISSUE THREAD

**Issue by victorsabino** [reactjs/react-modal#455]
Hello guys, I was having problems with the famous background scrolling instead of the modal issue. After some research I found that the fix is to set the body position to fixed, thanks to that the background doesn't scroll anymore but neither does the modal on Chrome and iOS (for some reason it works as intended on firefox) 

Remove the position: fixed attribute fixed the issue on desktop but of course the scrolling issue persists on iOS

**css**

.ReactModal__Body--open {
  overflow: hidden;
  position: fixed;
  width: 100%;
  height: 100%;
}

**javascript customStyle**

const customStyles = {
  overlay: {
    backgroundColor: 'rgba(57, 43, 46, 0.8)',
  },
  content: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 'auto',
    bottom: 'auto',
    border: 'none',
    borderRadius: 'none',
    height: '700px',
    width: '100%',
    padding: 0,
    overflowY: 'auto',
    backgroundColor: 'transparent',
    pointerEvents: 'none'
  }
}

**Comment by diasbruno** [comment]
Hi @victorsabino this seems duplicated, can you search for the issue?

**Comment by diasbruno** [comment]
Closing this for now. Please, feel free to reopen if needed.
