### ISSUE TITLE
Latest Master not loading react-modal css class

### ISSUE THREAD

**Issue by sachin32** [reactjs/react-modal#456]
### Summary:
After installation i used react model but it shows at bottom position.
### Steps to reproduce:

 1. Open application
 2. Open any react-model component in browser 
 3. Do inspect
 4. ReactModal__Overlay ReactModal__Overlay--after-open class not loading
 5. ReactModal__Content ReactModal__Content--after-open class notloading

### Expected behavior:
React model should come into middle of the page

### Additional notes:
![image](https://user-images.githubusercontent.com/23550462/28207233-85ee4418-68a6-11e7-999d-f1ec4f4ed525.png)

**Comment by diasbruno** [comment]
Hi @sachin32, `react-modal` has a default inline style, but If you have declared a `className` or a `overlayClassName`, those styles are nullified. Can you have a look on this?

Here is where the declaration is [src/components/Modal.js#L72](https://github.com/reactjs/react-modal/blob/master/src/components/Modal.js#L72) and here it gets nullified if a `className` is defined. [src/components/ModalPortal.js#L261](https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L261).

**Comment by sachin32** [comment]
@diasbruno Thanks for reply 

The issue is that same code same master is giving output perfectly for my team members but when we do npm install after cloning the project from scratch level then only issue is coming.

**Comment by diasbruno** [comment]
Hm, I got it. I'll check it.

**Comment by sachin32** [comment]
Fixed npm-cache was the problem
