### ISSUE TITLE
Modal does not close in between showing items from an array of objects

### ISSUE THREAD

**Issue by sayayinR** [reactjs/react-modal#460]
I have posted this on on stackoverflow:
https://stackoverflow.com/questions/45228757/react-modal-does-not-close-in-between-loading-content?noredirect=1#comment77424831_45228757

Not sure if this has to do something with the way I'm calling the Modal or it is an expected behavior of the Modal, either way looking for a solution if someone can help.

Thank you!

**Comment by tcrosen** [comment]
It seems to me this is an issue with your managing of the `isOpen` prop. 

Can probably close this as you are getting help from SO folks, right @sayayinR?

**Comment by sayayinR** [comment]
Yes, I have solved the issue in a different way. You can close it

**Comment by diasbruno** [comment]
@sayayinR how did you solve this? This can help other people if they face the same problem. :)

**Comment by diasbruno** [comment]
@sayayinR I'm closing this issue since the problem was fixed.

**Comment by diasbruno** [comment]
@tcrosen Thanks for looking on this one.
