### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by EbrahimMajdey** [reactjs/react-modal#461]
### Summary:
npm install produces not met dependencies
### Steps to reproduce:

npm install react-modal
### Expected behavior:

+-- UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0
+-- UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.0.0
`-- react-modal@2.2.2
  +-- exenv@1.2.0
  +-- prop-types@15.5.10
  | +-- fbjs@0.8.12
  | | +-- core-js@1.2.7
  | | +-- isomorphic-fetch@2.2.1
  | | | +-- node-fetch@1.7.1
  | | | | +-- encoding@0.1.12
  | | | | | `-- iconv-lite@0.4.18
  | | | | `-- is-stream@1.1.0
  | | | `-- whatwg-fetch@2.0.3
  | | +-- object-assign@4.1.1
  | | +-- promise@7.3.1
  | | | `-- asap@2.0.6
  | | +-- setimmediate@1.0.5
  | | `-- ua-parser-js@0.7.14
  | `-- loose-envify@1.3.1
  |   `-- js-tokens@3.0.2
  +-- UNMET PEER DEPENDENCY react@^15.5.4
  `-- react-dom-factories@1.0.0

**Comment by diasbruno** [comment]
@EbrahimMajdey yeah, that's right. we need to update it. 
@leonascimento can you have a look on this?

**Comment by diasbruno** [comment]
@EbrahimMajdey Probably, by now, you might have found a solution for this. Please reopen this issue if the problem persists. Thank you.
