### ISSUE TITLE
Allow opting out of returning focus on close

### ISSUE THREAD

**Issue by Hypnosphi** [reactjs/react-modal#464]
### Summary:

I use react-modal to display a search box with autocompletion. When I find a suitable option and hits enter key, I'm navigated to corresponding view, and the modal should be closed. Unfortunately, button that opens the modal gets re-focused, and a click event is fired on it (because that's how enter key works with buttons), so the modal gets open again.

It helps if I add some closeTimeoutMS, but then it starts depending on how long do I hold the key. So I'd prefer just to opt out of refocusing in such cases.

### Link to example of issue:
https://codesandbox.io/s/kZmzPBLGX

**Comment by ndelangen** [comment]
Is this resolved? @Hypnosphi @diasbruno 

https://github.com/storybooks/storybook/blob/7b996460cab90d1af953e20f10fe1236baf850ba/lib/ui/src/modules/ui/components/search_box.js#L73

**Comment by diasbruno** [comment]
@ndelangen Not yet. Perhaps we are giving back the focus to earlier and some event is firing. Also, I can reproduce this issue on Chrome - Safari and Firefox are working ok.

Maybe It's related to #494.

**Comment by diasbruno** [comment]
Released `v3.1.0` with an option to avoid the 'return focus on close'.

**Comment by Hypnosphi** [comment]
Still not completely fixed, see https://github.com/reactjs/react-modal/pull/540/files#r148984350
