### ISSUE TITLE
React v16-beta upgrade - componentWillUnmount error

### ISSUE THREAD

**Issue by jakepeyser** [reactjs/react-modal#476]
### Summary:
The `Modal` component is throwing an error in `componentWillUnmount` after upgrading React to v16-beta.

### Steps to reproduce:

 1. Upgrade React to `@next`
 2. Use the `Modal` component as before.
 3. Remove the containing component from the DOM and the error will occur

![image](https://user-images.githubusercontent.com/1534503/29189496-c8c1a5fc-7de4-11e7-9fe8-71afaa820d71.png)

### Additional notes:

After some research, it seems this is directly related to the usage of `renderSubtreeIntoContainer` method to set `this.portal` in Modal. This is described in depth in https://github.com/facebook/react/issues/10309. Since portal is never set correctly, assuming its existence in `componentWillUnmount` causes the error.

### Details
- Mac OSX
- Chrome v59.0.3071.115

**Comment by diasbruno** [comment]
Hi @jakepeyser #474 is available. A new version will be available today.

**Comment by jakepeyser** [comment]
Brilliant. Thanks @diasbruno

**Comment by diasbruno** [comment]
Released `v2.2.3`.

**Comment by uwolfer** [comment]
In my case, `ReactModalPortal` DOM elements are leaked due to this. When `this.portal` is undefined, things do not get cleaned up. This can be reproduced in my case with React 16 only - it works fine with React 15.x. Can you please check your DOM and see if things get cleaned up?

**Comment by diasbruno** [comment]
@uwolfer `react-modal@3.0.0-alpha` is available now. Let me know if this still happens.

To install, use `npm install react-modal@next`.

**Comment by uwolfer** [comment]
@diasbruno: Thank you, this fixes my issue.
