### ISSUE TITLE
How to get reference to overlay element

### ISSUE THREAD

**Issue by OliverJAsh** [reactjs/react-modal#478]
I need to get a reference to the overlay element, as I have enabled scrolling and this needs to be reset when navigating between routes (`scrollTop = 0`).

I am currently accessing this via `reactModalRef.portal.overlay`. Is this the recommended solution?

**Comment by diasbruno** [comment]
Hi @OliverJAsh, that's one way to do it. Maybe it would be helpful if we allow the user to get the refs if needed...something like `overlayRef={fn}` and `contentRef={fn}`. Any thoughts?
