### ISSUE TITLE
Thoughts on hiding the overlay?

### ISSUE THREAD

**Issue by AndrewRayCode** [reactjs/react-modal#48]
There are some cases in my app where I'd like to not have the overlay behind the modal. Because the (`position: fixed`) styles are set as inline on the overlay, I cannot override them with `overlayClassName` to massage the overlay into being hidden.

**Comment by zdfs** [comment]
Would modifying the CSS work (to be transparent) or do you want a prop that controls the creation of the overlay?

**Comment by DelvarWorld** [comment]
I want to be able to click on things behind the modal (think a dialog in an editor). might try transparent + pointer events

**Comment by zdfs** [comment]
Ah. It might be better to have a prop then that dictates whether the overlay is made or not. Probably a cleaner solution.

**Comment by weixing2014** [comment]
@DelvarWorld Do you figure out how to implement it? I had the same question. Thanks!

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in over a year. I'm assuming that this is no longer an issue. If it is, please feel free to re-open.

**Comment by KingZee** [comment]
I would like a fix to this issue. I want to control css of the overlay independly from the modal content.
