### ISSUE TITLE
Has anyone been able to implement modal with a drag and drop library?

### ISSUE THREAD

**Issue by tjones0808** [reactjs/react-modal#482]
I'm trying to open a modal after i've started dragging my object. as soon i do, the drag disappears and modal kills  it seems.

Anyone have any luck with this?

looking for something like this (https://tympanus.net/Development/DragDropInteractions/modal.html)

**Comment by dzek69** [comment]
If you managed to find a solution - maybe share it?

**Comment by tjones0808** [comment]
solution for me was to call a setTimeout with 0 ms before opening react modal. This allowed ReactDND to do its thing and catchup.
