### ISSUE TITLE
How do I find out what changed?

### ISSUE THREAD

**Issue by sontek** [reactjs/react-modal#483]
I'm currently on 2.2.2  and I see 2.2.4 is released, but in the changelog it shows that there was nothing new between the versions.   Should I be looking somewhere other than here:

https://raw.githubusercontent.com/reactjs/react-modal/master/CHANGELOG.md

For information on the changes?

**Comment by diasbruno** [comment]
@sontek Actually, the changelog generator is broken. You can see what changed in [react-modal/commits](https://github.com/reactjs/react-modal/commits/master).
But thanks for remind me that I need to fix this. :)

**Comment by diasbruno** [comment]
Related to #477.

**Comment by diasbruno** [comment]
@sontek I've regenerated the changelog. Thanks.
