### ISSUE TITLE
React Fiber support

### ISSUE THREAD

**Issue by maschwenk** [reactjs/react-modal#484]
It appears that this library is not compatible with React Fiber. It is using some deprecated/removed React API's. Are there any plans in place to get start this work? Curious how much work is involved. 

https://github.com/facebook/react/issues/10294#issuecomment-318210497

**Comment by diasbruno** [comment]
@maschwenk Yeah, that's for sure. Thanks for the link and PRs are always welcome.

**Comment by maschwenk** [comment]
Initial investigation shows that we need to replace `unstable_renderSubtreeIntoContainer` with `unstable_createPortal`. React maintainer details it here: https://github.com/facebook/react/issues/9808#issuecomment-308085984 and provided this fiddle https://jsfiddle.net/r442t0mk/

**Comment by sandys** [comment]
we are also getting impacted by this issue.

**Comment by diasbruno** [comment]
@maschwenk @sandys I'll merge this issue with @amannn's issue #498 to tackle this. Perhaps, we can open a project and make a roadmap for the next version.

**Comment by diasbruno** [comment]
`react-modal@3.0.0-alpha` is available. 

Version `2.3.3` is the stable version and can be installed with `react-modal@latest`.

To use the compatible version with React 16, you can install by running `npm install react-modal@next`.

**Comment by merlinpatt** [comment]
Why use `unstable_createPortal`? Why not use `ReactDOM.createPortal`?

https://egghead.io/lessons/react-render-elements-outside-the-current-react-tree-using-portals-in-react-16

**Comment by diasbruno** [comment]
@merlinpatt I think this was before `createPortal` got in the API.

**Comment by diasbruno** [comment]
Released official v3.0.0. 

You can follow #498 for more information.

Thank you all.
