### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by clobo-nativapps** [reactjs/react-modal#485]
I'm currently working on a project that requires us to support IE. I want to use this library for the modals but I didn't find anything about the browser support. 

Does this library support IE9+?

**Comment by diasbruno** [comment]
@clobo-nativapps There is an issue with some releases of `react-modal` due to some missing transforms (babel).

You can follow #465 for more information.

**Comment by diasbruno** [comment]
I'm tagging this as duplicated so we can discuss this on #465.
Thank you.
