### ISSUE TITLE
Changelog error

### ISSUE THREAD

**Issue by nickcampbell18** [reactjs/react-modal#491]
### Summary:

I think the script which generates your changelog is broken, as the newest version has two entries for v2.2.4 without any detail inside: https://github.com/reactjs/react-modal/blob/57e9316ff343281967b395255b8e478ac98a0b37/CHANGELOG.md.

I was going to submit a pull request, but I suspect you have a mechanism to do this automatically!

**Comment by diasbruno** [comment]
You can follow #477 and #483. Yeah, I just didn't have the time to fix it. 
Hope I can fix this week.

**Comment by diasbruno** [comment]
@nickcampbell18 If you want to have a look on this, it's a simple python script in `scripts/changelog.py`.

**Comment by diasbruno** [comment]
I've regenerated the changelog. I think the problem is when the `publish` task fails, it will leave some artifacts behind. So it needs a proper way to `clean` after it fails.
