### ISSUE TITLE
ARIA Attributes Not Appearing?

### ISSUE THREAD

**Issue by cycomachead** [reactjs/react-modal#496]
### Summary:
When I have a Modal Component, I can't seem to pass aria props that work properly. 

```jsx
<Modal
  aria={{
          labelledby: (this.props.heading ? this.headingId() : null),
          describedby: (this.props.subheading ? this.subheadingId() : null),
          modal: true,
        }}
>
</Modal>
```

### Steps to reproduce:

 1. Use the `aria` prop
 2. That's it. :)

### Expected behavior:
You should see aria-* attributes when you inspect an open modal element, but I don't see any.

### Link to example of issue:
https://codesandbox.io/s/lxm760yoj9

### Additional notes:
I've tried all combos and can't get anything working. (Storybox, code sandbox, my app, no matter what I can see the aria attributes on the resulting DOM element.

**Comment by diasbruno** [comment]
Hi @cycomachead, `aria` attribute is available on version `v2.2+`.

**Comment by cycomachead** [comment]
Ah, sorry, I should have added, I'm using the latest version. (I didn't realize code sandbox wasn't updated, but it should be now.) Even after updating I cannot see the right attributes.

**Comment by diasbruno** [comment]
Hm, probably we need a reminder to update the sandbox. I forked your sandbox and just updated to the latest version (v2.3.2) and it seems to be working. https://codesandbox.io/s/lxm760yoj9
Is it not adding all the attributes or just a specific one?

**Comment by diasbruno** [comment]
@cycomachead I'll close this issue and If there is something more specific about this, you can open a new issue. Thanks!
