### ISSUE TITLE
Modal inherits overlay's opacity

### ISSUE THREAD

**Issue by madeinspace** [reactjs/react-modal#501]
### Summary:

If you set the opacity of the overlay to say .8, all its children will inherit that too including the modal itself

### Expected behavior:

Should be able to set overlay's opacity without affecting the modal window

### Additional notes:

Need to take the modal out of the overlay container

**Comment by madeinspace** [comment]
Ignore you can use rgba without affecting the descendant, sorry! closing

**Comment by im1dermike** [comment]
@madeinspace I'm running into this same problem and can't figure out how to resolve it even after your closing comment.  My overlay div has a class which applies the following styles: `opacity: 0.8; background-color: #131313;`.  The child modal div undesirably inherits this same opacity.  I tried adding `opacity: 1 !important;`, but it did nothing.  Little help?

**Comment by fozenite** [comment]
The fix @madeinspace mentioned works. Refer https://stackoverflow.com/questions/5662178/opacity-of-divs-background-without-affecting-contained-element-in-ie-8/5662662. Change your overlay background to a rgba color.

**Comment by hinchley2018** [comment]
The [example](https://codepen.io/claydiffrient/pen/KNjVrG) of using CSS styles linked in the README was very helpful as well.
It allows you to target the .Overlay separately
