### ISSUE TITLE
Drag stop (mouseup) on Overlay closes Modal

### ISSUE THREAD

**Issue by tobiloeb** [reactjs/react-modal#515]
### Summary: 
I'v seen some other issues that was marked as resolved, but I can reproduce this Issue in current version 2.3.3. In case I stop dragging on the overlay, the modal is closing. I have added an example: https://codesandbox.io/s/1r60668vm7

### Steps to reproduce:

 1. Open the modal in the example.
 2. Drag the slider around and move it outside of the modal.
 3. Stop dragging (mouseup) outside of the modal and it will be closed.

### Expected behavior: 
The modal should stay opened.

### Link to example of issue:
https://codesandbox.io/s/1r60668vm7

**Comment by diasbruno** [comment]
@tobiloeb This issue is valid. Tested on safari and chrome, only on chrome this bug shows up.

**Comment by diasbruno** [comment]
@mrsilver256 opened a PR to fix it and it's on review.

**Comment by diasbruno** [comment]
@tobiloeb The fix will be release as `2.4.1`, so if you have updated to `v3` RC, you will have to wait a little more, but I'll make a forward port to `v3`.
