### ISSUE TITLE
CSS warning - Unable to locate source of warning

### ISSUE THREAD

**Issue by haydencarlson** [reactjs/react-modal#517]
### Summary:
Ok so I've removed react-modal component from rendering and this warning goes away but anytime it's included in my project it throws it.

It's just a nuisance. I've tried finding where it comes from but can't locate it in the package.
### Steps to reproduce:
Installed -> render react-modal ->
``` 
Warning: Unsupported style property -webkit-filter. Did you mean WebkitFilter? Check the render method of `ComponentName`
```
### Expected behavior:
No warning.

**Comment by diasbruno** [comment]
@haydencarlson Can you provide more information about this, like are you using style attribute or a class with pith property?

**Comment by haydencarlson** [comment]
@diasbruno 
`Version 2.3.2`
```
<Modal
        isOpen={this.props.open}
        onAfterOpen={null}
        onRequestClose={null}
        style={customStyles}
        contentLabel="Example Modal"
      >
     </ElementsHere>
</Modal>
```

```
const customStyles = {
      content : {
        top                   : '50%',
        left                  : '50%',
        right                 : 'auto',
        bottom                : 'auto',
        marginRight           : '-50%',
        transform             : 'translate(-50%, -50%)'
      }
    };
```

I'm using the style attribute and this is how i'm rendering it with those exact styles.

**Comment by haydencarlson** [comment]
I just updated to 2.3.3 with no change.

**Comment by diasbruno** [comment]
This should be ok. Are you doing some image processing or do you have any scripts to apply filters or a css class with 'filter' property?

**Comment by haydencarlson** [comment]
No I'm not.
I guess I should have mentioned this is a react on rails project, this could have something to do with the asset pipeline maybe?

**Comment by diasbruno** [comment]
@haydencarlson Maybe...Perhaps, you can check if any other dependency has something to do with filters.

Since it doesn't seems to be related to react-modal, I'll mark as `wontfix`, for now. Please, feel free to reopen if you find something. 

Thank you.
