### ISSUE TITLE
Changelog generation may be broken again?

### ISSUE THREAD

**Issue by dlong500** [reactjs/react-modal#522]
It looks like there is something up with the changelog again, as it was "updated" in the 3.0 release but only shows a duplicate `v2.4.1` instead of having a proper `v3.0.0` section.  Did the fix back in September somehow not make it into the `next` branch?

**Comment by quachsimon** [comment]
Jumping on the topic as well. Can we easily update to this new version? Are there breaking changes? I could not find any change logs from migrating to v3.0.0?

**Comment by diasbruno** [comment]
@quachsimon No, there are no breaking changes. The major version bump was just to make where the support for React 16 is available.

@dlong500 I'll fix the changelog, I don't know yet if it's a bug or regression.

**Comment by diasbruno** [comment]
The issue is sometimes I release a version on the machine (home or at office) and the repository has some missing tags. This confuses the changelog generator.

I'll be more careful on the next releases.

**Comment by diasbruno** [comment]
CHANGELOG was updated. Thanks!

**Comment by rimunroe** [comment]
Is it possible this may have happened again? d6931d13 added a section for 3.4.4, but the section contains a single empty bullet point.
