### ISSUE TITLE
DOM elements not cleaning up upon <Modal/> close

### ISSUE THREAD

**Issue by catamphetamine** [reactjs/react-modal#523]
I can see with 3.0.0 that DOM nodes are leaking.

Each time I open and close the same modal (using the same button) it creates a new DOM node with is not being recollected after the modal closes.

![image](https://user-images.githubusercontent.com/477167/31302514-fc4efac0-ab0a-11e7-80eb-6c97383661cf.png)

**Comment by catamphetamine** [comment]
Wow, this is really a bug in my code.
Nvm.
Closing.

**Comment by diasbruno** [comment]
Thanks, god. Is everything good so far?

**Comment by catamphetamine** [comment]
Ha ha. Yeah)
