### ISSUE TITLE
Production build throws ReferenceError.

### ISSUE THREAD

**Issue by kennykaye** [reactjs/react-modal#526]
### Summary:
When running react modal in production, `ModalPortal` throws a `ReferenceError` due to incorrect `PropTypes` import. `PropTypes` should be imported as a default import and not a named import.

### Steps to reproduce:

 1. Create a sample project that depends on react-modal.
 2. Set `process.env.NODE_ENV` to "production".
 3. Load application.

### Expected behavior:
react-modal should not throw `ReferenceError` when initializing component.

### Additional notes:

```javascript
index.js:11 Uncaught TypeError: Cannot read property 'bool' of undefined
    at Object../node_modules/react-modal/lib/components/ModalPortal.js (index.js:11)
    at __webpack_require__ (index.js:1)
    at Object../node_modules/react-modal/lib/components/Modal.js (index.js:11)
    at __webpack_require__ (index.js:1)
    at Object../node_modules/react-modal/lib/index.js (index.js:11)
    at __webpack_require__ (index.js:1)
```

See: 
<img width="731" alt="screen shot 2017-10-07 at 3 23 01 pm" src="https://user-images.githubusercontent.com/3267574/31312277-7b5f7840-ab73-11e7-86be-fcb8150cd778.png">

**Comment by kennykaye** [comment]
It looks like this was reverted 47d0d878c1cdff1ad024c28acb78fba9afadb1a1. This problem persists in `3.0.2`

**Comment by diasbruno** [comment]
Hmm, probably rebase...I'll push a fix. Thanks!

**Comment by diasbruno** [comment]
Reapplied your commit. Releasing version `v3.0.3`.
