### ISSUE TITLE
Problem with modal window in IE9

### ISSUE THREAD

**Issue by VitaliyInshakov** [reactjs/react-modal#528]
Hi! I have error when i want open modal window in my react project in IE9

> Failed to get the "add" property of a reference whose value is not defined or is NULL
inside function:
function add(bodyClass) {
  // Increment class(es) on refCount tracker and add class(es) to body
  bodyClass.split(' ').map(refCount.add).forEach(function (className) {
    return document.body.classList.add(className);
  });
}

**Comment by diasbruno** [comment]
Hi @VitaliyInshakov, which version of `react-modal` you found this bug?

**Comment by VitaliyInshakov** [comment]
v.2.3.2

**Comment by diasbruno** [comment]
Hm, `classList` is not available on `IE10-`. You can use a polyfill for it like [github:yola/classlist-polyfill](https://github.com/yola/classlist-polyfill).

**Comment by diasbruno** [comment]
Hi @VitaliyInshakov, have you tried the polyfill?

**Comment by VitaliyInshakov** [comment]
Hi, I tried this polyfill, but it didn't help me, so I searched again and found https://github.com/jwilsson/domtokenlist  and it really helped in IE9. Thanks for help

**Comment by diasbruno** [comment]
Great, thanks for sharing your solution. It is good for us to keep the code base clean and modern as possible, so a polyfill is the way to go in this situations. 

One thing we need is to show which browsers versions we support by default though.

**Comment by diasbruno** [comment]
I'm closing this for clean up. Thanks!
