### ISSUE TITLE
Omitting afterOpen in the className prop causes "undefined" string in class

### ISSUE THREAD

**Issue by benknight** [reactjs/react-modal#533]
### Summary:

Minor, but the string "undefined" is added to the modal element's class attribute when `afterOpen` is omited from the className object, e.g.

```js
<Modal className={{ base: 'modal' }} />
```

### Expected behavior:

"undefined" should never be cast to a string and added to a className.

**Comment by diasbruno** [comment]
Hi @benknight, in this case, prefer passing just a string `className={"modal"}`.

**Comment by diasbruno** [comment]
I'm tagging as `not a bug`, but perhaps we need to improve the documentation for this case.

**Comment by diasbruno** [comment]
@benknight Thanks. Hope my answer helped. I'm closing this for clean up. Please, feel free to reopen this issue.

**Comment by benknight** [comment]
Ah I didn't realize jut a string could be passed.  I would suggest using PropTypes to validate.  Something like 

```
className: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.shape({ ... }),
]),
```

**Comment by diasbruno** [comment]
Correct! Can you PR this?

**Comment by diasbruno** [comment]
The shape must contain `base`, `afterOpen` and `beforeClose` as `string`.

**Comment by diasbruno** [comment]
@benknight Thanks for the suggestion. It'll be available on the next release.

**Comment by benknight** [comment]
Great.  I'm happy to PR but it looks like you're all set now.  Thanks for
this improvement!
