### ISSUE TITLE
beforeClose Class is not working

### ISSUE THREAD

**Issue by facuch19** [reactjs/react-modal#543]
### Summary:
When i close the modal, it isn't changing the _afterOpen_ class instead of the _beforeOpen_  class. In react dev tools i can change the beforeOpen state, and so it finally works, but when i'm closing the modal either clicking escape or clicking in the close button or on the overlay area it isn't work.

**Comment by sw-yx** [comment]
thanks for the report. are you able to reproduce this bug in codepen so we can investigate?

**Comment by facuch19** [comment]
@sw-yx  Yeah, sure!

**Comment by facuch19** [comment]
hi @sw-yx, here is an example: https://codesandbox.io/s/k3jpyn9x5o.

If you look the modal when it is opening, you can see the css effects, but when you close it, the css classes are not working.

**Comment by diasbruno** [comment]
@facuch19 when using animations to close the modal use `closeTimeoutMS={n}`. If it is not defined the modal closes immediately.

**Comment by facuch19** [comment]
@diasbruno OMG bro, i was using `closeTimeoutMS={n}`. But i was using it with seconds....  `closeTimeoutMS={2}`, and it works with ms  `closeTimeoutMS={2000}`. Now itś working perfectly.Anyway is good know it. Thanks you very much for the time.

**Comment by diasbruno** [comment]
Awesome. 

...and thanks @sw-yx for taking the lead and start reviewing the issue.
