### ISSUE TITLE
Close on Escape key does not work`

### ISSUE THREAD

**Issue by rodryquintero** [reactjs/react-modal#550]
### Summary:
From what I am seeing in the documentation the "close on Escape" feature does not work as advertised.

### Steps to reproduce:
Just setup a minimal modal component.

### Expected behavior:
Close on Escape key press

### Link to example of issue:
```
<Modal
                tabIndex={1}
                ref="modal"
                style={modalStyle}
                isOpen={isOpen}
                contentLabel="Settings"
                onRequestClose={this.handleClose}
            >
            <div ref="card" className="ui fluid widget-modal card" onKeyDown={this.handleKeyPress}>            
                <div className="content">
                    {children}
                </div>
                <div className="extra content">
                    <div className="ui buttons">
                        <button className="ui button">
                            <i className="save icon"/>
                        </button>
                        <button onClick={handleClose} className="ui button">
                            <i className="close icon"/>
                        </button>
                    </div>
                </div>
            </div>
        </Modal>
```
### Additional notes:
I included a callback for `onRequestClose` but it is not triggering when pressing `esc`. I thought it was weird.

**Comment by diasbruno** [comment]
Hi @rodryquintero, can you make an example on 'codesandbox.io'? It's better for debugging because you can define something closer to what you are using (like version of the libraries you are using...).

**Comment by diasbruno** [comment]
is `this.handleKeyPress` has a prevent default or something? Maybe this handle is preventing the 'esc' key from triggering the modal close.

**Comment by diasbruno** [comment]
cc @rodryquintero

**Comment by diasbruno** [comment]
@rodryquintero Please, feel free to reopen this issue if there is a bug on react-modal. Thank you.

**Comment by rodryquintero** [comment]
Will do
