### ISSUE TITLE
What's the functionality of react-modal?

### ISSUE THREAD

**Issue by hundsim** [reactjs/react-modal#551]
### Steps to reproduce:

 1. Go to https://reactcommunity.org/react-modal/examples/minimal.html and run any of the examples.

### Expected behavior:
Take from W3: "A modal is a dialog box/popup window that is displayed on top of the current page." 

### Link to example of issue:
When trying out the examples there's no layover effect at all. A box with borders and rounded courners appears with a button to close the box.

### Additional notes:
Perhaps I'm missing the purpose of react-modal, but as the short description reads "Accessible modal dialog component for React" I thought the examples would show exactly that.

**Comment by diasbruno** [comment]
@hundsim Modal is a blocking view that prioritize its scope/context. If you can see in the example, there is a white overlay and the button 'toggle modal' gets 'disabled' until you provide an action (close the modal). The accessible part means that It follows some guidelines to make it accessible like pressing ESC to close and be able to read on screen readers.

Although, `react-modal` has been improved and now it's a little bit more flexible in terms of accessibility. In some cases, you may want to disable some feature like 'ESC to close', return the focus to the previous element and so one...
