### ISSUE TITLE
Printing modal is cut after one page

### ISSUE THREAD

**Issue by eranshabi** [reactjs/react-modal#555]
### Summary:
There is a cut in the content of the modal you print (`window.print()`) after one page.
### Steps to reproduce:

 1. Try to print content of modal which height is more than one page.

### Expected behavior:
modal content will not be cut after one page
### Link to example of issue:
https://codesandbox.io/s/zl6ro436ql
Open the modal, then click 'PRINT'

### Additional notes:
I think the solution is to change the `position: fixed` to `position: static` of `ReactModal__Overlay` only when printing.

**Comment by diasbruno** [comment]
Hi @eranshabi, probably the best way is the user provide the print style, but we could provide a style example so people can at least have some idea of what to do though. Maybe add this to the documentation?

**Comment by eranshabi** [comment]
Do you mean the users should provide new style using the style prop?

**Comment by diasbruno** [comment]
Via `<link media="print" />`.

**Comment by diasbruno** [comment]
@eranshabi Did you find a way to solve your problem?

**Comment by eranshabi** [comment]
Yes, I just override the ReactModal__Overlay class.

**Comment by diasbruno** [comment]
Great! I'll close this issue, but I'll try to update the docs later. Thank you.

**Comment by buzztnt** [comment]
Hey guys, was this added to the documentation? I've tried overriding the `ReactModal__Overlay` to `position: static` in my media query but still experiencing the same issue.
