### ISSUE TITLE
Getting this error in production with React 16

### ISSUE THREAD

**Issue by firaskrichi** [reactjs/react-modal#557]
<img width="424" alt="screen shot 2017-11-09 at 12 12 42 pm" src="https://user-images.githubusercontent.com/9126737/32632334-57da8afc-c547-11e7-9fd5-ffa374d7c5de.png">

**Comment by firaskrichi** [comment]
Any ideas what might have cause this?

**Comment by diasbruno** [comment]
Hi @firaskrichi, sorry for the later reply. Which version of `react-modal` are you using?

**Comment by firaskrichi** [comment]
Hi @diasbruno my bad it's another package causing the pb :)
