### ISSUE TITLE
cannot set focus to text field with mouse

### ISSUE THREAD

**Issue by bob-gallagher** [reactjs/react-modal#566]
I believe the fix for #564 has introduced this problem as things were working fine up to and including release 3.1.3 but fail with 3.1.4.

I have a modal component that has `input` components. Clicking with the mouse on one of these `input` fields does not bring focus to the field. Clicking on buttons does function as expected. 

shouldCloseOnOverlayClick={false}

**Comment by diasbruno** [comment]
Hi @bob-gallagher, that make sense. 
Probably we can check if the click is in fact on the overlay (?)

**Comment by diasbruno** [comment]
I'll revert this change if this option don't work.

**Comment by diasbruno** [comment]
@bob-gallagher can you please confirm if #567 provides the correct behavior?

**Comment by diasbruno** [comment]
Released `v3.1.5`. 

@bob-gallagher Please, reopen this issue if it doesn't fix the issue. Thank you.

**Comment by bob-gallagher** [comment]
Worked like a charm, thanks.

**Comment by diasbruno** [comment]
Great! Thank you for report this issue!
