### ISSUE TITLE
Focus is not returned on modal unmount in versions prior to 3.1.6

### ISSUE THREAD

**Issue by OliverJAsh** [reactjs/react-modal#573]
I just noticed a bug that existed in versions prior to the 3.1.6 that appears to have been fixed incidentally by https://github.com/reactjs/react-modal/commit/38dc8f9, specifically https://github.com/reactjs/react-modal/commit/38dc8f9#diff-14851ac17110ae8daabed39063cc885eR102.

Although this is no longer an open issue, I wanted to file it so it is documented and discoverable for other users on older versions who may run into this issue.

Steps to reproduce (versions prior to 3.1.6):

1. Focus an element outside of the modal
2. Mount the modal
3. Unmount the modal

Expected:

Originally focused element should have focus returned.

Actual:

Focus is not returned.

This is because the `returnFocus` function is called by `afterClose`, which was only called when `isOpen` changed from `true` to `false`.

Since https://github.com/reactjs/react-modal/commit/38dc8f9, we know call `afterClose` on `componentWillUnmount` as well, thereby fixing this issue. https://github.com/reactjs/react-modal/commit/38dc8f9#diff-14851ac17110ae8daabed39063cc885eR102

**Comment by OliverJAsh** [comment]
Closing as this is fixed, but the issue is now discoverable to other users.

**Comment by diasbruno** [comment]
Thanks for the awesome report.
