### ISSUE TITLE
Issue with Modal and redux

### ISSUE THREAD

**Issue by thedrew12** [reactjs/react-modal#579]
### Summary:
I have a simple component that opens a modal on click and renders a button inside the modal. When the button inside is clicked it sends off a redux action which logs the user in. The issue is as soon as a successful request comes back the modal closes automatically and gets removed from the DOM even though the state prop `isOpen` is still true. If I don't go through redux and call the function directly it doesn't close the modal. I would expect the modal to stay open until a function got called to close the modal. Any ideas for why this is happening?
```
return [
      <p key="login" onClick={() => this.setState({ isOpen: true })}>
        Login
      </p>,
      <ReactModal
        key="modal"
        isOpen={this.state.isOpen}
        onRequestClose={() => this.setState({ isOpen: false })}
      >
        <p
          onClick={e => {
            this.props.login()
          }
          }
        >Login</p>
      </ReactModal>
]
```

**Comment by diasbruno** [comment]
It can close if you set `this.state.isOpen` to `false`, or, you change the route (if using react-router) or render other component instead of your login component.

**Comment by thedrew12** [comment]
`render other component instead of your login component` Yeah, thats what is happening. The login component gets removed after you are authenticated and thats why the modal closes. I was trying everything and missing that one part. Thanks!

**Comment by diasbruno** [comment]
Awesome! I'm glad it helped.
