### ISSUE TITLE
Modal opened by using mouse right click was not closed even if I clicked ModalPortal.

### ISSUE THREAD

**Issue by Jongkeun** [reactjs/react-modal#590]
React-modal is not closed at first click on Linux.
If Modal is opened by mouse right click like a contextmenu, the modal is closed by twice clicking.
A modal that I opened as mouse left click is normal.
And the strange situation is broken only on  **_Linux_**.

### Steps to reproduce:
 1. click the button using mouse right click.
 2. click a background using mouse left click. The modal is not closed.
 3. click a background using mouse left click again. Then the modal is closed.

### Expected behavior:
 I need to close it at once although I opened a modal using mouse right click.

### Link to example of issue:
[this is sample code](https://codepen.io/jongkeun/pen/PEQqbY)

### Additional notes:
Thank you for your project.

**Comment by diasbruno** [comment]
This is a very curious scenario. It is also reproducible on Safari (OS X).

**Comment by Jongkeun** [comment]
It is normal until version 2.3.3.

**Comment by diasbruno** [comment]
Thanks. I'll check if something has changed on the handlers from `2.3.3..latest`.

**Comment by Jongkeun** [comment]
Check the pull request.
I added some code.
I don’t know if that is right.
Anyway I hope to fixed soon.
Cheer!
