### ISSUE TITLE
<li> element through which modal is generated not going into background until mouse off

### ISSUE THREAD

**Issue by shantsimonian** [reactjs/react-modal#594]
### Summary:

I'm using React 16, and I have an unordered list, and each li element in the list contains a button that is supposed to trigger a react-modal to appear. Whenever the button is clicked, the modal appears, but the whole li element that generated the modal remains in the foreground (in front of the modal) until the mouse leaves the borders of the li element. The modal covers everything else except the specific li element through which the modal was triggered.

### Expected behavior:

The modal should come into foreground and cover all other elements upon clicking the button that triggers it.

### Additional notes:

Note that I am using react-modal in conjunction with Bootstrap 4 (so my ul and li elements contain bootstrap classes).

Is react-modal expected to work properly with Bootstrap?

**Comment by diasbruno** [comment]
Hi @shantsimonian, did you set up `react-modal` to use the bootstrap modal classes?

**Comment by diasbruno** [comment]
[https://github.com/reactjs/react-modal/blob/master/examples/bootstrap/app.js](https://github.com/reactjs/react-modal/blob/master/examples/bootstrap/app.js) Here is an example to use react-modal with bootstrap.

**Comment by shantsimonian** [comment]
Hi @diasbruno, thanks for your response -- I'll give this a shot today!

**Comment by shantsimonian** [comment]
@diasbruno Tried it out - the same issue still persists. The styles look good now, though (they are bootstrap styles). Does the app element have to be the direct parent of the modal? Because I've currently set the app element to be the root div of my application (the one that I've manually created and given an id to in index.html).

**Comment by shantsimonian** [comment]
Hey @diasbruno - so I was able to finally solve the problem by adding a high z-index value to the class `.ReactModal_Overlay`. I just set the z-index to 10000 and that fixed the issue. I'm not sure if this is a general problem or not, but I think it might be worth looking into or at least documenting! Thanks again for providing me with that link.

-Shant
