### ISSUE TITLE
ESQ close

### ISSUE THREAD

**Issue by AshotN** [reactjs/react-modal#595]
Is it possible to add the functionality of pressing the ESQ key to close the model?

Thanks

**Comment by diasbruno** [comment]
Hi @AshotN, This feature is already present in react-modal and enabled by default. Here is an example of how to use it:

```js
<Modal isOpen={this.state.isOpen} onRequestClose={handleRequestClose}>
   {/* modal content */}
</Modal>
```

where `handleRequestClose` is a function that toggle the state of `isOpen` on your component.

**Comment by diasbruno** [comment]
I'll close this since this feature is already available. Thanks!
