### ISSUE TITLE
NVDA: Arrow Keys (Read mode) not working: 

### ISSUE THREAD

**Issue by karunkamal** [reactjs/react-modal#600]
### Summary:
Focus goes on modal and Arrow key triggers default action (scrolling page). 

### Steps to reproduce:

 1. Open NVDA , Firefox. Open Modal
 2. the focus goes on and read the heading (aria-label/contentLabel) of modal defined
 3. Pressing DOWN ↓ Arrow key should read next content, instead it does not.

### Expected behavior:
Screen reader should read next content avalable inside modal

**Comment by diasbruno** [comment]
@karunkamal can you check if there are any element receiving the focus instead of the one with the scroll.

**Comment by karunkamal** [comment]
@diasbruno I threw focus on the input inside the modal, and still i couldn't use the arrow key to go to next content after/before input. Pressing ESC key here would close the modal, making rest of the content non-accessible except the one which are tabbable.

**Comment by diasbruno** [comment]
Can you write an example, please?

**Comment by karunkamal** [comment]
https://codesandbox.io/s/1rwvyykjvq

Doesnt seem to be issue, will cancel this

**Comment by diasbruno** [comment]
Ok, @karunkamal. I'll try to find some time to review this.

I'll close this, for now, but please, feel free to reopen if you confirm it is an issue on react-modal.
