### ISSUE TITLE
How to retain background scroll position after closing modal ?

### ISSUE THREAD

**Issue by NithishReddy** [reactjs/react-modal#606]
Hi,
 I am implemented Modal in React. 
But after closing modal, document is going to top of the page, it is not retaining its scrolled position (i.e scroll position of page before opening modal).

Any solution??

**Comment by diasbruno** [comment]
Hi@NithishReddy, check out PR #588. It may have some ideas to help with this issue.

**Comment by diasbruno** [comment]
I'm closing this for clean up. Please, follow #614 for more information about this since it seems related.

Thank you.
