### ISSUE TITLE
Tab focus escapes modal on shift + tab after opening

### ISSUE THREAD

**Issue by jasonblanchard** [reactjs/react-modal#607]
### Steps to reproduce:

 1. Open modal
 2. Hit `shift` + `tab` (before doing anything else)
 3. You'll see that the tab focus will move outside the modal.

### Expected behavior:
Tab focus is _always_ trapped inside the modal when it is open.

### Link to example of issue:
This can be reproduced in all the examples in this repo.

**Comment by jasonblanchard** [comment]
I'm working on a fix now, I _think_ it's small.

**Comment by diasbruno** [comment]
Hi @jasonblanchard, here is a place to look [src/helpers/scopeTab.js#17](https://github.com/reactjs/react-modal/blob/master/src/helpers/scopeTab.js#L17).

Probably we should move the focus to the last element like this case [src/helpers/scopeTab.js#L26](https://github.com/reactjs/react-modal/blob/master/src/helpers/scopeTab.js#L26).

Hope this info can help.

**Comment by jasonblanchard** [comment]
@diasbruno Yup, that's exactly it. Pushing up a PR momentarily.
