### ISSUE TITLE
Uncaught TypeError: Cannot read property 'makeHref' of undefined

### ISSUE THREAD

**Issue by Asgator** [reactjs/react-modal#61]
http://codepen.io/anon/pen/MwRmKd?editors=001

'React-router' Link on modal failed context router.

If generate Modal on the fly

**Comment by morpheyesh** [comment]
I have this same issue. trying to figure it out

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in over a year.  I'm assuming that this is no longer an issue.  If it is, please feel free to re-open.
