### ISSUE TITLE
Modal was not closed if I clicked ModalPortal by mouse right button.

### ISSUE THREAD

**Issue by Jongkeun** [reactjs/react-modal#619]
### Summary:
It may be intentional or not, but there is case like a title.
It was normal until version 1.6.5.
I think [it](https://github.com/reactjs/react-modal/commit/4232477489162511943be62dd20b2b72f28cd6d5) was start point of this issue.
Before, onMouseup and onMouseDown were separated.
However, as it merges into one, the left mouse and right mouse functions are disconnected.

### Steps to reproduce:

 1. open a `Modal`.
 2. mouse right click the `ModalPotal`'s area.

### Expected behavior:
I think that whether using `preventDefault` or not is up to user.
I thought two way's solution.

- _**One**.Add a onContextMenu event at ModalPortal's render._
  **onContextMenu={this.handleOverlayOnClick}**
> 
    <div
        ref={this.setOverlayRef}
        className={this.buildClassName("overlay", overlayClassName)}
        style={{ ...overlayStyles, ...this.props.style.overlay }}
        onClick={this.handleOverlayOnClick}
        onContextMenu={this.handleOverlayOnClick}
        onMouseDown={this.handleOverlayOnMouseDown}
        onMouseUp={this.handleOverlayOnMouseUp}
        aria-modal="true"
      >

 - _**Two**. make an option for this operation for someone who doesn't need._
 ex) **shouldCloseOnOverlayRightClick**

### Link to example of issue:
test for [this case](https://codepen.io/jongkeun/pen/LQjBxq)

**Comment by diasbruno** [comment]
#609 (`v3.2.1+`) introduced the feature to get the references for the overlay and content. So it is possible to manage this cases.

It would be convenient to have this feature, something like `onOverlayContextMenu`, but I'm trying to not introduce application-specific behaviour.

I'll leave this open for discussion and it fits a more general case, we can get this on `react-modal`.

**Comment by diasbruno** [comment]
cc @MaksimKniazeu If you have any comment/advice regarding accessibility about the "right click to close" and "context menu".

**Comment by Jongkeun** [comment]
@IlyaPomaskin, @MaksimKniazeu
Could you help me please?

I read your commit and tried to using `overlayRef` but I can't what I need.
I don't know if I'm a beginner. I started javascript on last November. Sorry.
Could you give me [example](https://codepen.io/jongkeun/pen/LQjBxq?editors=0010) for user?
I want to close `Modal` when I clicked `ModalPortal` by mouse right button.

**Comment by diasbruno** [comment]
@Jongkeun, I'm so sorry, I was doing a lot of stuff today and I forgot to give some hints.

Here is one approach...

```jsx
class MyComponent extends React.Component {
  onContextMenu = (event) => {
     /* what to do */
  }
 
  overlayRef = (ref) => {
     if (ref) {
        /* ref is a DOM element, so you can add the listener here */
      } else {
        /* don't forget to remove thte listener */ 
      }
      this.overlay = ref;  
   }

  render() {    
    return (
       <Modal {/* modal properties */}
               overlayRef={this.overlayRef}
       </Modal>
     );
   }
}
```

Hope this helps!

**Comment by Jongkeun** [comment]
Thanks.
It was very helpful to me.
