### ISSUE TITLE
Misleading Codepen Demo

### ISSUE THREAD

**Issue by sgriffey** [reactjs/react-modal#620]
### Summary:
The codepen demo for "Using shouldCloseOnOverlayClick" is misleading because that attribute is set to false. When trying to experience the close behavior on overlay click, the demo therefore doesn't work. Once I edited the JS to be shouldCloseOnOverlayClick={true}, all works as planned.

### Steps to reproduce:

 1. Visit NPM package[https://www.npmjs.com/package/react-modal]
 2. Click "Using shouldCloseOnOverlayClick" demo at bottom list
 3. Click trigger modal
4. Try and click bg-overlay.

### Expected behavior:
The modal to close on overlay clicking. By setting the prop to true all works normal. Easy fix.

### Additional notes:
Super nitpicky, but updating pen will stop others from experiencing the brief confusion I did.

![image](https://user-images.githubusercontent.com/4163309/36557300-bc222926-17bc-11e8-89c6-e8082f3a68c7.png)

**Comment by diasbruno** [comment]
@sgriffey Yeah, you are right. I think we demonstrate both cases. Can you create the example?

**Comment by sgriffey** [comment]
@diasbruno example of modal closing on overlay click here:
https://codepen.io/sbgriffi/pen/WMyBaR

**Comment by diasbruno** [comment]
@sgriffey Can you, please, review PR #621?
