### ISSUE TITLE
setAppElement throws error in tests

### ISSUE THREAD

**Issue by nickaversano** [reactjs/react-modal#632]
### Summary:
When running in `test`, the `lib/helpers/ariaAppHider.js:24` throws:

`Error: react-modal: No elements were found for selector #app.`

### Expected behavior:

Should not throw errors in test.

**Comment by diasbruno** [comment]
Have you tried to set `Modal.setAppElement` on you tests?

**Comment by nickaversano** [comment]
In order to fix this issue, I did the following in all my components that use react-modal:

```javascript
if (process.env.NODE_ENV !== 'test') ReactModal.setAppElement('#app');
```

**Comment by diasbruno** [comment]
Great. That's one way. 

Another way would be to move the `setAppElement()` to a file that doesn't go into the tests. 

In case your tests really need to set the element, here is an example (but this will depend on the test environment):

```jsx
ReactModal.setAppElement(document.createElement('div'));
describe("test component that uses modal", () => {
   ...
});
```

**Comment by daru23** [comment]
I had the same issue, 

Work around of it like this 

```
if (this.props.modalApp) {
            Modal.setAppElement(this.props.modalApp);  //'#app'
        }
```

**Comment by diasbruno** [comment]
@daru23 @nickaversano #668 should fix this on testing environments. 

I'll close this for clean up. Reopen this issue if that didn't solve this case.

Thanks!

**Comment by brandondurham** [comment]
I just ended up dropping this on the modal:

```
ariaHideApp={ !process.env.NODE_ENV === 'test' }
```

**Comment by iagowp** [comment]
@diasbruno I still have the issue, running on 3.6.1.

When you said that it should fix the issue, you meant with no aditional code, right?

**Comment by glentakahashi** [comment]
I too am having the same issue, #668 didn't fix this for me.

**Comment by dndhm** [comment]
You can get around this issue by stubbing `document.querySelectorAll` in your tests:
```
  beforeEach(() => {
    document.querySelectorAll = () => ["node"];
  });
```

**Comment by derekhamilton** [comment]
I got rid of the error in a dumb way.

```
import * as Modal from 'react-modal';

it('renders without crashing', () => {
    Modal.setAppElement = () => null;
    ReactDOM.render(<Foo />, div);
});
```

**Comment by abhirathore2006** [comment]
I got similar error . i am using  `jest` so i decided to follow below solution

Solution: 
setup global mock for React Modal and override setAppElement method

```
//__mocks__/react-modal.js
const Modal = require('react-modal')

const oldFn = Modal.setAppElement
Modal.setAppElement = element => {
  if (element !== '#___gatsby') oldFn(element)
}
module.exports = Modal

```

**Comment by csreyes** [comment]
was able to work around the error by setting `appElement` directly on the modal.

```
    <Modal
      appElement={document.querySelector('#app)}
    >
```

**Comment by cis-zeeshan** [comment]
Guys, you can just simply set a mock function for this and get out of this. taddaaaa

```
jest
  .spyOn(Modal, "setAppElement")
  .mockImplementation(url => console.log(`setAppElement:'${url}'`));
```

Happy coding!!

**Comment by haseeb075** [comment]
> In order to fix this issue, I did the following in all my components that use react-modal:
> 
> ```js
> if (process.env.NODE_ENV !== 'test') ReactModal.setAppElement('#app');

Where should I put this line of code

**Comment by frankstepanski** [comment]
Will this problem ever be fully addressed?

**Comment by diasbruno** [comment]
@frankstepanski Do you have some spare time to investigate this?

**Comment by jamie--stewart** [comment]
We use a jest-flavoured version of @elle-the-dev's solution:

```typescript
import ReactModal from 'react-modal';
jest.spyOn(ReactModal, 'setAppElement').mockImplementation(() => null);
```

**Comment by WillyAntunez** [comment]
This works for me 😳

jest.mock('react-modal', () => ({
    ...jest.requireActual('react-modal'),
    setAppElement: () => {}
}))

**Comment by Anatoliy13Kravchenko** [comment]
Maybe for someone, it could be useful. I have a common library for all my projects and actually, there I keep my component which uses 'react-modal' inside, some kind of wrapper for my purposes. 
So when I test it on the level of library
`if (process.env.NODE_ENV !== 'test') ReactModal.setAppElement('#root');`
usually enough, but when I test my client projects, where I use the final 'react-modal' wrapper, it doesn't work.
Considering, that modal can be imported dynamically I do this via **lazy import.**

`const CodeBaseModal = React.lazy(() => import('@some-library/modal'));`
or you can do that 
`const ReactModal= React.lazy(() => import('react-modal'));`

Hope it helps.
