### ISSUE TITLE
Remove usages of unsafe lifecycle methods

### ISSUE THREAD

**Issue by Hypnosphi** [reactjs/react-modal#637]
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

**Comment by kaushik94** [comment]
@Hypnosphi @diasbruno can I take this up? I am guessing this involves polyfilling the components so that they can be used with the current react version?

**Comment by diasbruno** [comment]
Sure, @kaushik94. Follow the [react-lifecycles-compat](https://github.com/reactjs/react-lifecycles-compat) guide and everything should be fine.

**Comment by Hypnosphi** [comment]
https://github.com/reactjs/react-modal/pull/639#discussion_r179925995

**Comment by Hypnosphi** [comment]
Plus `ModalPortal` still uses cWRP: https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L79
