### ISSUE TITLE
ESC key doesn't close modal

### ISSUE THREAD

**Issue by shaun-sweet** [reactjs/react-modal#641]
### Steps to reproduce:

 1. go to this codepen https://codepen.io/anon/pen/PRdWdB (its in your example docs)
 2. Try to close the modal with the esc key
 3.  Won't close

### Expected behavior:
Should close

### Additional notes:
Any ideas?  I have looked thru the source code a bit, but will dig some more after lunch.  This breaks accessibility.

**Comment by diasbruno** [comment]
Hi @shaun-sweet, `shouldCloseOnEsc` depends on `onRequestClose={Function}` to handles the close action.

Here is an example of [onRequestClose](https://codepen.io/claydiffrient/pen/KNjVBx).

**Comment by shaun-sweet** [comment]
Awesome!    I must have missed that in the docs because I was looking at the source code thinking it shouldn’t work haha.   
  

  
I’ll check the docs again and perhaps open a PR for a change if it was obvious   
  
  
  
 Regards,  
Shaun Sweet
  
  
  
  

  
  
>

**Comment by diasbruno** [comment]
Ok, @shaun-sweet. I'm going to close this issue and if you can find this reference, you can reopen o open a new issue to fix it. Thanks.
