### ISSUE TITLE
ReactModal or Modal?

### ISSUE THREAD

**Issue by SteveALee** [reactjs/react-modal#648]
The code, readme and examples import and use `Modal` but the examples use `ReactModal` and that is what I need to import in my code.

What gives?

**Comment by diasbruno** [comment]
Hi @SteveALee, the name of the variable can be anything, but need to be careful about the rules to import (see the first import rule).

```js
// import using the name `Modal`, but can be anything (resolve for export default).
import Modal from 'react-modal'; 

// this would try to find an item exported with the name `Modal`.
import { Modal } from 'react-modal'; 

// import all symbols in the namespace `Modal` (object).
import * as Modal form 'react-modal'; 
```

**Comment by SteveALee** [comment]
Thanks @diasbruno 
> the name of the variable can be anything
Ah, of course you are using default export . D'oh! I forgot those as I always usually use { Name } format myself.

Oh, the typings that vs code picks up from @types seem to be quit old - 3.1. probably doesn;t matter. 
in vscode or I get

**Comment by diasbruno** [comment]
I'm just trying to get as much information as possible, so if other people looks for this issue, they have something to read.

We had some issues about this - I believe related to the definition for react-modal on @types. I'm not sure if that was fixed on react-modal side or theirs.
