### ISSUE TITLE
package.json "module" field is pointing to a non existent file

### ISSUE THREAD

**Issue by rocketspacer** [reactjs/react-modal#650]
Build tools will likely prefer "module" if it exists, fallback to "main" if it doesn't. See [here](https://rollupjs.org/guide/en#publishing-es6-modules)

Current "module" field in [package.json](https://github.com/reactjs/react-modal/blob/master/package.json#L6) is pointing to **"./src/index.js"**, which doesn't get published. Causing confusions for build tools, in my case, parcel-bundler.

**Comment by diasbruno** [comment]
@rocketspacer Released `3.4.4`. Can you validate the fix?
