### ISSUE TITLE
Improvements for aria-modal

### ISSUE THREAD

**Issue by afercia** [reactjs/react-modal#654]
Based on the specification, the ARIA property [aria-modal](https://www.w3.org/TR/wai-aria-1.1/#aria-modal) must be used on the element that has the `role="dialog"` (or `alertdialog`). Instead, `react-modal` uses it on the element that contains the modal, see #359 / #570.

https://www.w3.org/TR/wai-aria-1.1/#aria-modal
> Used in Roles:  window (abstract role)
> Inherits into Roles: alertdialog dialog

See also the example in the ARIA Authoring Practices 1.1:
https://www.w3.org/TR/wai-aria-practices/#dialog_modal
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

> Notes on aria-modal and aria-hidden

> - The aria-modal property was introduced in ARIA 1.1. As a new property, screen reader users may experience varying degrees of support for it.
> - **Applying the aria-modal property to the dialog element** replaces the technique of using aria-hidden on the background for informing assistive technologies that content outside a dialog is inert.
> - In legacy dialog implementations where aria-hidden is used to make content outside a dialog inert for assistive technology users, it is important that:
>   - aria-hidden is set to true on each element containing a portion of the inert layer.
>   - The dialog element is not a descendant of any element that has aria-hidden set to true.

So, to my understanding, while we wait for browsers and assistive technologies to adapt to this new property, keep using `aria-hidden` on the content outside the modal is still recommended. However, `aria-modal` should be set on the element that _is_ the modal (i.e. the one that can receive the `role="dialog"`).

**Comment by techieshark** [comment]
Just to update an old thread...

> I've tested a bit aria-modal="true" and seems it's broken in Safari 11.1 😞

I just tested Safari 13 with VoiceOver and it worked great on the same page. If `aria-modal` is the future, is it time to go... Back To The Future?

![image](https://user-images.githubusercontent.com/1072292/89982881-df33dd00-dcb9-11ea-8c34-8282c0a6160a.png)

**Comment by youf-olivier** [comment]
Also in the current version, the modal are not accessible, because we have a aria-hidden on the root element and nothing else in the modal, right ?
