### ISSUE TITLE
How to send in data-* attributes to ReactModal component?

### ISSUE THREAD

**Issue by joetidee** [reactjs/react-modal#656]
I am wanting to send in a `data-*` to the underlying element of the `ReactModal` component - how do I do this? For example,

`<ReactModal data-synthetics="something" >...</ReactModal>`

**Comment by diasbruno** [comment]
@joetidee Sorry for the delay. I've merged #657 and now we have data attributes available on react-modal.

**Comment by diasbruno** [comment]
I'll close this for now. Please feel free to reopen if it still an issue. Thanks.
