### ISSUE TITLE
Please close on mousedown

### ISSUE THREAD

**Issue by LeoIannacone** [reactjs/react-modal#658]
### Summary:

Please call onRequestClose on mousedown event rather than on click

### Steps to reproduce:

 1. Create a modal with a content
 2. Mousedown on the content, move the mouse out on the overlay
 3. Relase the mouse

### Expected behavior:
The modal should not close because the user started the click on the content

**Comment by diasbruno** [comment]
I'll close this for clean up. Reopen this issue if you can provide more information regarding this issue. 

Thanks.
