### ISSUE TITLE
Readme example shouldCloseOnOverlayClick does not work

### ISSUE THREAD

**Issue by ajthinking** [reactjs/react-modal#660]
### Steps to reproduce:

 1. Go to https://codepen.io/claydiffrient/pen/woLzwo
 2.  Press Trigger modal 
 3. Press outside the box, on the overlay - it does not close the modal!

**Comment by codeniko** [comment]
You need to define `onRequestClose` since it appears `shouldCloseOnOverlayClick` and `shouldCloseOnEsc` depend on it. Check out https://github.com/reactjs/react-modal/issues/462

**Comment by ajthinking** [comment]
Thanks, though onRequestClose is already defined in the example and I cant find any other solution in #462

**Comment by soorajvnair** [comment]
hey @ajthinking in your codepen, shouldCloseOnOverlayClick is set to false. If you want to close when clicking on the overlay, that needs to be set to true.

**Comment by LuminescentMoon** [comment]
I have a similar issue. I've verified that `Modal` has `shouldCloseOnOverlayClick: true` via devtools. I've verified that the function passed as `onRequestClose` fires on both pressing Esc and clicking the overlay using a `console.log` statement. I've verified that `this` in the `onRequestClose` handler is pointing to at least a component with the correct name using `console.log`.

But somehow, closing the modal using Esc works, but closing the modal by clicking on the overlay doesn't. In the latter scenario, the `this.setState` line in the `onRequestClose` handler is somehow being ignored, but not in the former scenario as I've inspected the component with devtools and saw that `isOpen` has not changed to false.

**Comment by LuminescentMoon** [comment]
Interesting... Pressing Esc to close the modal also does not work if I click the overlay first before pressing Esc.

**Comment by drake-smith** [comment]
@LuminescentMoon I just saw your comment from July 11, 2018. I am experiencing the same behavior right now, where shouldCloseOnOverlayClick is not working, but pressing Escape is. However, if I click on the overlay at least once first (which doesn't close), and then hit Esc, it does not close. 

I am using react-modal ^3.11.2

**Comment by diasbruno** [comment]
@drake-smith Did you get any error messages related to the method, or, is there something else that you need the `stopPropagation`?
