### ISSUE TITLE
How to make the whole modal scroll

### ISSUE THREAD

**Issue by bvv218** [reactjs/react-modal#661]
I set up example from the example folder, but I can't seem to find a way to be able to scroll the whole modal (not the content of the modal). Is there a way to do it?

**Comment by diasbruno** [comment]
Hi @bvv218, do you want to scroll on the overlay or inside the content?

**Comment by bvv218** [comment]
Hi @diasbruno, to be able to scroll modal on the overlay.

**Comment by diasbruno** [comment]
@bvv218 Did you find a solution? I guess you can use some css or edit some of the modal style properties...

**Comment by bvv218** [comment]
@diasbruno Yes, I did. Had to override some default css styles.
