### ISSUE TITLE
We should update the lifecycle

### ISSUE THREAD

**Issue by andrevvalle** [reactjs/react-modal#662]
REF: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

react-modal uses getSnapshotBeforeUpdate() but also contains the following legacy lifecycles:
  componentWillReceiveProps
  componentWillUpdate

The above lifecycles should be removed.

**Comment by diasbruno** [comment]
Hi @andrevvalle, it is for backward compatibility with react `16.3-`. Future releases, probably when react-modal gets ready for `4.0+`, we can deprecate those lifecycle methods.

**Comment by ryami333** [comment]
I highly recommend this approach @diasbruno: https://github.com/reactjs/react-lifecycles-compat

**Comment by diasbruno** [comment]
@ryami333 Yeah, we are already using this package. It was used as explained on the documentation, but perhaps we need to update to the latest version.

**Comment by diasbruno** [comment]
I'll close this in favor of #669
