### ISSUE TITLE
Sprint for react-modal v4.

### ISSUE THREAD

**Issue by diasbruno** [reactjs/react-modal#669]
It's time for react-modal to get ready for `react 16.3+`, this includes:

## Checklist

1. Deprecate old lifecycle methods and remove polyfills.
2. Decide how long we can maintain react-modal versions below `v4` (backports or another approach).
3. Improve documentation where missing.
4. Add more examples.

If you want to give it a try on any item on the list, create a new issue and assign to you.  

Appreciate ideas regarding this update and help with all the listed items.

**Comment by diasbruno** [comment]
#653, #654 and #656 are good issues to be included in this sprint.

**Comment by kaushik94** [comment]
@diasbruno I am fixing #656 currently. I can help out with the other too also.

**Comment by wszgxa** [comment]
PR to fix #653 : https://github.com/reactjs/react-modal/pull/683

**Comment by diasbruno** [comment]
Thanks, @wszgxa. I'll have a look on the PR.

**Comment by diasbruno** [comment]
Moved to milestone `4.0`.
