### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wwwebman** [reactjs/react-modal#670]
I am wonder why do you  use 'clicking prevention' technique like below:
https://github.com/reactjs/react-modal/blob/f715a69e31b00eaf7912595a9bd2d22ab5cecdb3/src/components/ModalPortal.js#L269

Why just not use e.stopPropagation() is that case?

**Comment by diasbruno** [comment]
Hi @wwwebman, you can check if you can get this in the logic of clicking and dragging from `content > overlay` and `overlay > content`. It would be great to find a cleaner way to do it.

**Comment by diasbruno** [comment]
I'll close this issue for clean up. Please reopen if you can discuss further on how we can archive this. 

Thanks, @wwwebman.

**Comment by wwwebman** [comment]
ok, @diasbruno, thanks
