### ISSUE TITLE
Modal does not display correctly, cuts off top part

### ISSUE THREAD

**Issue by bau123** [reactjs/react-modal#673]
### Summary:
When I create a modal with too much text or images, the modal does not give the correct scroll features and will cut the top part of the modal
### Steps to reproduce:

 1. create a modal
 2. a too many lines of text
 3.modal cannot display all text correctly and cuts off top part

**Comment by krean93** [comment]
I am using bootstrap grid on the app and I am experiencing the same problem. 
My current styles:
![image](https://user-images.githubusercontent.com/26706301/43151272-02a1751a-8f6c-11e8-9b53-2344a38f3ab5.png)
