### ISSUE TITLE
How to disable overlay

### ISSUE THREAD

**Issue by itaditya** [reactjs/react-modal#686]
I'd like to show a modal on top of other content but don't want that the overlay because then the other content won't remain interactable. Can we do this?

**Comment by diasbruno** [comment]
Hi @itaditya, You can do with some css. Basically you can set the size of the overlay to be the same as the content.

**Comment by itaditya** [comment]
Oh ok got it. Thanks

**Comment by diasbruno** [comment]
@itaditya Let me know if that idea worked. Thank.

**Comment by itaditya** [comment]
Yes it worked @diasbruno

**Comment by diasbruno** [comment]
Good to hear that. :+1:

**Comment by sachinkreeti** [comment]
Can we do something like this `overlay: { position: static }`. This works for me since the overlay does not have any width and height.

Thanks!
