### ISSUE TITLE
Desktop Safari - Error in scopeTab.js

### ISSUE THREAD

**Issue by DarudeGarystorm** [reactjs/react-modal#687]
If focus is set to an element that isn't focusable, when the user tabs the variable x in scopeTab.js will be set to -1, then when tabbable[x].focus() is called an error will occur.

**Comment by diasbruno** [comment]
Hi @DarudeGarystorm, that's true. Is this cause by a manual focus or a 'non-tabbable' element is getting the focus?

**Comment by DarudeGarystorm** [comment]
In my specific case the focus is being set programmatically in the onAfterOpen function to a non-tabbable element, then the user is trying to tab.

Do you think we should go with the browser default when tabbable.indexOf(document.activeElement) is undefined? Or do you have another solution that would work?

**Comment by diasbruno** [comment]
Not sure if this is a bug. Can you write a small reproducible example?

It's always nice to let the browser handle to focus, but sometimes we can see some different behaviour like #680. But if you need to control the focus, than it's always nice to write how it will give back the focus.

**Comment by DarudeGarystorm** [comment]
Small example: https://codesandbox.io/s/jzwwrzy3y3
You might need to refresh the react-modal dependency it kept loading an older version for me

**Comment by diasbruno** [comment]
What is the goal to focus this particular element?

**Comment by diasbruno** [comment]
If you are trying to make the heading readable by voice over, you can try this:

```js
<Modal id="modalA"
       isOpen={modalA}
       onRequestClose={() => this.toggleModal("A")}
       onAfterOpen={this.afterOpen}
       aria={{ labeledby: "modalTitle" }}>
  <h1 id="modalTitle">
    Focus is here
  </h1>
  ...
</Modal>
```

**Comment by DarudeGarystorm** [comment]
The reason for setting the focus was that I had/have a bug where voiceover (iOS Safari) doesn't focus the modal when it opens. I'll try to make a small example of that

**Comment by DarudeGarystorm** [comment]
If I can get access I'll happily make a PR that checks if the tabbable element exists in scopeTab.js

```
  // If the tabbable element does not exist,
  // let the browser control the focus
  if(typeof(tabbable[x]) === 'undefined') return;

  event.preventDefault();

  tabbable[x].focus();
}
```

**Comment by DarudeGarystorm** [comment]
Hi @diasbruno, when are you planning your next release? I'm waiting for this issue to be fixed...
