### ISSUE TITLE
Pass the event through the onCloseRequest

### ISSUE THREAD

**Issue by roine** [reactjs/react-modal#69]
I want to allow close on ESC press but not on overlay click, can you pass the event through the `onRequestClose` prop.

**Comment by cbrwizard** [comment]
I + for this, or maybe provide an option to not close on overlay click as some modals need this behavior.

**Comment by baer** [comment]
+1 for this. I need to control how/when the modal is closed. Some modals need to be able to close on blur + escape + button, some should not be closable at all.

**Comment by mzabriskie** [comment]
Would be happy to accept a PR for this.

**Comment by claydiffrient** [comment]
Closing because #91 was merged.
