### ISSUE TITLE
Clicking the overlay or pressing the escape key won't close the modal

### ISSUE THREAD

**Issue by daformat** [reactjs/react-modal#705]
### Summary:
Click the overlay or pressing the escape key doesn't close the modal

### Steps to reproduce:

 1. Open modal
 2. Try clicking the overlay
 3. Try pressing the escape key

### Expected behavior:
The defaults state that clicking the overlay or pressing the escape key should close the modal.

### Link to example of issue:
https://codepen.io/claydiffrient/pen/KNxgav

**Comment by diasbruno** [comment]
Hi @daformat, if possible, can you please review those examples and see if we have missed any update with the current implementation?

**Comment by daformat** [comment]
Hello, I thought that by default clicking on the overlay or pressing the escape key would close the modal, but didn't get that I needed to add the `onRequestClose` prop for this to work.

Sorry about that
