### ISSUE TITLE
onAfterClose prop passing

### ISSUE THREAD

**Issue by ibrahimovfuad** [reactjs/react-modal#708]
### Summary:
Hi!
ReactModal component can accept onAfterOpen prop, but I need to use something like onAfterClose but i don't see it in docs.

### Expected behavior:

Need to pass onAfterClose as prop.

**Comment by diasbruno** [comment]
Hi @ibrahimovfuad. You can achieve this using `onRequestClose` function.

**Comment by jcrben** [comment]
According to the docs http://reactcommunity.org/react-modal/#usage:
> Function that will be run when the modal is requested to be closed (either by clicking on overlay or pressing ESC)
>    Note: It is not called if isOpen is changed by other means.

It does not seem like there's a hook in the `onAfterClose()`? https://github.com/reactjs/react-modal/blob/fc5340027a2ed98309872063d7c8af2e98eb7cca/src/components/ModalPortal.js#L152
