### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Butonix** [reactjs/react-modal#730]
Warning: Failed prop type: Invalid prop `className` supplied to `Modal`.
Warning: Failed prop type: Invalid prop `overlayClassName`

**Comment by diasbruno** [comment]
Hi @Butonix, which version are you using?

**Comment by Butonix** [comment]
Hi!
latest xcode version
and your last archive

**Comment by diasbruno** [comment]
Can you post the stacktrace or logs about those errors, please?

**Comment by yonahforst** [comment]
@Butonix - what was your solution? I'm getting the same error

**Comment by thedaviddias** [comment]
Same issue, any way to avoid Butonix to close the issue so soon? And get some feedbacks for whow was able to solve the issue?

**Comment by danphilibin** [comment]
Leaving this solution here in case anyone has the same issue... in my case I had only included the `base` property in the `className` object. The error went away when I defined all three properties:

```
<Modal
  className={{
    base: 'modal', 
    afterOpen: 'modal-in',
    beforeClose: 'modal-out'
  }}
  overlayClassName={{
    base: 'modal-overlay', 
    afterOpen: 'modal-overlay-in',
    beforeClose: 'modal-overlay-out'
  }}
></Modal>
```

**Comment by diasbruno** [comment]
Thanks, @danphilibin. 

Here is a reference to the property type for [className and overlayClassName](https://github.com/reactjs/react-modal/blob/master/src/components/Modal.js#L39).

When you pass an object to these attributes, that's the correct 'shape' for these object. 

Also, the answer was in the first comment in this issue `Warning: Failed prop type: className`. :man_facepalming:

**Comment by keithpickering** [comment]
I'm supplying objects in the correct format but I'm still getting this error.

**Comment by yeluoqiuzhi** [comment]
I think it is cause by empty css class rules, empty css will be remove by css-loader or something other, so you get empty string when you import styles in css modules
