### ISSUE TITLE
Focus escapes modal when first or last element has style `display: none`

### ISSUE THREAD

**Issue by pzhine** [reactjs/react-modal#732]
### Summary:
The 3.8.1 release of `react-modal` allows the focus to escape when the first or last tabbable element has style `display: none`

### Steps to reproduce:

 1. Open a `react-modal` with a few tabbable elements where the first or last tabbable element style set to `display: none`.
 2. Press tab or shift-tab a few times.
 3. When it gets to the first/last tabbable item, the tab or shift-tab event moves the focus outside the modal.

### Expected behavior:
The tab and shift-tab events never move the focus outside the modal

### Link to example of issue:
https://codesandbox.io/s/4x2nlqq599

**Comment by flurmbo** [comment]
Hi @diasbruno, is it okay if I give a go at this issue?

**Comment by diasbruno** [comment]
Sure, @flurmbo. Contributions are always welcome. Let me know if you need anything.
