### ISSUE TITLE
Chrome: Window scrolls when returning focus to an element after modal closes

### ISSUE THREAD

**Issue by cameracker** [reactjs/react-modal#735]
### Summary:

In chrome, when the modal closes and focus is restored to an element that is scrolled to a non-default position, the window will scroll. In certain settings, such as an editor component like SlateJS or DraftJS, this jump is disorienting to users. 

### Steps to reproduce:

 1. Have focus on an element scrolled near the top of a window
 2. Open the dialog
 3. Close the dialog
 4. Observe that window scrolls to focus on the original element

### Expected behavior:

When focus is restored to an element, the window does not scroll

### Link to example of issue:

Admittedly having some trouble reproducing this in a fiddle or code sandbox. Sorry :(

### Additional notes:

Requires one line change at https://github.com/reactjs/react-modal/blob/master/src/helpers/focusManager.js#L42 to pass `{ preventScroll: true }` to `focus()`

**Comment by diasbruno** [comment]
Hi @CameronAckermanSEL, thanks for reporting this issue. You can submit a PR with any necessary changes and we can further discuss about the correct behavior.

**Comment by CameronAckermanSEL** [comment]
Thanks @diasbruno ! Just put one up. :)
