### ISSUE TITLE
Bootstrap example has default style props

### ISSUE THREAD

**Issue by jonaswindey** [reactjs/react-modal#74]
If you run the current version and go to http://localhost:8080/bootstrap/ , the default styles are applied, together with the bootstrap styles. 

<img width="1152" alt="screen shot 2015-09-29 at 12 27 30" src="https://cloud.githubusercontent.com/assets/3637300/10161622/b099a7e8-66a5-11e5-8065-0857765b171e.png">

**Comment by ekonstantinidis** [comment]
The same happened to me. Did you managed to fix this? Also there are 2 scrollbars when scrolling (one for the modal and one for the page). Any ideas?

![dec 23 2015 23 34](https://cloud.githubusercontent.com/assets/6333409/11985594/095319ca-a9cf-11e5-8d6c-9307d6655e8c.gif)

**Comment by risonsimon** [comment]
anyone found a solution for this? I'm having this issue as well, having multiple scrollbars.

**Comment by hustlzp** [comment]
Remove this line did the trick:

https://github.com/reactjs/react-modal/blob/master/lib/components/ModalPortal.js#L187

**Comment by hustlzp** [comment]
Or less hacky way:

@jonaswindey @risonsimon @ekonstantinidis 

```js

<Modal className="Modal__Bootstrap modal-dialog"
    style={styles}>
</Modal>

const styles = {
    content: {
        position: null,
        top: null,
        left: null,
        right: null,
        bottom: null,
        border: null,
        background: null,
        overflow: null,
        WebkitOverflowScrolling: null,
        borderRadius: null,
        padding: null
    }
}
```

**Comment by sibeliusseraphini** [comment]
:+1:

**Comment by sibeliusseraphini** [comment]
@hustlzp this do not work when you have a navbar, do you know how to fix this?

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in almost a year. I'm assuming that this is no longer an issue. If it is, please feel free to re-open.

**Comment by NewDimension** [comment]
This issue still exists. In the docs it's mentioned that `className` and/or `overlayClassName` need to be set so the respective components don't get passed default styles. [Docs](http://reactcommunity.org/react-modal/styles/classes.html)

In the example, they set `className` to "Modal__Bootstrap" which doesn't correspond to any defined style, but the job of removing default style from the component. However, they don't set `overlayClassName` so the overlay gets the default style. We could set `overlayClassName` to "ReactModal__Overlay" but we still need to fix the CSS.

```
// component.js
      <Modal
          className="Modal__Bootstrap modal-dialog"
          overlayClassName="ReactModal__Overlay" // ADD THIS
           isOpen={this.state.modalIsOpen}
        >
         ...

// style.css

.ReactModal__Overlay {
  -webkit-perspective: 600;
  perspective: 600;
  opacity: 0;
  overflow-x: hidden;
  overflow-y: auto;
  background-color: rgba(0, 0, 0, 0.5);
  position: fixed; // ADD MISSING
  inset: 0px // ADD MISSING
}
...
```
