### ISSUE TITLE
Local development cannot find module webpack-cli/bin/config-yargs

### ISSUE THREAD

**Issue by janzenz** [reactjs/react-modal#744]
I've tried setting up my local development, `npm install` went fine with some `npm audit` suggestions. However, when I run `npm start` I get the error below. I'm using `node@10.11.0` and `npm@6.4.1`.

> Error: Cannot find module 'webpack-cli/bin/config-yargs'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (~/Documents/Projects/react-modal/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by JadeHayes** [comment]
Any luck?  I've ran into this as well.

**Comment by diasbruno** [comment]
It seems that [config-yargs](https://github.com/webpack/webpack-cli/blob/master/bin/config/config-yargs.js) has changed on newer version. 

Can anyone try to add/replace `webpack` with `webpack-cli`?
