### ISSUE TITLE
"ReactModalPortal" is added to body automatically

### ISSUE THREAD

**Issue by majid-amiri** [reactjs/react-modal#749]
### Summary:
The issue is that ReactModalPortal is added to `<body>` Automatically without any contents but it takes the whole screen space and makes all elements of page not to work. 
Here's what is at the bottom of `<body>` when I inspect the page:

`<div class="ReactModalPortal"></div>
`

But if I trigger modal conditionally it would be ok and works nicely. So what am I doing wrong?

Here's my modal component: 

```
import React, { Component } from 'react';
import ReactModal from 'react-modal';
import PropTypes from 'prop-types';

ReactModal.setAppElement('#app');

export default class Modal extends Component {
  static defaultProps = {
    isOpen: false,
    className: 'web-view-modal',
  };

  static propTypes = {
    isOpen: PropTypes.bool,
  };

  state = {};

  render() {
    const { children, closeModal, isOpen, className, ...props } = this.props;
    return (
      <ReactModal
        {...props}
        isOpen={isOpen}
        overlayClassName="no-scroll"
        bodyOpenClassName="no-scroll"
        onRequestClose={closeModal}
        className={className}
        shouldFocusAfterRender={false}
      >
        <div className="close-modal" onClick={() => closeModal()}>
          <i className="st-icon-close" />
        </div>
        {children}
      </ReactModal>
    );
  }
}
```

and here's how I'm triggering this component: 

```
class MainPage extends Component {
  static defaultProps = {};

  static propTypes = {};

  state = {
    showModal: false,
  };

  toggleModal = () => {
    const { showModal } = this.state;
    this.setState({
      showModal: !showModal,
    });
  };

  render() {
    const { showModal } = this.state;
    return (
      <Fragment>
        <PrimaryButton
          title="Open Modal"
          onClick={this.toggleModal}
          type=""
        />
        <Modal isOpen={showModal} closeModal={this.toggleModal}>
          Modal Content
        </Modal>
      </Fragment>
    );
  }
}

```

### Expected behavior:
"ReactModalPortal" should not be added to body automatically

**Comment by diasbruno** [comment]
Hi @majid-amiri, can you please check the css referenced by this class?

**Comment by diasbruno** [comment]
This is the "portal" node. For every modal reference, on its contruction, it creates its own node and removed when you unmound the modal.

Normally, this class doesn't has any style.

**Comment by majid-amiri** [comment]
Hi, it was an issue with the css class provided for portal, it was fixed by removing css class.
Thank you

**Comment by MinhOmega** [comment]
Hi, i have question like that. In body had more `<div class="ReactModalPortal"></div>`. What should i do to remove what ?
Here is modal component: 
```
      <ReactModal
            isOpen={showModal}
            style={customStyles}
            shouldCloseOnOverlayClick={true}
            contentLabel="Some text here"
            ariaHideApp={false}
            onRequestClose={handleCloseModal}
        >
           {children}
        </ReactModal>
```
![image](https://user-images.githubusercontent.com/49482201/133369264-5add178d-0b25-41e0-a174-0a52043d50d7.png)
Pls help. Thanks

**Comment by diasbruno** [comment]
@MinhOmega Actually, you don't need to do anything. 

When the modal first mounted, closed or open, we inject this tag for each modal component. When the modal is finally unmounted, the tag is removed.

It should be a bug if:

- It always created a new tag
- It forgot to remove tag on unmount

**Comment by giacomoalonzi** [comment]
I noticed that I have `<div class="ReactModalPortal"></div>` multiple times, but I didn't get why? I've created components that wrap `ReactModal` to create specific modals with data inside. Is this the issue? Thanks
