### ISSUE TITLE
Nested forms strange behavior

### ISSUE THREAD

**Issue by ramusus** [reactjs/react-modal#751]
### Summary:

I have found, that If modal located inside form and there is another form in modal, they behavior intersects. If I click on submit button in inner form - outer is submitted, if there are errors in inner form, onInvalid event handler of outer form is invoked. This is strange behavior, given that **forms are not nested in a DOM**.

Here is example - https://codesandbox.io/s/1qjlzm6k87. Open console to see logs.

### Steps to reproduce:

 1. click on submit button -> "invalid" in logs
 2. open modal
 3. click on submit button in modal -> "invalid" in logs, but no invalid handler on modal form
 4. put something in input in modal and click on submit button -> "submit" in logs, but no submit handler on modal form

### Expected behavior:

Forms work independently

**Comment by diasbruno** [comment]
Hi @ramusus. According to [W3 - The form element](https://www.w3.org/TR/html5/sec-forms.html#elementdef-form):

```
4.10.3. The form element
....
Content model:
Flow content, but with no form element descendants.
```

It's seems that it's not a good idea to nest form elements, not sure why.

**Comment by ramusus** [comment]
@diasbruno, forms are not nested in a result DOM, they are nested only in React component hierarchy.

**Comment by diasbruno** [comment]
Oh...Sorry about that. You are correct. 

I think this is related to the propagation of synthetic events in react. 

The form elements are on different nodes, but they have a direct path for the synthetic event propagation. I think this can explain why you are getting those logs.

**Comment by ramusus** [comment]
@diasbruno you are right. I have added `e.stopPropagation()` to modal form handlers and behavior straightened up immediately. Here is updated example: https://codesandbox.io/s/9qmy6507vy

Thanks.
