### ISSUE TITLE
ComponentWillUnmount called when component children update

### ISSUE THREAD

**Issue by oneillsp96** [reactjs/react-modal#758]
I have a bit of code, the gist of it is below.  The issue I'm running into is that conditional uodates inside the modal itself is causing componentWillUnmount to run, even when I don't modify isOpen or remove the modal from view.  I even tried hard-coding isOpen to true and still see the issue.  This causes the removal of "ReactModal__Body--open" which I need to style my root div.
What am I doing wrong here to cause didUnmount to fire?

.ReactModal__Body--open  {
    overflow-y: hidden;
    & #root {
        filter: blur(5px);
    }
}

From the codebase, Line 162 in ModalPortal.js:
 bodyOpenClassName && classList.remove(document.body, bodyOpenClassName);

Example

`
<ReactModal
            isOpen={props.isOpen}
            ariaHideApp={false}
            className="c_condition-lists-modal_container"
            overlayClassName="c_overlay c_overlay_dark"
            closeTimeoutMS={200}
        >

const [showContentA, setShowContentA] = useState(true);

{showContentA 
? 
<div>Content A</div>
<div onClick={() => setShowContentA(false)}>Show Content B</div>
:
<div>Content B</div>
<div onClick={() => setShowContentA(true)}>Show Content A</div>
}
</ReactModal>

`

**Comment by diasbruno** [comment]
Hi @oneillsp96, thanks for reporting this issue. 
Can you make a reproducible example on codepen or codesandobox?

**Comment by oneillsp96** [comment]
I could not repro with a small example, and moving the full example code over would take me longer to do than it would be worth.  Just wondering if anyone has had a similar issue (componentWillUnmount running before isOpen is set to false causing "ReactModal__Body--open" to be removed).  Is there any method that would let me tap into componentDidUpdate and manually reset "ReactModal__Body--open" back to the root div if props.isOpen is true?  Do you think a PR would make sense to always re-add ReactModal__Body--open" to body in componentDidUpdate if props.isOpen is true and the class doesn't exist?

**Comment by diasbruno** [comment]
Not sure. It would be better to have a reproducible example, so anyone can help debugging this.

Is your modal inside a conditional render? Something like...

```
{someVariable && <Modal ... />}
```

**Comment by oneillsp96** [comment]
Understandable.  No it’s not inside a conditional render. I just removed the style for now, if I get time I will try to get a working codesandbox up.

Just can’t figure out how the modal is staying open but componentWillUnmount is running.
