### ISSUE TITLE
Support for higher-order components, like Radium

### ISSUE THREAD

**Issue by eriklharper** [reactjs/react-modal#76]
I'm trying to use react-modal with [Radium](http://projects.formidablelabs.com/radium/), which requires you to wrap your root element inside a `Radium()` function call like so:

```
React.render(React.createElement(Radium(App)), document.getElementById('ReactRenderTarget'));
```

Doesn't look like react-modal supports this kind of thing.  My end goal is to be able to use Radium's inline media query styling support to style the modal portal at different breakpoints.  I tried doing this in renderPortal:

```
this.portal = React.render(React.createElement(Radium(ModalPortal(props))), this.node);
```

But I get the error:
```
Uncaught TypeError: inst.render is not a function ReactCompositeComponent.js:789
```

Any tips?

**Comment by djbobbydrake** [comment]
Any updates on this one?

**Comment by eriklharper** [comment]
Sorry, no, and in fact I no longer use Radium anymore, I've since learned that its overkill to use an inline js styling library.  Its better to leverage CSS for the features it already offers and just use inline where necessary.
