### ISSUE TITLE
Launch modal from within modal

### ISSUE THREAD

**Issue by cmoesel** [reactjs/react-modal#761]
### Summary:

Is it possible to launch a modal from within another modal and keep the state of each?

For example, Modal A has a form to fill out.  One of the fields requires complex input, so I want to click a button in the form and launch another modal (Modal B) to assist in creating the complex input.  After Modal B is closed, the first modal should still be active (and updated with the information from B).

Currently it seems like Modals act like a singleton in our app.  When I tried this without doing anything special, attempting to launch the second modal just toggled the first modal so it disappeared and nothing happened.

I'm not asking someone to solve this for me.  I'm just new to React (and React-Modal) and  want to verify it is even possible before investing time in trying to figure out an approach!  So, is this behavior possible w/ the architecture of React-Modal?

Thanks!

**Comment by diasbruno** [comment]
Hi @cmoesel, can you make a reproducible example of this issue, please?

**Comment by cmoesel** [comment]
Hi @diasbruno.  Thanks for the prompt reply.  To be honest, I'm not sure how easily (or quickly) I can pull together a reproducible example. Our project is open source, but there's work to get it running and it requires an account on a 3rd party service to get to the part where I'm running into this problem.  And... I think I'm still too new to React to be able to easily extract the relevant parts into a working example.

In your opinion, however, should it be possible to launch a modal from a modal, and return to the first modal after closing the second?  If you say it should be possible, I will try to find a way on my own!

**Comment by diasbruno** [comment]
No problem. You should be able to nest them. Maybe it's related to the event propagation in react.

Let me know if there is some code I can look at.

**Comment by diasbruno** [comment]
Also, I think there is a test for this case.

**Comment by cmoesel** [comment]
FYI -- this turned out to be a silly issue where the button we were using to launch the second modal wasn't properly identified as type 'button', so it was causing the form on our first modal to be submitted, which then closed the modal.  Doh.  Thanks for your help!
