### ISSUE TITLE
Is it possible to pass an 'id' prop?

### ISSUE THREAD

**Issue by YassienW** [reactjs/react-modal#763]
Can we pass an id prop to the main modal component? If not is this something the developers would consider? I could submit a PR if so.

Thanks

**Comment by diasbruno** [comment]
Hi @YassienW, one option is to use the `data` attribute, example:

```js
<Modal data={{ id: 1 }} />
```

If you want implement this attribute, we can further discuss on the PR.

**Comment by YassienW** [comment]
@diasbruno #765
