### ISSUE TITLE
Tall modal won't scroll

### ISSUE THREAD

**Issue by cassiopagnoncelli** [reactjs/react-modal#771]
Anyone got the chance to have a tall modal (height > 100% of screen size) to scroll correctly?

Although there are libs like react-modal and others to spin up a modal I can't seem to find a solution across them to have a tall modal working the way it should.

**Comment by diasbruno** [comment]
Hi @cassiopagnoncelli , you can try something like this [https://codesandbox.io/s/scroll-view-zlppg](https://codesandbox.io/s/scroll-view-zlppg).

**Comment by cassiopagnoncelli** [comment]
Thanks mate! Actually got it working this morning. Quick question, why isn't body scrolling natively supported? It seems to me to be the most direct use case.
