### ISSUE TITLE
Use React Hooks in README

### ISSUE THREAD

**Issue by nagayev** [reactjs/react-modal#784]
### Summary:
React Hooks in modern way to create a React components and maybe soon classes components will be deprecated.

**Comment by nagayev** [comment]
Can anyone say is it good idea?

**Comment by diasbruno** [comment]
Hi @nagayev, it looks good. Not sure if we should keep both or add them to the documentation. What do you think?

**Comment by nagayev** [comment]
@diasbruno I think classes will deprecate in future, so I think we can use Hooks everyware and delete old docs.

**Comment by diasbruno** [comment]
Hmm...I'm not sure on this one, it would be great to be on the latest version of react, but this transition will take some time, and I don't how is the adoption of hooks going...

Would you mind if we let this open so we can get more input on this? If we get more :+1:, it will be a sign that we can move forward on using hooks.

**Comment by nagayev** [comment]
@diasbruno okey
