### ISSUE TITLE
How can I close the Modal from inside a component that is inside the Modal

### ISSUE THREAD

**Issue by Ofer-Gal** [reactjs/react-modal#800]
### Summary:
I am rendering a component inside the modal because it will contain lots of code.
When the user is done doing his/her job, I want to close the modal from this component.
How do I call the parent closeModal() function?

**Comment by cour64** [comment]
The modal's open state is handled outside the modal component. Pass the function that's being used to close the modal down as a prop or make it accessible via a context.

e.g.

```jsx
function SomeNestedComponent(props) {
  return (
    <button onClick={props.closeModal}>Close</button>
  )
}

function MyModal() {
  const [open, setOpen] = useState(false)

  function openModal() {
    setOpen(true)
  }

  // a function used to set the open state of the modal to false 
  // i.e. close the modal
  function closeModal(){
    setOpen(false);
  }

  return (
    <div>
      <button onClick={openModal}>Open Modal</button>
      <Modal isOpen={open} onRequestClose={closeModal}>
        {/* pass the closeModal function down into the nested component */}
        <SomeNestedComponent closeModal={closeModal} />
      </Modal>
    </div>
  )
}
```

Depending how deeply the component that needs to call the `closeModal` function is nested, it might be better to use the [Context API](https://reactjs.org/docs/context.html) to avoid [prop drilling](https://kentcdodds.com/blog/prop-drilling).

**Comment by Ofer-Gal** [comment]
Thanks
