### ISSUE TITLE
Second modal not working when previously toggling fullscreen through a first

### ISSUE THREAD

**Issue by VicHofs** [reactjs/react-modal#813]
### Summary:
When toggling fullscreen from a first modal, any modals that are subsequently toggled will not appear.
### Steps to reproduce:

 1. Create a modal that closes and toggles fullscreen through some interaction.
 2. Attempt to open a second modal through automated means.

### Expected behavior:
The second modal should open normally even when fullscreen is enabled through the first.
### Link to example of issue:
https://codesandbox.io/s/fullscreen-modal-example-urww9

**Comment by diasbruno** [comment]
@VicHofs Can you check in which element the modals are been mounted?

**Comment by VicHofs** [comment]
@diasbruno I didn’t set it manually, but I meant it to be on the main div (everything)

**Comment by diasbruno** [comment]
Maybe it's not mounting on the element that will be made fullscreen.

You can try this:

```html
<div id="root"> <!-- use #root to be fullscreen --> 
   <div id="app" />
   <div id="modals" />
</div>
```

The `parentSelector` will set where the modals will be mounted.

```js
Modal.setAppElement('#app') // your app must render in this element.
 
<Modal 
parentSelector={document.getElementById('modals')} 
... />
```

**Comment by VicHofs** [comment]
@diasbruno Alright I'll post here again as soon as I try that.

**Comment by diasbruno** [comment]
@VicHofs Have you found a solution for your problem?

**Comment by VicHofs** [comment]
> @VicHofs Have you found a solution for your problem?

No, but I unfortunately don't have a lot of time to look into it right now, so in order to avoid cluttering the issues here I'm closing it temporarily.

Will reopen eventually if I find the time :)

**Comment by diasbruno** [comment]
@VicHofs No problem. 👍
