### ISSUE TITLE
Disable Modal From Closing When Overlay Is Clicked

### ISSUE THREAD

**Issue by ikechukwukalu** [reactjs/react-modal#814]
I would like to make the modal backdrop static. I want to prevent the modal from closing when the overlay is clicked?

**Comment by Doesntmeananything** [comment]
Have you tried using the `shouldCloseOnOverlayClick` prop?

From the [API docs](http://reactcommunity.org/react-modal/):

```javascript
shouldCloseOnOverlayClick={
  true
/* Boolean indicating if the overlay should close the modal */}
```
