### ISSUE TITLE
Bug: React Modal is using ReactDOM on the server

### ISSUE THREAD

**Issue by keeganstreet** [reactjs/react-modal#824]
`Modal.js` is accessing a property of `ReactDOM` when it is first run, regardless of whether `renderPortal` is called or even whether `Modal` is instantiated.

https://github.com/reactjs/react-modal/blob/cec8833cccb3c2b2580cabcdf8fb244e0a4f2b34/src/components/Modal.js#L13

On serverside rendered apps, this code runs in NodeJS, where `ReactDOM` should not be used. If `ReactDOM` is not available, "Cannot read property createPortal of undefined" will be thrown.

To fix this, `isReact16` could be changed from a boolean to a function that returns a boolean so that the `ReactDOM.createPortal` check only runs when needed. Or the approach in  https://github.com/reactjs/react-modal/pull/780 would work too.

**Comment by keeganstreet** [comment]
Hey @diasbruno, would you like a PR to apply the fix (replace `Boolean` with `() => Boolean`)?

**Comment by diasbruno** [comment]
@keeganstreet Sorry for the delay. That would be great. PRs are always welcome.

**Comment by keeganstreet** [comment]
No need to say sorry @diasbruno ! Appreciate all the work you do for open source 🙏 

I have just opened a PR: https://github.com/reactjs/react-modal/pull/825

**Comment by diasbruno** [comment]
Maybe something like this will work: `const isReact16 = canUseDOM && ReactDOM.createPortal !== undefined;`. 
If we don't have browser-like env, we don't render the modal anyways...

What do you think?
