### ISSUE TITLE
Modal scroll events are not propagated

### ISSUE THREAD

**Issue by jamesonhill** [reactjs/react-modal#840]
### Summary:
If you scroll content within a modal instance, that scroll event is not being propagated.

### Steps to reproduce:

 1. Add scroll event listener to window
 2. Open modal with scrollable content
 3. Scroll modal content

### Expected behavior:
Scroll events are propagated the same as click, keypress, etc.

### Link to example of issue:
Example: https://codesandbox.io/s/cool-wave-me7nd?file=/src/App.js

### Additional notes:
My use case is that I have a `<StickyContainer>` component that listens to the window scroll event and applies CSS to the content such that it "sticks" to the top of its container. I have to support IE, so `position: sticky` is not viable. Below is a contrived repro of how it works:
```
const StickyContainer = ({ children }) => {
  const [isSticky, setIsSticky] = useState(false);
  const [offsetHeight, setHeightOffset] = useState(0);

  const containerRef = useRef<HTMLDivElement>(null);

  const handleScroll = () => {
    if (containerRef.current) {
      const { height, top } = containerRef.current.getBoundingClientRect();

      setIsSticky(top <= 0 && document.documentElement.scrollTop >= offsetHeight);
    }
  };

  useEffect(() => {
    if (containerRef.current) {
      setHeightOffset(containerRef.current.getBoundingClientRect().top);
    }
  }, []);

  useEffect(() => {
    window.document.addEventListener('scroll', handleScroll);

    return () => window.document.removeEventListener('scroll', handleScroll);
  }, [handleScroll]);

  return (
      <div className={isSticky ? 'sticky' : undefined} ref={containerRef}>
        {children}
      </div>
  );
};
```

**Comment by jamesonhill** [comment]
In the codesandbox example, scrolling with the modal closed does fire the `console.logs`. Once you open the modal & scroll, the logs are not fired.

**Comment by igorarkhipenko** [comment]
@jamesonhill I'm having exact the same issue right now. Did you find a solution for it?

**Comment by jamesonhill** [comment]
@igorarkhipenko No.  I closed this issue because I don't think it's a bug w/ the library, but actually just unexpected behavior of scroll events in general. In my case, I applied `overflow-y: auto` to a container element inside of the modal. When you do that, the scroll event is fired on that element but not on the window. I reproduced the same behavior in a non-modal scenario.
