### ISSUE TITLE
A Few Errors in the Documentation

### ISSUE THREAD

**Issue by cagreer18** [reactjs/react-modal#844]
### Summary:
Hello, this is my first issue report so I hope that I do not miss any standards in place.
Firstly, I noticed a stray "p" is at the start of a paragraph located [here](http://reactcommunity.org/react-modal/#custom-parent). Secondly, there seems to be a dead link in that same paragraph as well which leads to the 404 page.

### Expected behavior:

I have a feeling that the extra "p" in the paragraph is merely a typo when creating the "p" element for the paragraph, so I raised this as an issue due to me not changing any functional code. I also believe that the link was meant to be updated after some site migration and was simply missed. I believe that the dead link should lead [here](http://reactcommunity.org/react-modal/accessibility/#app-element) instead.

### Additional notes:
I apologize, again, if I missed any standards that should be at place here. I'm new to contributions, so I thought I would raise this as an issue instead of doing a pull request and trying to change the ``README.md``  -- or whatever was used to generate the documentation -- directly.

**Comment by diasbruno** [comment]
Hi @cagreer18 Good catch. Thanks for the report.

Probably I've merged the fix, but didn't publish de documentation - again (🤦 as always).

I'll do it right now.

**Comment by diasbruno** [comment]
@cagreer18  I've just published the docs for the current version. Can you please check if the error is still there?

If everything is fine, you can close this issue. 

Thanks!

**Comment by cagreer18** [comment]
Everything seems good. :-)
