### ISSUE TITLE
How to hide toolbar on scroll in mobile Safari?

### ISSUE THREAD

**Issue by tab** [reactjs/react-modal#849]
### Summary:

How to hide toolbar on scroll in mobile Safari when react-modal is open?

### Steps to reproduce:

When scrolling the page Safari on iOS automatically hides the toolbar.
This is the default behavior.

Everything looks like this

**– toolbar visible**

![IMG_2833](https://user-images.githubusercontent.com/67445/106728884-7eb9a300-663f-11eb-9ff7-95fc1386aa12.PNG)

**– start scrolling down and it hides**

![IMG_2834](https://user-images.githubusercontent.com/67445/106728919-89743800-663f-11eb-815b-a6eb09e2b999.PNG)

When react-modal is visible toolbar isn't hides on scroll and visible all the time

**– toolbar visible**

![IMG_2835](https://user-images.githubusercontent.com/67445/106729091-bd4f5d80-663f-11eb-9328-1e8af3db38ff.PNG)

**– start scrolling**

![IMG_2836](https://user-images.githubusercontent.com/67445/106729163-ce986a00-663f-11eb-8254-c3b6ce1238ed.PNG)

### Expected behavior:

Toolbar is hides on scroll 

### Additional notes:

– react 17.0.1
– react-modal 3.12.1
– iOS 14.4

**Comment by pampanelson** [comment]
any solution?

**Comment by stefanstankovic7189** [comment]
Still no solution?
