### ISSUE TITLE
Modal classname to be added to ReactModalPortal div so we can style modal overlay

### ISSUE THREAD

**Issue by gregg-cbs** [reactjs/react-modal#851]
### Summary
In nextjs when using css modules it is not possible to apply css the modal overlay.

### Steps to reproduce:

 1. In Nextjs add the Modal component to a page
 2. Add a css module style `<Modal className={styles.modal}>`
 3. Notice the style is being added to the `ReactModal__Content` div and not to the parent `ReactModalPortal` div.
 4. So now with modules you cannot style the modal overlay
 5. You should apply the classname to the top most wrapper so users of this package can have as much control as they need - seeing as css works top down.

**Comment by diasbruno** [comment]
Hi @gregg-cbs. `className` is used for the content. 

The options are:

- `className` (content)
- `portalClassName`
- `bodyOpenClassName`
- `htmlOpenClassName`
- `overlayClassName`

Let me know if this helps.
