### ISSUE TITLE
shouldCloseOnOverlayClick and shouldCloseOnEsc don't work, even in React Modal's examples

### ISSUE THREAD

**Issue by nth-chile** [reactjs/react-modal#852]
### Steps to reproduce:

 1. Go here and click on the codepen link https://reactcommunity.org/react-modal/examples/minimal/
 2. Add shouldCloseOnOverlayClick and shouldCloseOnEsc props to the modal
 3. Try to close the modal on overlay click or by pressing escape

### Expected behavior:

shouldCloseOnOverlayClick should close on overlay click and shouldCloseOnEsc should close on esc!

### Link to example of issue:

https://reactcommunity.org/react-modal/examples/minimal/

**Comment by diasbruno** [comment]
Hi @nth-chile, yeah...the examples is very old. It's using `react-modal@1.6.2`, but it's weird that it's not working 🤔.

**Comment by nth-chile** [comment]
Yeah I first noticed because I wanted to use these two flags in my app today, so it seems like an issue with current version

**Comment by diasbruno** [comment]
Have you used `read-modal` on the latest version?

**Comment by nth-chile** [comment]
It is ^3.12.1

**Comment by diasbruno** [comment]
Thanks. Can you make a reproducible example?

**Comment by nth-chile** [comment]
Let me know if this demonstrates the issue: https://codesandbox.io/s/dreamy-cannon-9r360?file=/src/App.js

**Comment by diasbruno** [comment]
`react-modal` used a callback function `onRequestClose` that is called in this cases. 

Try to add to your code and let me know if it solves your problem.

**Comment by diasbruno** [comment]
`onRequestClose` is used to control the state of `isOpen` flag.

**Comment by diasbruno** [comment]
Here is one way to do it. https://codesandbox.io/s/priceless-bouman-f9hq9

**Comment by diasbruno** [comment]
...but we definitely need to update the docs. I'll flag this as `documentation`.

**Comment by nth-chile** [comment]
Ah ok, so the two flags I mentioned just fire `onRequestClose`

**Comment by diasbruno** [comment]
Awesome, @nth-chile.
