### ISSUE TITLE
z-index issue with fullscreen videos stored in modal (Safari only)

### ISSUE THREAD

**Issue by timzekid** [reactjs/react-modal#859]
### Summary:
We use ReactModal to render a video inside of it. For the record - video is rendered using [react-player](https://www.npmjs.com/package/react-player). 
And after we go fullscreen with the video - some elements on the page are rendered on top of the video (hence on top of the modal). Seems like it has something to do with z-index'es. But since it renders as expected until we go fullscreen it makes it harder to figure out.

HTML-wise the modal is rendered in a default way thru a `portal` at the end of the `document.body`.
This bug is only reproducible in **Safari**.

### Steps to reproduce:

You can reproduce it here at [Preply production](https://preply.com/en/online/english-tutors). Just open any of the videos you see in the right-side panel and go fullscreen. Please use **Safari** to reproduce

![image](https://user-images.githubusercontent.com/17126360/112951078-a7dc4880-9143-11eb-9883-8460fd1256ad.png)

![image](https://user-images.githubusercontent.com/17126360/112951043-a0b53a80-9143-11eb-8471-89c79f2a7892.png)

### Expected behavior:

When video is in a fullscreen mode it should be displayed on top of any other elements on the page

**Comment by diasbruno** [comment]
Hi @timzekid, have you found a solution for this? It seems to be a css issue on your project...please let me know it there is something we need to do on react-modal side.

Reopen if necessary.
