### ISSUE TITLE
Background Content Visible in Modal 

### ISSUE THREAD

**Issue by dhairyasenjaliya** [reactjs/react-modal#886]
### Steps to reproduce:

 1. Used as per the example provided in package 
 
Styles that I have passed in modal 

const customStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    background: "rgba(22, 11, 139, 0.8)",
  },
};

<img width="1212" alt="Screenshot 2021-06-09 at 10 00 01 AM" src="https://user-images.githubusercontent.com/47522946/121293652-9b295d00-c909-11eb-9a77-0f47444b5bef.png">

 I want to remove the pagination button as well as Mapbox text from the background

**Comment by dhairyasenjaliya** [comment]
.ReactModal__Overlay {
  z-index: 1000;
}

this workes well

**Comment by philxavier** [comment]
Hey, same issue here..
Where exactly can I do that change? @diasbruno ?

Thanks!

**Comment by diasbruno** [comment]
@philxavier `.ReactModal__Overlay` is the default css class that react-modal generates. So you just need to add to your css something like @dhairyasenjaliya suggested, you just have to adapt to your case.

**Comment by philxavier** [comment]
It works! Thanks a bunch

**Comment by diasbruno** [comment]
Awesome!

**Comment by Jinwook94** [comment]
Thanks a lot!

**Comment by diasbruno** [comment]
@dhairyasenjaliya That would be great. So, I believe the problem is not about react-modal itself, but when the page has to manage `z-index` "by hand".

Here, [react-modal/styles/classes.md](https://github.com/reactjs/react-modal/blob/master/docs/styles/classes.md), is where we need to add something about this.
