### ISSUE TITLE
Error: Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by djbobbydrake** [reactjs/react-modal#89]
Seeing this error in the latest 0.6.1:

```
Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded 
```

Anyone else having this issue?

**Comment by yleclanche** [comment]
Same here.

**Comment by NikitaKis** [comment]
+1

**Comment by samidarko** [comment]
+1
https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

**Comment by antoinerey** [comment]
Same here.

**Comment by mcarlone** [comment]
Same error.

**Comment by djbobbydrake** [comment]
Yup @antoinerey that worked for me. Closing this issue.

**Comment by mgenev** [comment]
Im having this problem too

**Comment by davidwadge** [comment]
Also experiencing the same issue.

**Comment by GBarthos** [comment]
Hi, I'm using react 15.4.0 and react-modal 1.6.5, same thing here.
Removing and installing it anew doesn't change anything...

What is causing this ? Isn't there any fix ?

**Comment by PonderingGrower** [comment]
I'm having this issue when trying to run unit tests using mocha and enzyme. This issue makes it impossible to test components that use Modal.

**Comment by diasbruno** [comment]
Hi all, which versions of `react-modal` are you using? Later today I can have a look on this.

**Comment by PonderingGrower** [comment]
I'm running `15.4.0` of `react` and `1.7.0` or `react-modal`.

**Comment by diasbruno** [comment]
@PonderingGrower can you try with an updated version of `react-modal`?

**Comment by PonderingGrower** [comment]
I can, but it will take a while because I would need to pull it into our internal packaging system to be able to use it first, and I'm pretty much done for today as it's Friday evening.

I can get back to you with an attempt with a newest version on Monday. Thanks for taking a look at this, cheers!

**Comment by diasbruno** [comment]
This issue must be fixed on current version `v2+`. 

I'm closing this issue for clean up. Please, feel free to reopen this issue if needed. 
Thank you!

**Comment by ophite** [comment]
This error with:
15.6.2 -react, 
3.1.13 - react- modal
