### ISSUE TITLE
Allow appElement prop to call setAppElement

### ISSUE THREAD

**Issue by YPCrumble** [reactjs/react-modal#899]
### Summary:

Currently I don't think react-modal is compatible with code splitting using [loadable-components](https://loadable-components.com/) because of needing to call `Modal.setAppElement()`. The issue is that if we load the `Modal` element like this:

`const Modal = loadable(() => import('react-modal'))`

...then `Modal` won't have resolved at runtime when we call `Modal.setAppElement`.

My suggestion is to call `setAppElement` from within the constructor if we pass an `appElement` prop to the `Modal`. 

Thanks for maintaining this repo, and please let me know if a PR to do the above would be welcomed, as I'd love to contribute!

**Comment by diasbruno** [comment]
@YPCrumble Can you try something like this?

```js
const Modal = loadable(() => {
  const comp = import('react-modal');
  comp.setAppElement(x);
  return comp;
})
```

**Comment by YPCrumble** [comment]
Thanks for your idea @diasbruno - the issue with this is that under the hood, loadable-components isn't actually importing the library at runtime - it's delaying the import. So the code above generates something along the lines of this error:

> TypeError: _libraries.Modal.setAppElement is not a function

**Comment by diasbruno** [comment]
Hm...can you setup a something where we can debug this?

**Comment by YPCrumble** [comment]
@diasbruno so sorry - your code works I had just implemented it wrong! Thanks again for this library and your patience with my issue - closing.

**Comment by diasbruno** [comment]
Sem problema, @YPCrumble! Happy to help.
That's great! Did have to change anything on that code? If so, and if you can post it here, it would be helpful for others.

**Comment by YPCrumble** [comment]
Thanks again! The code works as you wrote it above :D.
