### ISSUE TITLE
Modal content not being rendered if env is present in jest config moduleNameMapper

### ISSUE THREAD

**Issue by v1adko** [reactjs/react-modal#900]
### Summary:

Modal content not being rendered using react testing library if env is present in jest config `moduleNameMapper` object
It's a very confusing bug, so this issue can be a reference for other people who may encounter an error
It is not expected to change anything with the library since it's a jest configuration issue 
(easiest fix is to rename your file imports to something like `environment` or `env-variables`)
[Reproduction repo link](https://github.com/v1adko/react-modal-env-testing-issue)

### Steps to reproduce:

1. Pull the repo - `gh repo clone v1adko/react-modal-env-testing-issue`
2. run `yarn` to install dependencies
3. run `yarn test` - confirm that the test passes
4. uncomment 4th line in `jest.config.js`
5. run `yarn test` again - confirm that the test fails, no modal content is present

**Comment by kkowalczuk** [comment]
Keys in `moduleNameMapper` are representing regular expressions and `react-modal` uses `exenv` so I guess it's caught by simple `"env"` as well:

```js
// Works just fine:
"^env$": "<rootDir>/env.js",

// These two produce similar issue:
"env": "<rootDir>/env.js",
"^exenv$": "<rootDir>/env.js",
```

**Comment by v1adko** [comment]
Yes, exactly. This is a better alternative to renaming your file, thanks stranger :)
Given these solutions I think the issue can be closed.
