### ISSUE TITLE
Nested modals

### ISSUE THREAD

**Issue by falaxfala** [reactjs/react-modal#907]
Is there any way make nested modals?

For example, I've got redux slice as modal manager in global scope. I have a modal provider with every modals marked as global modals. Everything works fine, but when I want to open one modal from another (without closing first one), I just can't close the second one by click on overlay. I must click ESC with focus on secondary modal.

Structure is something like: 
```jsx
<div> //Provider
 {children} //Rest of App
 <Modal1>...content</Modal1> //Not nested
 <Modal2>...content</Modal2> //Nested or not - depends of situation
 <Modal3>...content</Modal3>//Only nested
</div>
```

Am I doing something wrong? Is there even possibility of nesting modals?

**Comment by diasbruno** [comment]
Great. 

I'll close this. If you get back using react-modal and find this problem, please reopen this issue.
