### ISSUE TITLE
Ref not passed when rendered inside a modal

### ISSUE THREAD

**Issue by zimmicz** [reactjs/react-modal#914]
### Summary:
Ref is not passed when compnent is rendered inside a modal

### Steps to reproduce:

 1. Go to https://codesandbox.io/s/react-modal-with-elastic-carousel-8hihr?file=/src/App.tsx

### Expected behavior:
I expect ref to be defined inside `useLayoutEffect`.

### Link to example of issue:
https://codesandbox.io/s/react-modal-with-elastic-carousel-8hihr?file=/src/App.tsx

**Comment by diasbruno** [comment]
Hi @zimmicz,

You need to check for the ref to see if the component was actually rendered or not: 

```js
    carousel.current?.sliderContainer.addEventListener("mousemove", () => {
      console.log("mouse moves");
    });
 ```

**Comment by diasbruno** [comment]
I'll close this for now. Let me know if there is any other problem.

**Comment by zimmicz** [comment]
@diasbruno this won't work. If you remove the `ReactModal` parent though, the code works just fine. Even if you use the check you proposed, the event won't trigger, because when the effect runs (on `[]`), the ref is not there. That's what I tried to report: the ref should be defined.

**Comment by diasbruno** [comment]
Ahh, of course, the dependency for the hook was missing...

```js
React.useLayoutEffect(() => {
    carousel.current?.sliderContainer?.addEventListener("mousemove", () => {
      console.log("mouse moves");
    });
  }, [carousel.current]);
```

**Comment by diasbruno** [comment]
Another option you can try is to render the component and store on a state. Problem is that the timer of the carousel will probably start and maybe it won't start correctly.

The reason is that there is a window where the component is not fully rendered, so you won't get the ref first time.

**Comment by zimmicz** [comment]
> Ahh, of course, the dependency for the hook was missing...
> 
> ```js
> React.useLayoutEffect(() => {
>     carousel.current?.sliderContainer?.addEventListener("mousemove", () => {
>       console.log("mouse moves");
>     });
>   }, [carousel.current]);
> ```

According to [epicreact.dev](https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/), it seems refs shouldn't be used as useEffect dep. But if I get that right, there are edge cases to this (and this one seems to be one of them).

I was a bit confused by the fact that ReactModal removal made things work just fine.

**Comment by diasbruno** [comment]
Hmm...another option is to use `onAfterOpen`. This way you will be guarantee that `ref` will exist and you can attach a listener to it.

From the documentation:

```js
  onAfterOpen={
    handleAfterOpenFunc
  /* Function that will be run after the modal has opened. */}
```

```js
onAfterOpen={function () { 
  carousel.current?.sliderContainer?.addEventListener("mousemove", () => {
    console.log("mouse moves");
  });
}}
```

**Comment by diasbruno** [comment]
> I was a bit confused by the fact that ReactModal removal made things work just fine.

That is because react-modal may or may not have been rendered, so its content will also not have been rendered, that's why you don't got a `ref` back.
