### ISSUE TITLE
animation glitch while closing the modal

### ISSUE THREAD

**Issue by chaitanya71998** [reactjs/react-modal#917]
### Summary:
I am trying to make animated children in react modal. So I used keyframes and achieved them. But in iphone 6 chrome while closing the modal with animation there is sudden back jerk. In all other browsers and devices this is working fine, also why i dont know the  transitions are not working in  all Chrome browsers of iPhones (you can see open animation not working).

### Steps to reproduce:

 1. Have an iphone 6 with chrome (my chrome version 92.0.4515.90)
 2. check into the link given below
 3. try opening and closing the modal, you can observe no animation working and issue while closing the modal

### Expected behavior:
The children element should open and close with animation and run smoothly.

### Link to example of issue:
https://codesandbox.io/s/c71998-react-modal-close-animation-forked-sw2s8

**Comment by diasbruno** [comment]
@chaitanya71998 This one is very platform specific...not sure if we can do anything. It's probably something on this particular build of chrome on this particular device.

**Comment by chaitanya71998** [comment]
@diasbruno thanks for the reply check in the way you said.
