### ISSUE TITLE
Migrate to rackt eslint config

### ISSUE THREAD

**Issue by pwmckenna** [reactjs/react-modal#92]
https://github.com/rackt/eslint-config-rackt contains a starting point that all org repos can build off of. This can be introduced by first using the config and overriding any rules that the repo doesn't comply with, without having to change any of the source. Then for non-controversial rules, PRs can be made to update the source to comply.

Here's the initial PR: https://github.com/rackt/react-modal/pull/90

**Comment by claydiffrient** [comment]
I'm going to go ahead and close this, creating a new issue that requests a eslint-config that doesn't appear to be deprecated.
