### ISSUE TITLE
Animations not triggered when `onRequestClose` prop absent

### ISSUE THREAD

**Issue by quicksnap** [reactjs/react-modal#93]
Looks like these lines cause the timeout not to trigger when `onRequestClose` is missing: https://github.com/rackt/react-modal/blob/master/lib/components/ModalPortal.js#L113-L114

So, I am needing to put in an empty function:

```
        <Modal
          closeTimeoutMS={150}
          isOpen={this.props.isModalOpen}
          onRequestClose={() => {}} >

          <LoginForm />

        </Modal>
```

Should we make a change? I could do a PR, but unsure on the best direction.

**Comment by vinceprofeta** [comment]
+1

**Comment by quicksnap** [comment]
Any thoughts on this? I would happily create a PR if that sounds good

**Comment by diasbruno** [comment]
@quicksnap Yes, sir. It seems right to make it optional. +1

Maybe (?) [ModalPortal.js#L87-L88](https://github.com/reactjs/react-modal/blob/master/lib/components/ModalPortal.js#L87-L88)

**Comment by quicksnap** [comment]
I'd happily whip up a PR if a maintainer would give the OK.

**Comment by claydiffrient** [comment]
+1 to that @quicksnap go right ahead and I'll get it in the next release.

**Comment by quicksnap** [comment]
Oh cool! I'll try and get a PR today or in the next few. If I forget for some reason, someone just ping me. Or make the PR themselves =P

**Comment by quicksnap** [comment]
Also, it's odd that you don't have some sort of a collaborator badge, @claydiffrient! **shrug**

**Comment by claydiffrient** [comment]
Indeed @quicksnap... I don't know why I don't have one... but oh well... I am one :)
