### ISSUE TITLE
onAfterClose should accept undefined like onAfterOpen

### ISSUE THREAD

**Issue by goldmont** [reactjs/react-modal#933]
### Expected behavior:
Pass undefined to onAfterClose callback.

Thanks.

**Comment by diasbruno** [comment]
Hey, @goldmont. Actually, onAfterOpen is wrong. This is a case where the application needs to handle...if you are intended to use those callback, you must give it a function (even if a `const noop = () => {}`).

**Comment by goldmont** [comment]
Ok, understanding. Thank you!

**Comment by diasbruno** [comment]
This way we avoid weird types and not to be conservative on our api (adding a lot of checks). Let me know if you have any ideas regarding this. Thanks!
