### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by swissspidy** [reactjs/react-modal#937]
### Steps to reproduce:

 1.
 2.
 3.

### Expected behavior:

It would be nice to add React v18 to `peerDependencies` to mak using this library easier in a React 18 app.

**Comment by VeRJiL** [comment]
still does not work for react v18 using npm

`$ npm i react-modal
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bazar-khodro-web@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16 || ^17" from react-modal@3.14.4
npm ERR! node_modules/react-modal
npm ERR!   react-modal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\VeRJiL\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VeRJiL\AppData\Local\npm-cache\_logs\2022-04-09T07_45_00_855Z-debug.log`

**Comment by swissspidy** [comment]
@VeRJiL That's because a new release has not been published yet. You need to wait for a new release.

**Comment by kkowalczuk** [comment]
@diasbruno I see https://github.com/reactjs/react-modal/commit/403093510eae51b5ee289ee0a08e79ee1be068dd being merged to `master` two days ago, but the _Releases_ section (and NPM registry) still points to 3.4.4 as the most recent release.

What is the process for "official releases" and is there any ETA of 3.5.1?

**Comment by VeRJiL** [comment]
Any updates ?

**Comment by mike-niemand** [comment]
Is there a timeframe for this?

**Comment by diasbruno** [comment]
Hi. I had a little problem with my mac and I'm kinda locked out from npm. Hope to get this done at least by the weekend.

**Comment by diasbruno** [comment]
@swissspidy Want to push this version?

**Comment by swissspidy** [comment]
Sure, if there is any way I can help with publishing to npm, I am happy to

**Comment by thomasfw** [comment]
Any updates on this?

**Comment by swissspidy** [comment]
Unfortunately I think Bruno still first has to regain access to npm in order for anyone to be able to publish a new version.

**Comment by diasbruno** [comment]
Yeah...still working on that. I've reached out to the npm's support to see what we can do.

**Comment by diasbruno** [comment]
Reopened this issue so we can make it visible. Please, help me redirect people to this issues if they open a new one related to this. :joy:

**Comment by diasbruno** [comment]
Finally, the version was released. Thanks for your patience.

**Comment by diasbruno** [comment]
Did you all had a change to verify if it's all good?

**Comment by thomasfw** [comment]
All good, I'm getting 3.15.1 now. Thanks

**Comment by diasbruno** [comment]
@thomasfw but did it work with React 18?
