### ISSUE TITLE
Please, update to ver. 3.15.1 on npm 

### ISSUE THREAD

**Issue by progdog-ru** [reactjs/react-modal#941]

**Comment by timothymalcham** [comment]
This would be great, I'm recently upgraded to React 18 and I'm now experiencing issues with react-modal after upgrading. I see that React 18 was added as a peer dependency in 3.15.1, so I'm hoping that it might resolve some of the issues I'm seeing.

**Comment by diasbruno** [comment]
This is already been taking care of...hope we can get this on npm ASAP.
