### ISSUE TITLE
Not compatible with React 18?

### ISSUE THREAD

**Issue by Coronus117** [reactjs/react-modal#942]
### Summary:
Cannot install with React 18

### Steps to reproduce:

 1. npx create-react-app my-new-app
 2. npm install react-modal
 3. ERROR

**Comment by diasbruno** [comment]
This is already been taking care of...hope we can get this on npm ASAP.

**Comment by Brhernann** [comment]
Why this issue is closed ?

**Comment by Alejoboga20** [comment]
What would be the solution for this?

**Comment by diasbruno** [comment]
@Brhernann @Alejoboga20 Are you having problems with the latest version? You'll need to upgrate do version 3.15.1 to work with react 18+.

**Comment by diasbruno** [comment]
If you are using this version, please feel free to open a new issue.
