### ISSUE TITLE
Opening modal via `onTouchStart` unexpectedly triggers `onRequestClose`

### ISSUE THREAD

**Issue by josephmarkus** [reactjs/react-modal#948]
### Summary:

I have an instance of react-modal, which closes as soon as it is opened.

The modal is controlled by a `<button>`. When using `onClick`, all works as expected. On touch devices (iPhone/iPad) `onClick` doesn't work, so I use `onTouchStart` instead. The code example below has `onClick` removed to demonstrate the issue when using `onTouchStart` alone.

### Steps to reproduce:

 1. Visit https://m7kxnv.csb.app/
 2. Open DevTools
 3. Select iPhone 12 Pro
 4. Click 'Open Modal'
 5. Observe console.log events in DevTools. Notice that both `openModal` and `closeModal` are logged.

### Expected behavior:

`onTouchStart` shouldn't trigger `onRequestClose`

### Link to example of issue:

Sandbox:
https://codesandbox.io/s/suspicious-dream-m7kxnv?from-embed=&file=/src/App.js

Direct link:
https://m7kxnv.csb.app/

### Additional notes:

https://user-images.githubusercontent.com/9258365/168327553-2c4d1b84-67cf-45b8-a94e-1be10c8b9f1f.mov

**Comment by diasbruno** [comment]
`onTouchEnd` triggers the overlay click somehow...

`onTouchEnd={(e) => (e.preventDefault(), e.stopPropagation())}` should fix this issue.
