### ISSUE TITLE
Using react-modal with NextJS

### ISSUE THREAD

**Issue by gustavopolonio** [reactjs/react-modal#949]
What's the right way to use react-modal with NextJS?

In ReactJS we use `Modal.setAppElement('#root')`, being that the `#root` is the body from `index.html`.

What configs I have to do using NextJS?

**Comment by diasbruno** [comment]
Don't set the app element do `<body />` You will hide every node inside of it.

Prefer something like this...

```html
<div>
   <div id="app" />
   <div id="modals" />
</div>
```

**Comment by shaharia1999** [comment]
Any one can hare to fixed this Problem

**Comment by JP-HoneyBadger** [comment]
following

**Comment by diasbruno** [comment]
@JP-HoneyBadger @shaharia1999 @gustavopolonio Can you guys, please, provide an example so we can get a better picture of the problem?

**Comment by rodrigo-muniz-acct** [comment]
I'm using Next 14 and react 18 and it's working for me. I just needed to add the `"use client"` at the top of the file. Like this:

```ts
"use client";

import Modal from "react-modal";

interface MyModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const MyModal = ({ isOpen, onClose }: MyModalProps) => {
  return (
    <Modal isOpen={isOpen}>
      <button onClick={onClose}>Close</button>
      <h2>Modal Title</h2>
    </Modal>
  );
};

export default MyModal;
```
