### ISSUE TITLE
classNames

### ISSUE THREAD

**Issue by thejameskyle** [reactjs/react-modal#95]
I see that `react-modal` used to have the ability to specify classes for styles but that was removed in favor of inline styles.

While some might argue that inline styles are better for react applications, not everyone has that option (including myself).

It would be nice if `react-modal` wasn't opinionated about this and supported both giving classNames and inline styles.

**Comment by paazmaya** [comment]
:+1:

**Comment by nbwar** [comment]
+1 please bring back classNames. Its a pain to do custom animations with inline-styles that can't be overwritten with css.

**Comment by idmontie** [comment]
:+1:

**Comment by thejameskyle** [comment]
For those that are interested I've started a separate project [`react-modal2`](https://github.com/thejameskyle/react-modal2) which is less opinionated, accessible, stateless (dumb component), and is built via a reusable collection of modules. It also allows you to use classNames instead of inline styles.

**Comment by kjs3** [comment]
:+1:

**Comment by OKNoah** [comment]
Seems like very little effort to support both. 👍

**Comment by antoinerey** [comment]
:+1:

**Comment by simpixelated** [comment]
Looks like #100 would fix this, but it hasn't been reviewed/merged yet.

**Comment by claydiffrient** [comment]
v1.0.0 is now released with supported added back for classNames
