### ISSUE TITLE
Switch from KeyboardEvent.keyCode to KeyboardEvent.code

### ISSUE THREAD

**Issue by robinmetral** [reactjs/react-modal#952]
Hi! First of all, apologies for removing the issue template—since this isn't a bug report, I've found it hard to fill the reproduction steps.

I'm wondering if there's anything stopping us from switching from the deprecated [`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) to [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) in the `ModalPortal`:

https://github.com/reactjs/react-modal/blob/0847049f19eaed81715e1263705564a569577774/src/components/ModalPortal.js#L276-L285

We should probably stop relying on the deprecated property, and since [React 18 dropped support for IE](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#dropping-support-for-internet-explorer) (which didn't support `KeyboardEvent.code`), I can't think of any blockers.

Using the deprecated property can already cause issues in browsers (or testing environments) that have removed support for it. I've ran into this using `@testing-library/user-event` ([ref](https://github.com/testing-library/user-event/issues/969)).

Happy to submit a PR for this!

**Comment by diasbruno** [comment]
Hi, if it has been deprecated, we need to update.

PRs are always welcome.

**Comment by robinmetral** [comment]
Awesome, thanks for the reply—will submit some time this week 🙂
