### ISSUE TITLE
Build badge broken

### ISSUE THREAD

**Issue by magicznyleszek** [reactjs/react-modal#967]
### Summary:

The build badge in `README.md` file is broken. It leads to https://travis-ci.org/reactjs/react-modal, which says:

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

I think it should be updated or removed :)

**Comment by memark** [comment]
The badge src is
https://travis-ci.org/reactjs/react-modal.svg?branch=v1
which doesn't work
![](https://travis-ci.org/reactjs/react-modal.svg?branch=v1)

Updating to
https://travis-ci.com/reactjs/react-modal.svg?branch=v1
doesn't help either
![](https://travis-ci.com/reactjs/react-modal.svg?branch=v1)

However keeping the old domain and removing the branch parameter
https://api.travis-ci.org/reactjs/react-modal.svg
does work
![](https://api.travis-ci.org/reactjs/react-modal.svg)

I'll fix the broken badge with a PR, but I'm not sure what to update the link to.

**Comment by diasbruno** [comment]
@magicznyleszek @memark Thanks!
