### ISSUE TITLE
Disable Default Styles?

### ISSUE THREAD

**Issue by idmontie** [reactjs/react-modal#97]
Is there a way to completely disable the default styles?

I was hoping I could just use:

```
var customStyles = {
      overlay : false,
      content: false
    };
```

But, `_.assign` will just ignore the `false` value.

**Comment by mjyoung** [comment]
+1

**Comment by ericsoco** [comment]
I was about to create an issue for the same thing. Only, I was going to create the issue as a suggestion to add this to docs:

> To disable the default styles, specify `null` for each value to disable. This is useful for styling via a stylesheet instead of using inline styles. For example:
> 
>     modalStyles = {
>         content: {
>             background: null
>         {
>     };

**Comment by idmontie** [comment]
@ericsoco It would be useful to have that in the docs, but it is quite annoying to have to override every single property for the content and the background if I want to use classes.

**Comment by Josh-a-e** [comment]
I'd love to see this, at the moment as a temp fix I have all the relevant styles set to null individually

**Comment by mjyoung** [comment]
Yep, @ericsoco's workaround worked for me.

If anyone's interested, these are the styles I'm using to have flexbox position the modal::
https://gist.github.com/mjyoung/c10ed08eefcf2e1d5afc

**Comment by ericsoco** [comment]
@idmontie agreed. I have this in my code now:

			modalStyle = {
				overlay : {
					backgroundColor: ''
				},
				content : {
					top: null,
					left: null,
					right: null,
					bottom: null,
					border: null,
					background: null,
					borderRadius: null,
					padding: null,
					position: null
				}
			};

And that's a little ridiculous.

**Comment by grahamb** [comment]
I just ran into this while updating a project from 0.2 to 0.6.1. @ericsoco's workaround works, but is pretty gross.

#100 looks like it'll fix it.

**Comment by hnq90** [comment]
We should write:
```
content : {
                top: 'initial',
                left: 'initial,
                ....
            }
```

**Comment by sjungwirth** [comment]
> And that's a little ridiculous.

agreed

**Comment by megapctr** [comment]
@ericsoco :+1: I can't understand why defaults are enforced like this

**Comment by pjnovas** [comment]
+1

**Comment by wavded** [comment]
Just opened another issue but then saw this one that is basically asking the same question.  Having to turn off every style seems a little ridiculous and can be breaking if new "default" styles are added.  Would prefer to just turn them off and work within CSS.

**Comment by dzmitry-kremez-itechart** [comment]
+1  Also as I see here https://github.com/reactjs/react-modal/blob/master/lib/components/ModalPortal.js#L183 you disable default styles if there are class names. But it doesn't work in latest(0.6.1) npm and bower lib version. Could you please publish latest master code to npm and bower?

**Comment by claydiffrient** [comment]
@dzmitry-kremez-itechart I'm working on finalizing a few details with the new release.  It will happen soon, hopefully this week.

**Comment by dzmitry-kremez-itechart** [comment]
@claydiffrient cool, thx

**Comment by claydiffrient** [comment]
v1.0.0 was just published and classnames can override defaults now.
