### ISSUE TITLE
When I have a lot of text in a Modal that is bigger than the screen

### ISSUE THREAD

**Issue by es-maor** [reactjs/react-modal#977]
When I have a lot of text in a Modal that is bigger than the screen I can't scroll up or down to see the top of the Modal or the bottom.

**Comment by gautamz07** [comment]
@es-maor have you tried.

```
.ReactModal__Content {
  max-width: 50vw; // modify this value for your use case.
  max-height: 50vh; // modify this value for your use case.
}
```

**Comment by Dunridge** [comment]
@es-maor have you found a solution for this?

**Comment by diasbruno** [comment]
@Dunridge @gautamz07 @es-maor This can be solved using css. You just have to set the frame of the element inside of the modal, and, control using `overflow` property.

**Comment by Dunridge** [comment]
@diasbruno Yeah, the issue is that I can set the overflow and I can scroll but there's no way to set a margin at the bottom of the modal's content. Is there a way to do it?

**Comment by diasbruno** [comment]
I believe if you search on the issues for scroll, you may find some examples. If you don't find any, just let me know.
